- app/views/shared/_contact_panels.html.erb
- app/views/static_pages/contact_us.html.erb
- app/views/static_pages/cysylltu_a_ni.html.erb
- config/application.rb
- config/locales/cy.yml
- config/locales/en.yml
Actually reverting the commit rather than the merge commit.  This is to put the normal (non-holiday) hours back in place on the site.
This reverts commit de6d6e82aa848382bd80b908638e68d1e2e69204.
> Revert "festive open hours"

- Gemfile
- Gemfile.lock
- app/controllers/rio_controller.rb
- config/initializers/rio.rb
- config/routes.rb
- lib/tool_mount_point.rb
- lib/tool_mount_point/rio.rb
- spec/requests/tool_integration/rio_spec.rb
- Unfortunately I can't use the gem version and have to add the git version. As there is already a gem named `rio` on rubygems. We are not on a recent enough version of bundler where the source on a gem can be specified
- The `category_id` has yet to be decided and is subject to change
> mount Retirement Income Options engine

- app/assets/javascripts/require_config.js.erb
This is a small change made to look bigger by the second commit that alpha-sorts the sections. See 35885b7 for the meaningful change.
The path alias for the entry-point script for an engine is constructed
using using the value of the `data-engine` attribute from the engine's
layout with "Config" added on the end (see bottom of application.js).
So these two paths for car_cost_tool and pensions_calculator we never
being used and in fact referred to non-existent files.
See: https://trello.com/c/PlIsKwOm
> Remove invalid/unused RequireJS paths

- app/controllers/rio_controller.rb
- app/views/layouts/engine.html.erb
- app/views/layouts/engine_unconstrained.html.erb
- This allows engines to be not width constrained and use the full width of the page.
- Rio will use this
> Unconstrained engine layout

- app/assets/stylesheets/components/common/_icon.scss
- app/assets/stylesheets/components/common/_icon_2x.scss
- app/assets/stylesheets/components/dough_theme/collapsable/_collapsable.scss
Affects Category landing pages (https://www.moneyadviceservice.org.uk/en/categories/budgeting-and-managing-money) that are using Collapsable. Also tidies up `_icon.scss` and `_icon_2x.scss` by removing duplicate height/width and some empty selectors.
> Reinstate the + icon on .icon--toggle

- app/views/shared/_directory.html.erb
- app/views/shared/_footer_primary.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Adds links to the blog in the category section of the home page and primary footer. This is hard coded for now as the blog is going live on Monday and there is no easy way (or know one knows how) to add a new category in the Category Manager Application. Since that category data is being migrated to the CMS in the next week, this will also be added when that is done so it's dynamic like the others.
> Add blog links

- app/assets/stylesheets/components/page_specific/_want_to_talk.scss
In safari this was overlapping with page content when scolling down the
page
Tested in Chrome, Safari, Firefox, IE8, IE9
> fix want to talk panel in Safari

- config/initializers/disable_minitest_hook.rb
- test.sh
Call cucumber directly to make it return a non-zero exit status.
Previously, running `test.sh` would run `rake cucumber`, which always returns a zero exit code (for some reason). This meant test failures wouldn't fail CI.
> Make failing cucumber fail CI

- app/controllers/application_controller.rb
- app/views/layouts/syndicated.html.erb
- spec/controllers/application_controller_spec.rb
The requirement is when budget planner (or other tool) is syndicated (in an iframe) the user needs to be able to  authenticate. For example they want to save their data which then sends the user to a login screen. The old behaviour is shown in the screenshot below which uses public website and the old budget planner.
The light box/pop up dialog has been removed and is no longer available. I'm also not aware of such a dough component existing to replace it. Instead we send the user straight to the login page and then redirect them back to where they came from. See below..
However we do not want to render the entire site with header and footer when we are in the iframe we want to render the minimal amount in the iframe. The pull request will make the login page look like below...
Changes …
> add syndicated layout

- app/controllers/application_controller.rb
- app/controllers/rio_controller.rb
- spec/controllers/application_controller_spec.rb
Regardless of this change this presents the vulnerability of
clickjacking when tools are syndicated
> move x frame options to ApplicationController

- .rspec
- test.sh
Each time that you run the specs, they run with the build config and you need to overwrite. So let's move this config to the CI test script and add to .rspec only the default config that everybody uses.
> Remove CI rspec config to the main file and move to CI test file

- Gemfile
- Gemfile.lock
- config/initializers/timelines.rb
- config/routes.rb
- lib/tool_mount_point.rb
- lib/tool_mount_point/timelines.rb
- spec/requests/tool_integration/timelines_spec.rb
Adding timelines engine (moving it from `public_website` repository).
Version specified to be at least 1.2.0.
> Timelines update

- Gemfile
We're doing some heavy lifting here, big removals, large change.
This is just to make sure no one runs `bundle update` and pushes it all into production.
> Pin pensions calculator.

- app/assets/stylesheets/components/dough_theme/tab_selector/_tab_selector.scss
See #214 for background information.
Same change has been applied on Dough: https://github.com/moneyadviceservice/dough/pull/220
@moneyadviceservice/frontend
> Fixes missing text in TabSelector - Dough issue #214

- app/controllers/corporate_controller.rb
- app/decorators/content_item_decorator.rb
- app/decorators/corporate_decorator.rb
- app/views/corporate/show.html.erb
- lib/core/entity/article.rb
- spec/decorators/corporate_decorator_spec.rb
- spec/lib/core/entity/article_spec.rb
* This is the basic structure of the Partners/Terms and Conditions and other
corporate pages.
* Today CMS doesn't support forms and some other type of dynamic context, so this extra content is needed.
> Render extra content on corporate articles if partials exists.

- app/assets/stylesheets/components/dough_theme/button/_button.scss
- app/assets/stylesheets/components/dough_theme/pagination_counter/_pagination_counter.scss
- app/views/search_results/_pagination.html.erb
The current pagination does not work well on small device sizes (awkward wrapping). So I have tightened the button dimensions to fix this.
@moneyadviceservice/frontend
> Fix pagination style for small devices

- app/assets/javascripts/syndication/resizer.js.coffee
- app/assets/javascripts/syndication/tool_syndication.js.coffee
- app/assets/javascripts/syndication/tools.js.coffee
- app/assets/javascripts/syndication/widget.js.coffee
As public_website will be decommissioned at some point in the future we are migrating this over to the responsive site. `tools.js` is referenced by the html that partners use to embed a syndicated tool, it is also used by the test_harness repo which allows us to mimick a partner who is embedding a tool.
We found a potential trip wire on the public_website project. This code on `build.sh` and one of the Rake tasks:
```
deploy.rake
run "cp public/assets/syndication/tools.js public/static/tools/tools.js" 
```
We couldn't find any references to "public/static/tools" in the code though.
Other than that we tested this and the code is being served correctly. We added a comment to the code to verify it's being served from frontend and not public_website.
> Migrates tools.js and dependencies from public_website

- Rakefile
- app/assets/javascripts/syndication/tools.js.coffee
- config/initializers/assets.rb
We want to stop serving tools.js from public website and move this to frontend. 
All the embedded partner-tools make use of /assets/syndication/tools.js
We need to make this a seamless migration.
This PR creates "tools.js" with a kind of 'after' hook on assets:precompile.
We are unsure if we need to update the scripts repo as the tools.js from public_website is currently zipped up as 'static-content' and served by nginx. Ideally we want to be using the new version from frontend.
> Making latest tools_<generated_asset_hash>.js available as tools.js

- app/assets/stylesheets/components/page_specific/_retirements_panel.scss
and headline is black if it's not a link
> ensure that correct visited blue is used

- Gemfile
- Gemfile.lock
- app/controllers/action_plans_engine_controller.rb
- config/initializers/action_plans.rb
- config/routes.rb
- lib/engine_mount_point.rb
- lib/engine_mount_point/action_plans.rb
- spec/requests/tool_integration/action_plans_spec.rb
- Action Plans engine has been upgraded to rails 4 and to work with frontend
- This integrates it into frontend as part of the migration
> Migrate Action plans engine

- app/assets/stylesheets/components/dough_theme/backgrounds/_all.scss
- app/assets/stylesheets/components/dough_theme/backgrounds/_backgrounds.scss
- app/assets/stylesheets/components/dough_theme/backgrounds/_settings.scss
- app/assets/stylesheets/components/page_specific/_stripe_banner.scss
- app/assets/stylesheets/components/page_specific/_want_to_talk.scss
- app/views/shared/_want_to_talk.html.erb
- config/locales/cy.yml
- config/locales/en.yml
These changes implement the new design for the Want To Talk widget. 
@stevoland @moneyadviceservice/frontend
id:6195 state: Being Built
> Want to talk - Implement updated design and copy

- app/views/layouts/_base.html.erb
This was on the old website but never migrated over. We're changing it
to use dataLayer.push() for GTM while we're at it. The Budget Planner
and soon hopefully the Health Check, Redundancy Tool and Quiz engines
are meant to set the content for this to be a string that identifies the
tool along with a unique id for user's data. For example 'BP123456'.
> Add toolTrackingId to GA dataLayer.

- app/assets/javascripts/components/WantToTalk.js
- app/views/articles/show.html.erb
The Want to Talk has now been moved above the Related Links section and set to be statically positioned, not sticky, like before.
@moneyadviceservice/frontend
> Want to talk positioning

- app/assets/stylesheets/components/dough_theme/form/_form_input_range.scss
`.form__input-range` was looking a little odd in IE10-11. So we've modified some styles to make it look more like the other browsers do. It does change the height of the slider element by approx 5px in IE, which isn't ideal but the usual negative margin hacks didn't seem to help. Suggestions encouraged!
__Before:__
__After:__
> Fix range input display in IE10-11.

- app/views/shared/_contact_panels.html.erb
No need for the javascript to kick in for the button if it isn't there
This was causing the following JS error on the /en/campaigns/debt-management page (which doesn't have the usual footer).
Uncaught TypeError: Cannot set property 'innerHTML' of null
> Fix issue where chat button isn't present on a MAS page.

- app/controllers/application_controller.rb
Fixes recent issue of category pages blowing up and returning 500s. Incident report can be found here (if you're a MAS employee) https://moneyadviceserviceuk.atlassian.net/wiki/display/DEV/2015-04-23+-+Site+Category+Pages+Down.
> Fix issue when no child categories are present

- app/assets/stylesheets/components/page_specific/_more_in.scss
- app/controllers/styleguide_controller.rb
- app/decorators/category_decorator.rb
- app/views/articles/show.html.erb
- app/views/shared/_more_in.html.erb
- app/views/shared/_related_links.html.erb
- app/views/styleguide/components_website.html.erb
- config/locales/cy.yml
- config/locales/en.yml
so that they can eventually be styled differently.
This needs to be done, as the related links on the right hand side of an article are going to be styled differently from the 'More in' list of links, in another PR
> separating 'More In' and 'Related Links' into two different components

- spec/controllers/retirements_controller_spec.rb
This didn't show up before because the spec file didn't have `_spec.rb` on the end.
Then I renamed it in https://github.com/moneyadviceservice/frontend/pull/1035, but only tested it with the feature enabled in my local repo. Maybe in tests all features could be disabled by default, any thoughts?
@paulanthonywilson @munckymagik
> Fix wrong feature flag in RetirementsController spec.

- lib/core/repository/cms/cms.rb
- spec/lib/core/repository/shared_examples/cms_resource.rb
on a 404 it will now return nil which is what the public wesbite fallback
repository used to do
> Remove public website cms fallbacks

- app/controllers/action_plans_engine_controller.rb
- config/routes.rb
- lib/engine_mount_point.rb
- lib/engine_mount_point/action_plans.rb
- lib/tool_mount_point.rb
- lib/tool_mount_point/action_plans.rb
- spec/requests/tool_integration/action_plans_spec.rb
* #6278 in Target process.
* Rename the existing URL https://www.moneyadviceservice.org.uk/en/action-plans/redundancy
to https://www.moneyadviceservice.org.uk/en/tools/redundancy-pay-calculator
> Rename redundancy action plan to redundancy tool

- app/assets/stylesheets/layout/_variables.scss
- app/assets/stylesheets/layout/common/_global.scss
- app/assets/stylesheets/layout/page_specific/_article_page.scss
- Added breakpoint of 800px where 3 cols come in
- at 720px $mq-m two columns appear on tablet for article pages
> TP-6352: Update breakpoint on category/article page

- app/controllers/debt_test_controller.rb
* setting the parent layout in this way breaks setting the syndicated
* layout when it is need.
* As far as I know, setting the layout makes no difference to the layout
> remove definition of debt-test parent template

- app/assets/javascripts/components/StickyColumn.js
- spec/javascripts/tests/StickyColumn_spec.js
- Sometimes when back to top is clicked, the browser gets
confused, thinking that the sticky component is at the bottom.
- Added check to ensure that it returns to it's natural static
position when back to top is pressed
> TP-6352: Sticky column - back to top edge case bug

- app/controllers/retirements_controller.rb
- config/features.yml.sample
- config/routes.rb
- spec/controllers/retirements_controller_spec.rb
It's going live, and it shouldn't need to be conditionally enabled or disabled.
> Remove welsh retirement landing pages feature flag

- app/assets/javascripts/syndication/tools.js.coffee
- app/controllers/debt_test_controller.rb
- app/controllers/embedded_tools_controller.rb
- app/views/layouts/engine_syndicated.html.erb
Some tools do not have any benefit from having the iframe resizer when being syndicated. For the debt test tool, it was causing problems with the scrolling. This enables tools to disable the iframe resizer if they need.
> Conditional loading of syndicated tool iframe resizer 

- .env
- .env.test
- README.md
this is so developers who want to fire up frontend will have access to
dummy data. reducing overhead in setup. developers can choose to set
this back to their local version if needed
> in .env point to QA cms

- app/controllers/corporate_controller.rb
- app/models/corporate_partner.rb
- config/application.rb
- config/routes.rb
- features/corporate_partners_export.feature
- features/step_definitions/corporate_partners_export_steps.rb
- features/support/env.rb
- spec/models/corporate_partner_spec.rb
* Allows the partnerships team to export a list of all corporate partners who've registered for an embed code at `/en/corporate/syndication` in CSV format.
* CSV export available via url at `/en/corporate/export-partners`
> Corporate partners export

- app/views/styleguide/css_overview.html.erb
We favour `js-` prefixes for Javascript selectors, whereas the styleguide was suggesting id's as well.
> Better wording for CSS styleguide

- app/assets/stylesheets/components/page_specific/_home_top.scss
- app/assets/stylesheets/helpers/_layout.scss
@Tr4pSt3R spotted a bug where home page BG promo was not displaying correctly on his 27 incher.
Auto margins will not centre an absolutely positioned element.
> Align background image correctly for XL screen sizes (>1200px)

- app/controllers/technical_feedback_controller.rb
- spec/controllers/technical_feedback_controller_spec.rb
After technical feedback is received the user is returned back to the
referring page. This could cause 500 errors if the url was entered
directly.
This fix redirects the user to the root page if there is no referrer.
> Redirect to root after feedback if no referrer url

- config/environments/production.rb
This is so the caching of the categories is reduced to every hour instead of once a day. 
I'm not aware of much else that uses caching.
> decrease Rails cache expiry to 1 hour

- app/assets/javascripts/components/ClearInput.js
- app/assets/javascripts/components/EmbedCodeGenerator.js
- app/assets/javascripts/components/InputFilters.js
- app/assets/javascripts/components/Newsletter.js
- app/assets/javascripts/components/StickyColumn.js
ClearInput, Newsletter, StickyColumn etc etc don't have a componentName set in the JS.
This is causing DoughBaseComponent to spit out a console warning.
This task is to add names to each JS module so this warning goes away.
> TP-6432: Add componentName to existing dough components in frontend

- Gemfile.lock
This updates dough-ruby to latest version which includes this PR:
https://github.com/moneyadviceservice/dough/pull/233
> TP-6435: update dough_ruby for frontend

- app/controllers/corporate_controller.rb
- app/models/corporate_partner.rb
- features/corporate_tool_page.feature
- features/step_definitions/corporate_tool_page_steps.rb
- spec/controllers/corporate_controller_spec.rb
- spec/models/corporate_partner_spec.rb
Allows partners to re-request for another embed code using an existing email address.
> Partners embed code submission

- app/controllers/campaigns_controller.rb
- app/controllers/concerns/suppress_menu_button.rb
- app/controllers/debt_management_controller.rb
- app/controllers/embedded_tools_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/home_controller.rb
- app/controllers/landing_pages_controller.rb
- app/controllers/mount_controller.rb
- app/controllers/profile_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/retirements_controller.rb
- app/controllers/sessions_controller.rb
- Added method to three controllers to remove the menu button
as there is no menu markup output on these sections of pages
- This was causing a "t.find is not a function" JS error appearing no these pages.
> TP-6444: Remove menu button from profile and registration pages

- features/profile_saved_tools.feature
- features/step_definitions/profile_steps.rb
- removed health check feature as health check is no
longer regarded as a 'saved' tool
- updated feature spec and steps to reflect recent
changes
> TP-6343 - update feature to ensure it passes

- app/assets/stylesheets/components/page_specific/_category_detail.scss
The button was missing a hover state, which highlighted the fact there were two hit areas. This fixes this, and adds the hover states.
The diff looks more serious than the change actually was, its really just a few styles moving around.
> Styling button element for Dough collapsible

- app/assets/stylesheets/components/page_specific/_category_link_list.scss
- app/views/categories/_top_links.html.erb
Naming clash that was spilling to pages using link_list from common. Mainly the pensions and retirement landing page.
Also adds `@extend .unstyled-list` as this was because inherited from the 'common' component, and now we've separated them it needs to be declared here, too.
> Renaming page_specific link_list -> category_link_list

- app/assets/stylesheets/layout/page_specific/_retirements.scss
- ensure buttons with quite long content don't cause horizontal
scrolling issues
> TP-6462: Override wrapping style on buttons for retirement page

- app/assets/stylesheets/layout/common/_context_bar.scss
viewports less than 720px view port
It was felt that the breadcrumb was taking up too much screen real-estate on mobiles, and also google had an issue in their 'mobile optimised' report that the touch targets were too small on the crumb.
- ensures it only surpresses the breadcrumb visually and is still
accessible for screen readers
> id:6458 comment: Suppress breadcrumb for mobiles devices

- bin/mas-version-diff
* This will be used to everybody (frontend/backend) devs when pointing the
frontend version on the scripts repo
Run like:
```
./bin/mas-version-diff 1865 1870
```
The result:
```
8838a16 (tag: 1870)\ Merge pull request #1137 from moneyadviceservice/fix-tool-name-routing-error\ [Jones Agyemang]
871f490\ redirects incorrect tool url to 404 page\ [Jones Agyemang]
129fac3 (tag: 1869)\ Merge pull request #1135 from moneyadviceservice/remove-registration-edit-feature\ [Jones Agyemang]
ad906fc\ remove unnecessary registration edit feature\ [Jones Agyemang]
b90b62d\ Merge pull request #1134 from moneyadviceservice/remove-404-page-feature\ [Tomas D'Stefano]
c3a84b8\ remove 404 page feature\ [Jones Agyemang]
1b86283\ Merge pull request #1128 from moneyadviceservice/error-page-routing\ [Jones …
```
> Add a simple mas diff version script for everyone that bump version on the scripts repo

- app/assets/stylesheets/components/page_specific/_category_detail.scss
- app/assets/stylesheets/components/page_specific/_category_link_list.scss
- app/views/categories/_child_categories.html.erb
- config/locales/cy.yml
- config/locales/en.yml
This PR includes some accessibility enhancements for the category pages, based upon DAC recommendation which can be seen below.
--
DAC Response - I would say that adding the function to the heading is a really good idea. However, a keyboard only user may become disorientated by the ‘+’ not receiving any visible link focus on tab. To me, the focus being only on the ‘Running a bank account’ and not on the ‘+’ sign (see screen shot) suggests that I will not be viewing more content. I would definitely underline the ‘+’ sign and possibly make it green so that they look related and one link.
Also, a ‘view more’ link usually directs users to another page/window. The ‘+’ sign is the standard icon for expandable content.
> Accessibility updates suggested by DAC

- app/assets/stylesheets/layout/page_specific/_registration.scss
- welsh language version of button too wide so allowed text to wrap only in this instance.
- updates previous fix for this issue which applied to button--primary, which is now replaced by button--newsletter
> id:6499 comment:fix for button on small viewport

- app/assets/stylesheets/components/common/_lists.scss
Requirement is to keep font size of lists the same as the rest of the table
> Give lists in tables uniform font size

- app/assets/stylesheets/components/dough_theme/button/_button.scss
- app/views/devise/registrations/new.html.erb
which is green in colour
- reverted signup button to button--primary
> id: 6501 comment: Simplified newsletter button to just one version

- config/locales/cy.yml
- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
Content lives here:
https://www.moneyadviceservice.org.uk/en/campaigns/debt-management/companies
Slipped in another small Welsh translation for category pages.
> Update content on debt management company list

- config/locales/cy.yml
- updated YAML file to Welsh language URL
> id: 6558, comment: Debt advice locator tool link broken in Welsh version

- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
- company name removed from lists in en and cy yml files, used by both pages
> id: 6636, comment: Remove Back2credit from debt management pages

- app/controllers/catchall_controller.rb
- spec/cassettes/core/repository/cms/cms_api/find/idonotexist_nested.yml
- spec/requests/404_spec.rb
the cms api throws an error when it doesn't recognize certain urls
for now we handle this to return a 404
the better fix is to make the cms not have this constraint
and return a 404 when the resoure cannot be located
however this needs further looking into in case there are compatability
issues
> fix 404 catchall when cms content not found

- config/database.yml
- spec/spec_helper.rb
the time is roughly the same on my local box although I've only done a few runs. however in theory it should be quicker as there is no disk io overhead and assuming the test box has enough memory.
> [DEV APPROVED]use in-memory sqlite database in test mode

- app/controllers/static_pages_controller.rb
- config/routes.rb
- features/step_definitions/breadcrumbs_steps.rb
- features/step_definitions/static_page_steps.rb
- features/support/world/static_pages.rb
- spec/controllers/static_pages_controller_spec.rb
- this removes code that is no longer used as we only have 2 static pages. these are `contact-us` and the welsh equivalent
- this also solves the problem of static redirects handled by the cms. as these routes will no longer be routed by the application the catchall route and controller will take care of these redirects.
> limit static pages to contact us

- config/routes.rb
this route is pointless because it will eventually be caught by a bigger net anyway. 
```
if Feature.active?(:redirects)
match '*path', via: :all, to: 'catchall#not_implemented'
else
match '*path', via: :all, to: not_implemented
end
```
> remove pointless route

- app/controllers/catchall_controller.rb
- spec/cassettes/en/core/cms/cms_api/find/redirected.yml
- spec/requests/not_implemented_spec.rb
for example this will allow urls with the extension .pdf
to be redirected
> catchall controller passes format to cms

- app/views/layouts/_base.html.erb
An agency for Optimizely are running a training session on Friday and need an empty page on production to demonstrate some tests with. We have decided to use the https://www.moneyadviceservice.org.uk/en/empty template for this as it is only used by third parties in a non-automated fashion.
This code simply drops in the embed code to those pages using the `hide_elements_irrelevant_for_third_parties` flag, which is only set to true on the `empty` controller.
> Adding optimizely embed code to empty page

- app/views/devise/registrations/new.html.erb
- db/migrate/20150928135300_change_default_value_for_opt_in_for_research.rb
- db/schema.rb
- features/registration.feature
- features/step_definitions/registration_steps.rb
- spec/models/user_spec.rb
Fixes the issue we experienced and the horrors of setting defaults at the
database level. This fix maintains the opt-in for market research field being
set to true automatically. This assertion is on the form only. It's done neither
through callbacks nor database defaults.
> Fix opt in db migration

- Gemfile.lock
Updating versions for the following (engine pipelines triggered and passed):
RIO - Removing BETA
https://github.com/moneyadviceservice/rio/pull/78
savings_calculator - Remove feedback link for partners
https://github.com/moneyadviceservice/savings_calculator/pull/22
timelines - Add meta descriptions & separate canonical for tool
https://github.com/moneyadviceservice/timelines/pull/61
Not 100% sure why autoprefixer-rails (updates on bundle update savings_calculator) and pensions_calculator-calculations (updates on bundle update rio) are updating also? I will roll these back before merge if necessary? @benbarnett
> [DEV APPROVED]Updating engine versions for multiple tasks

- README.md
Off the back of the changes to `frontend-code-standards` yesterday.
> Adds reference links to frontend readme

- app/views/layouts/_base.html.erb
When at the top, the whole top half of every page of the site was failing to render in IE8
> Moving SVG sprite to bottom of page

- app/views/layouts/_base.html.erb
Move the SVG sprites to underneath the top BODY tag but wrapped IE conditionals so it always renders unless IE < 9.
> Fix for SVG icons not rendering in Safari

- build.sh
- test.sh
Newer versions of bundler create .bundle/config which is taking priority
over env var settings, BUNDLE_WITHOUT in particular. This breaks builds
when test.sh bundles without the "test" group and that state gets
saved. The fix, until Bundle 2 is released, is to rm the config file:
https://github.com/bundler/bundler/issues/3288
> Fix builds with newer Bundler.

- build.sh
So that we get RPM versions with the environment name built-in.
This shouldn't change anything for our normal Go pipelines as they all just use the value of `$GO_PIPELINE_COUNT`for `$GO_PIPELINE_LABEL` by default anyway. The `dev_test` and Azure build pipelines append something to the counter for those pipelines will generate RPMs with different names. This is desireable in Azure where we want more control over what RPMs we try to install (we only want the Azure-build ones), and probably makes sense for the `dev_test` ones too.
> Build RPMs using the Go pipeline label.

- spec/requests/tool_integration/annuities_spec.rb
* The spec was broken only when the feature flag was turn off.
Fixing the matcher to catch the not found exception solves the problem
> Fix annuities request spec

- app/decorators/campaign_page/campaign_decorator.rb
- unfortunately no test, as I can't figure it out. the named route seems to be missing even with the feature toggle enabled
- also i have no idea why specific campaign knowledge has filtered through to this generic decorator
> fix link to car cost tool in campaign page

- spec/requests/tool_integration/annuities_spec.rb
* The spec was renamed to requests so the route to does not exist
here. Changing the matcher will fix the spec.
* This only spec can be runned with anuites feature flag turn on
> Change the matcher verification for annuites spec

- app/assets/stylesheets/components/common/_contact_panel.scss
- app/assets/stylesheets/layout/common/_contact_panels.scss
- app/views/shared/_contact_panels.html.erb
Using CSS pseudo-elements rather than <div>s to show the borders on the three-column footer on the homepage.
> id: 6797 homepage columns border browser zoom bug

- app/assets/stylesheets/components/common/_contact_panel.scss
- app/assets/stylesheets/components/common/_icon.scss
- app/assets/stylesheets/components/common/_icon_2x.scss
- app/views/shared/_newsletter_signup.html.erb
Use the partial instead to support SVG and fallback...
`<%= render 'shared/svg/use_icon',
icon: 'email',
svg_fallback_support: true
%>
`
There is no double-density sprite at the moment so I had to force single sized on double density screens using background-size: auto.
> [DEV APPROVED] 6779 fix newsletter icon

- features/display_newsletter_form.feature
- package.json
The ‘Display sticky newsletter’ feature passes locally but is failing on the build server, reason being a JavaScript error linked to PhantomJs. After trying to specify an exact version of PhantomJs we are still not able to resolve the error.
Removing this test as per discussion with @rnalexander
> Removing flickering cucumber test

- app/views/shared/_feedback.html.erb
- config/features.yml.sample
- features/feedback.feature
This UI panel has recently resurfaced due to removing the feature flags. We’re putting it behind a feature flag to keep it hidden until we get a decision on whether it’s needed anymore or not.
> Feedback Panel Feature Flag

- app/assets/stylesheets/components/page_specific/_home_top.scss
Hiding hero image fir IE8 users, until the homepage / CMS editing work
goes live
Current:
Fix:
> [DEV APPROVED] Ie8 Hero image fix

- app/assets/stylesheets/components/page_specific/_home_top.scss
IE8 hero image can be put back in now that the CMS homepage editing has
gone live, the removed CSS hid the image and increased the width of the main title
> [DEV APPROVED] Adding ie8 hero image

- app/assets/javascripts/modules/google_complete.js
User testing has shown that showing the search hints within the input field (typeahead) is confusing. This commit removes the hints from the field but keeps the rest of the AJAX search functionality.
**Live site:**
**Proposed change:** (ignore the error page!)
> [DEV APPROVED] 6877 - removing search hinting from input

- app/views/shared/_contact_panels.html.erb
- app/views/static_pages/contact_us.html.erb
- app/views/static_pages/cysylltu_a_ni.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Reverting Christmas opening hours to originals:
English contact panel:
English contact page:
Welsh contact panel:
Welsh contact page:
> [DEV APPROVED] #6875 Revert Xmas opening times

- app/helpers/sticky_newsletter_visibility.rb
Sticky newsletter will not show in following articles,
1.https://www.moneyadviceservice.org.uk/en/articles/if-you-have-had-a-late-miscarriage
2.https://www.moneyadviceservice.org.uk/en/articles/if-your-baby-has-died-shortly-after-birth
> [DEV APPROVED] #6916 - Remove sticky newsletter from some articles

- app/assets/stylesheets/_enhanced.scss
- app/assets/stylesheets/components/common/_mas_button.scss
- app/assets/stylesheets/components/common/_news_signup_sticky.scss
- app/assets/stylesheets/components/common/_newsletter_signup.scss
- app/assets/stylesheets/components/dough_theme/button/_button.scss
- app/views/shared/_news_signup_sticky.html.erb
- app/views/shared/_newsletter_signup.html.erb
This ticket highlighted other issues with the newsletter buttons, all have been addressed in this PR:
Moved Dough Theme import Components above Local Components to stop overwrites.
Added mas-button and removed non-generic modifiers.
Moved the specific modifiers to parent Block SCSS files.
Removed third-party class.
Removed unused newsletter button css properties.
Before:
After:
> [DEV APPROVED] #6786 - Newsletter button style fix for tools

- features/support/ui/sections/sticky_newsletter.rb
A fix for the currently failing cucumber test for the sticky newsletter, I changed a classname on the sticky button element but not in features/support/ui/sections/sticky_newsletter.rb
> Sticky newsletter button cucumber fix

- app/helpers/sticky_newsletter_visibility.rb
- spec/helpers/sticky_newsletter_visibility_spec.rb
Background
The plan is to migrate the Blog to the MAS domain, www.moneyadviceservice.org.uk/blog in early January 2016. We do not want the MAS sticky footer to appear on any of the Blog pages
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1351)
> [DEV APPROVED] removes sticky footer from all blog pages

- vendor/assets/javascripts/webchat.js
One of the outcomes of the recent problems with WebChat was that this value is hard-coded in the front-end when we actually have pre-environment values set in Puppet. This change allows us to use the values in Puppet.
Tested in preview.
> Set the domain for webchat using a value in Puppet

- app/assets/javascripts/components/NewsletterSticky.js
- app/views/shared/_news_signup_sticky.html.erb
- spec/javascripts/fixtures/NewsletterSticky.html
- spec/javascripts/tests/NewsletterSticky_spec.js
Addressing the following accessibility recommendations (see TP ticket for details) 
* Adding aria roles for dialog and labelledby
* Setting keyboard focus when it loads
* Creating a closed tab loop for the fields within it
* Returning keyboard focus to the page when it is closed
> [DEV APPROVED] #6793 Accessibility updates to the sticky footer

- Gemfile.lock
Bumping debt advice locator tool
Relates to PR's:
1) #6918 Contact number adjustments:
https://github.com/moneyadviceservice/debt-advice-locator/pull/105
2)#6918 Changing phone number colour
https://github.com/moneyadviceservice/debt-advice-locator/pull/107
> Bump debt advice locator version to 2.0.4.97

- app/assets/stylesheets/components/common/_mas_logo.scss
- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/assets/stylesheets/layout/common/_header.scss
- app/helpers/application_helper.rb
- app/views/shared/_header.html.erb
- spec/helpers/application_helper_spec.rb
-  Adds CSS to fix position of header on smaller screen sizes
- restyles header globally to make it less deep
- updates main content position in line with changes to header depth
- Add non-sticky class when on a tool page (with the exception of payday loans tool, which has own layout)
- Adds styles to remove sticky header from selected pages
Integrates with PR239 on mortgage_calculator
> [DEV APPROVED] id: 6920, comment: Adds sticky header to mobile site with some exceptions

- Gemfile.lock
Relates to PR: https://github.com/moneyadviceservice/mortgage_calculator/pull/239 - Updates sticky element for better mobile experience
Also includes: https://github.com/moneyadviceservice/mortgage_calculator/pull/240 - #6925 Mortgage calculator mobile improvements
> [DEV APPROVED] #6920 - Bumping Mortgage Calculator 1.3.8.631

- Gemfile.lock
Relates to PR: https://github.com/moneyadviceservice/advice_plans/pull/149 - #6955 Money Health Check mobile visual bug
> [DEV APPROVED] #6955 - Bump Advice Plans to 3.1.1.364

- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
Enables a link to the income drawdown page that was commented out. (also updates link to correct location).
> enable link to income drawdown. update link.

- app/assets/stylesheets/components/common/_search.scss
- app/assets/stylesheets/layout/common/_header.scss
The overflow-y property was changed on the .l-header__content element in #6920 (Implement Sticky header on Mobile) to fix mobile scrolling problems. This hides the .tt-dropdown-menu element because it is positioned absolutely. We can overcome this by changing its position to static on mobile (!important is reluctantly used to overwrite dynamically set properties in this instance).
> id: 7002, comment: Fixes typeahead bug where the suggested text is hidden

- app/controllers/application_controller.rb
- app/helpers/chat_migration_message.rb
- app/views/shared/_contact_panels.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/chat_migration_message.feature
- features/step_definitions/chat_migration_message.rb
- spec/helpers/chat_mirgation_message_spec.rb
Adding a timed script to display chat unavailable message for Saturday 6th February 2016
| 2nd February 2016 | 6th February 2016 | 10th February 2016 |
|---------------------------|--------------------------|----------------------------|
|<img width="304" alt="before and after" src="https://cloud.githubusercontent.com/assets/13165846/12780889/b1c63ace-ca68-11e5-8643-4298b53ca82d.png">|<img width="329" alt="screen shot 2016-02-03 at 11 25 35" src="https://cloud.githubusercontent.com/assets/13165846/12780923/e823ea9e-ca68-11e5-861a-bc84e9ea0df1.png">|<img width="304" alt="before and after" src="https://cloud.githubusercontent.com/assets/13165846/12780896/b750b564-ca68-11e5-8c61-c43efe40f96a.png">|
| 2nd February 2016 | 6th February 2016 | 10th February 2016 | …
> [DEV APPROVED] #6963 - Display Web Chat offline message

- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
Adding a new link at position 3 of the retirement income choices to the
income drawdown page, and moving the flexi-access link to position 7 for both English and Welsh
> [DEV APPROVED] #7011 - Pensions and Retirements link update

- app/controllers/debt_management_controller.rb
- app/views/debt_management/companies.html.erb
- app/views/debt_management/show.html.erb
- features/cassettes/cy/core/repository/articles/cms/find/non-fca-debt-management-companies.yml
- features/cassettes/en/core/repository/articles/cms/find/non-fca-debt-management-companies.yml
- features/debt_management.feature
- features/step_definitions/debt_management_steps.rb
- features/support/ui/pages/debt_management.rb
- features/support/ui/pages/debt_management_companies.rb
- features/support/world/pages.rb
Replaces the static list of companies found at https://www.moneyadviceservice.org.uk/en/campaigns/debt-management and https://www.moneyadviceservice.org.uk/en/campaigns/debt-management/companies with the contents of an article from the CMS.
This is reliant on this article being created in the CMS before going live with the id ``non-fca-debt-management-companies`` (same for both locales).
> Pull in debt management campaign company list from a CMS based article

- app/assets/stylesheets/layout/page_specific/_article_page.scss
The problem is that since the introduction of the Sticky Header on mobile devices elements that scroll to the top of the viewport when selected from internal menus are partially hidden by the header: 
This fix adds ensures there is some space above the relevant headings:
> id: 7010, comment: Adjusts position of headings when linked from internal menu

- app/assets/stylesheets/components/page_specific/_home_top.scss
Removing hero image for IE8 users, this will allow us to use double density images, improving visual appearance of the hero image.
IE8 screenshot:
This change hides the hero image container and makes the main intro text wider to fill the empty space a little more
> [DEV APPROVED] #7013 - Remove Hero image for IE8 users

- Gemfile.lock
Updated mortgage calculator version includes:
https://github.com/moneyadviceservice/mortgage_calculator/pull/244
https://github.com/moneyadviceservice/mortgage_calculator/pull/243
> [DEV APPROVED] Bump mortgage calculator to 1.3.8.635

- app/assets/stylesheets/components/common/_global-alert.scss
- app/assets/stylesheets/layout/common/_header.scss
Problem is that the global alert pushes the position of the header down:
====
When scrolled the header (now in fixed position) remains in this position: 
====
The agreed solution is to switch the positions of the header and global alert in mobile view when the global alert is displayed: 
====
This displays as desired when the view is scrolled:
> [DEV APPROVED] id: 7021, comment: Switches relative positions of header and global alert on mobile views when alert is displayed

- Gemfile.lock
There were a couple of small changes in RIO to update the title and canonical links for the income drawdown page. This PR bumps the engine to the latest version which includes these changes.
> update rio to latest version

- Gemfile.lock
Bumping budget planner, new version includes task the following PR:
6972 month and year bug
https://github.com/moneyadviceservice/budget_planner/pull/398
> [DEV APPROVED] Bumping budget planner to 4.0.3.728

- Gemfile.lock
Bumping budget planner to 4.0.3.729
Relates to PR https://github.com/moneyadviceservice/budget_planner/pull/399
> Bumping budget planner 4.0.3.729

- features/step_definitions/newsletter_signup_steps.rb
Newsletter signup feature requires the homepae being read from the cms
to be stubbed, and now requires the footer to be stubbed too.
> Fix the cucumber specs for footer from cms.

- Gemfile.lock
This PR https://github.com/moneyadviceservice/rio/pull/85
Waiting for Jackie to approve on preview. But in anticipation, looking for DEV_APPROVED status.
> Update rio for extra link to Income Drawdown

- app/controllers/embedded_tools_controller.rb
This change removes the skip to navigation link from tools pages as they do not contain a main navigation
> [DEV APPROVED] #7033 - Remove Skip to main nav for tools

- features/cassettes/cy/core/repository/footer/cms/find/footer.yml
- features/cassettes/en/core/repository/footer/cms/find/footer.yml
- features/support/env.rb
Cucumbers were failing as the footer is always retrieved from the CMS; previously there was a feature flag inactive for tests (apparently).
Uses VCR to fake out the requests to the CMS, as per Standard Operating Procedure for these front-end cucumbers.
> Cucumber VCR cassettes for the footer from cms

- Gemfile.lock
Bumping mortgage calculator for related ticket A11Y - repayments not
read by screen reader
Related PR: https://github.com/moneyadviceservice/mortgage_calculator/pull/245
> Bumping mortgage calculator to 1.3.8.640

- app/helpers/sticky_newsletter_visibility.rb
- lib/newsletter_exclusions.rb
Excluding the in article and sticky footer from the following articles:
* a-new-start-without-debt
* feel-better-without-debt
* no-more-debt-stress
* get-debt-under-control
* no-more-debt
These have not been published yet, I’ve been reassured that these
article names won’t change
> [DEV APPROVED] #7163 - Excluding newsletter signup from articles

- Gemfile.lock
Latest version includes updates:
- Bug - Remove autocomplete values PR: https://github.com/moneyadviceservice/action_plans/pull/126
- 7174 time distance bug fixes PR: https://github.com/moneyadviceservice/action_plans/pull/128
- Updating ruby version PR: https://github.com/moneyadviceservice/action_plans/pull/129
- 7162 Updating Jobseekers allowance PR: https://github.com/moneyadviceservice/action_plans/pull/124
- id: 6749, comment: Work and redundancy calculator - corrects wrong welsh translation PR: https://github.com/moneyadviceservice/action_plans/pull/123
> [DEV APPROVED] Bumping Action Plans to 316az

- Gemfile.lock
New pensions calculator includes PR: https://github.com/moneyadviceservice/pensions_calculator/pull/180
> [DEV APPROVED] 7124 - Bumping pensions calc to 538

- Gemfile.lock
New payday loans intervention versions contains work relating to PR https://github.com/moneyadviceservice/payday_loans_intervention/pull/49
7023 - Removing date references
> [DEV APPROVED] #7023 - Bumping payday loans to 251

- app/assets/stylesheets/layout/page_specific/_debt_management.scss
- also makes the "Consumer Credit Register" link open in a new tab and adds the relevant icon
This is slightly amended from PR1422: the external link stuff has been made more specific by nesting it inside .l-debtmanagement__companies-list
> id: 7216, comment: Updates copy on Debt Management page

- app/controllers/application_controller.rb
- app/controllers/articles_controller.rb
- app/controllers/categories_controller.rb
- app/views/articles/show.html.erb
- app/views/categories/show.html.erb
- app/views/layouts/_constrained.html.erb
- app/views/layouts/_unconstrained.html.erb
- features/skip_to_main_link.feature
- features/step_definitions/skip_to_main_link_steps.rb
Skip to main link on categories and articles pages are being adjusted to that they jump to the main content.  This change will remove the main id from the entire content and place it on the actual main content of both the article and category pages.
The tests check if the container <main> in both article and category pages contain the attribute ``id="main"`` as this is what the accessibility link contains as the anchor ``<a href="#main">``
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1421)
> [DEV APPROVED] 7034 - Skip to main link update

- app/assets/stylesheets/components/page_specific/_category_detail.scss
- Looks like the class-names of the icons were extended to include the colour but this wasn't reflected in the CSS.
- This PR updates the CSS to add this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1427)
> [DEV APPROVED]id: 7009, comment: Fixes bug on Expand/Contract icons

- Gemfile.lock
This will update the versions of `pensions_calculator` and `pensions_calculator-calculations` for the 06/04/2016 update, as per card 7042.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1428)
> [DO NOT MERGE] Update pensions_calculator and calculations gems

- bin/mas-version-diff
A couple tweaks here:
- Turn the SHA into a link, so they used to look like:
> 114198f\ Bumping frontend version for prod\ [slaywell]
And now:
> moneyadviceservice/scripts@114198f Bumping frontend version for prod [slaywell]
- Enable prettier colours for refs
- Remove backslashes
- Remove pager, there will be pretty short bits
- Add help text when insufficient args
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1408)
> [DEV APPROVED]Make SHA refs links in version diff

- Gemfile
- Gemfile.lock
Stop updating rio from git master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1432)
> Lock rio gem to version 0.0.3 instead of master

- Gemfile
- Gemfile.lock
moneyadviceservice/rio@0612511 Bump version 1.1.0 -> 1.2.0 [Jones Agyemang]
moneyadviceservice/rio@0ffbb0f Update for 2016/2017 budget. [Jones Agyemang]
moneyadviceservice/rio@7951e86 Bump version 1.0.0 -> 1.1.0 [Jones Agyemang]
moneyadviceservice/rio@013c160 Fix indentation in Welsh income drawdown [Jones Agyemang]
moneyadviceservice/rio@c558191 Fix basic rate and other copy change in drawdown [Jones Agyemang]
moneyadviceservice/rio@80a648e Update income drawdown for 2016 [Jones Agyemang]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1441)
> Bump rio 1.0.0 -> 1.2.0

- app/controllers/registrations_controller.rb
- features/registration.feature
- features/step_definitions/registration_steps.rb
As a site user coming to the Money Advice Service
I would like to be signed up for the newsletter when I explicitly choose to do so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1436)
> [DEV APPROVED]Registration newsletter signup opt-in should be unchecked by default

- Gemfile
- Gemfile.lock
Complements PR93 in rio (https://github.com/moneyadviceservice/rio/pull/93) which changes/adds copy to the tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1452)
> [DEV APPROVED] TP: 7310, Comment: Bumps version number for rio (to 1.3.0)

- Gemfile.lock
Releasing the cumulative changes of three PRs:
Separate task that looks like it just hasn't been released yet: [Fix date issue for distance in words dateHelper](https://github.com/moneyadviceservice/action_plans/pull/130)
- moneyadviceservice/action_plans@f725ea7 Merge pull request #130 from moneyadviceservice/7234_fix_date_issue [Jones Agyemang]
- moneyadviceservice/action_plans@d0065e1 bump action_plans gem version [Jones Agyemang]
- moneyadviceservice/action_plans@d2c4792 Fix date issue for distance in words dateHelper [Jones Agyemang]
The main piece of work that needs to be released: [7045 - Financial year 2016 update](https://github.com/moneyadviceservice/action_plans/pull/131)
- moneyadviceservice/action_plans@61f6bb9 Merge pull request #131 from …
> Bump action_plans from 4.0.5.316 to 4.0.8.323

- app/controllers/registrations_controller.rb
- app/views/devise/registrations/new.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/registration.feature
- features/step_definitions/registration_steps.rb
- features/support/ui/pages/sign_up.rb
- spec/lib/core/repository/users/default_spec.rb
As it says, remove the opt in on signup, also a bit of copy. 
Copy for the checkbox left in place as it's still in use on the settings page, due for removal in ticket 7331.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1465)
> Remove newsletter opt in from signup

- app/controllers/registrations_controller.rb
- app/views/devise/registrations/edit.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/settings.feature
- features/step_definitions/settings_steps.rb
- features/support/ui/pages/settings.rb
[Ticket 7331 - User Settings Page - Remove the newsletter opt in checkbox](https://moneyadviceservice.tpondemand.com/tp2/entity/7331)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1466)
> 7331 - Remove the newsletter opt-in from the user settings page

- app/views/shared/_footer_primary.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Requirements:
- Facebook 72k likes
- Twitter 42k followers
- YouTube 5.5m views
| English |
|-----------|
|<img width="574" alt="screen shot 2016-06-14 at 08 39 18" src="https://cloud.githubusercontent.com/assets/13165846/16034897/299463b8-320c-11e6-8baf-4f592634407b.png">|
| Welsh |
|----------|
|<img width="583" alt="screen shot 2016-06-14 at 08 39 08" src="https://cloud.githubusercontent.com/assets/13165846/16034910/34799fdc-320c-11e6-97e3-1439dc5f8366.png">|
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1469)
> [DEV APPROVED] 7319 - Update social followers, adding Welsh

- app/views/debt_management/show.html.erb
- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
Due to some confusion on this task, this was left out of the last PR.
This text has been moved into the CMS page so that it is also shown on the standalone page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1476)
> 7422 - Remove the companies intro text on debt management page

- config/locales/cy.yml
- config/locales/en.yml
Updates the CTA on the registration page in English and Welsh. 
Current: 
Update: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1475)
> [DEV APPROVED] TP: 7417, Comment: Updates text on Registration page CTA

- app/views/shared/_footer_primary.html.erb
This ticket adds title attributes to the footer social SVG's.  This will also need to apply to other projects - Blog, RIO and any other that does not use the frontend footer
Please note: There is a related ticket in dough to apply the same changes to the social sharing icons:
https://github.com/moneyadviceservice/dough/pull/272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1486)
> [DEV APPROVED] 7444 - SVG title attributes

- app/views/retirements/pension_savings/_five_years_out_section.html.erb
- app/views/retirements/pension_savings/_managing_money_in_retirement_section.html.erb
- app/views/retirements/pension_savings/_moving_into_retirement_section.html.erb
- app/views/retirements/pension_savings/_starting_out_section.html.erb
- app/views/retirements/pension_savings/_ten_years_out_section.html.erb
- app/views/retirements/pension_savings/_throughout_working_life_section.html.erb
- config/locales/landing_pages/pension_savings_timeline.cy.yml
- config/locales/landing_pages/pension_savings_timeline.en.yml
The DAC report highlights that images on the following page contain descriptive alt attributes:
https://www.moneyadviceservice.org.uk/en/pensions-and-retirement/pension-savings-timeline
here https://www.moneyadviceservice.org.uk/en/pensions-and-retirement
However due to accessibility requirements it is necessary to have a null alt attribute.
The solution was to remove the alt attributes for the images from the yaml files (en|cy) and update the rails image_tag helper to use a null alt attribute like so:
```
<%= image_tag "retirement_concepts/in-retirement@2x.png", alt: '' %>
```
Which results in the output:
```
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend …
> [DEV APPROVED] - 7440 - Null image ALT attributes

- app/views/layouts/_constrained.html.erb
- app/views/layouts/_unconstrained.html.erb
- app/views/technical_feedback/new.html.erb
This PR addresses two small items raised in the DAC Audit:
- Correctly labelling the form elements on the Feedback page (these had been incorrectly labelled) at some point).
- Altering code that generates empty ID attribute in some cases - empty ID attributes are invalid HTML
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1492)
> [DEV APPROVED] 7488 - Accessibility / valid markup fixes

- app/assets/stylesheets/layout/page_specific/_profile.scss
- app/views/devise/registrations/edit.html.erb
- app/views/profile/edit.html.erb
- config/locales/cy.yml
- config/locales/en.yml
1) On the signup page and account settings page, remove the ``<fieldset>`` element that wraps the research opt-in tickbox - it is no longer required as there is only one field within it. This should have no visual impact.
| Please see screenshot of markup below, element is no longer in a ``<fieldset>`` element |
|--------|
|<img width="954" alt="screen shot 2016-07-25 at 09 40 47" src="https://cloud.githubusercontent.com/assets/13165846/17095354/f3d2f356-524b-11e6-9bf9-481b65b3b331.png">|
2) On the profile page, add a <legend> element as the first child of the ``<fieldset>`` element, styled like a header.
| Please see screenshot and markup below |
|--------|
|<img width="941" alt="screen shot 2016-07-25 at 09 44 05" src="https://cloud.githubusercontent.com/assets/13165846/17096285/7de8c2d8 …
> [DEV APPROVED] 7479 - Adding valid html to signup and account management

- app/assets/stylesheets/components/page_specific/_home_top.scss
- app/assets/stylesheets/layout/page_specific/_homepage.scss
- app/views/shared/_home_top.html.erb
This ticket introduces changes which guarantee the hero image and text do not overlap.
Desktop:
Tablet / mobile Landscape:
Tablet portrait / mobile
Mobile / Small
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1491)
> [DEV APPROVED] 7474 - Home Page Image Optimisation

- Gemfile
- Gemfile.lock
This has been successfully deployed and tested on _Preview_(https://www.preview.dev.mas.local/en/tools/redundancy-pay-calculator). 
History of changes can be viewed here: 
https://github.com/moneyadviceservice/action_plans/pull/137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1499)
> [DEV APPROVED] bump action_plans to version 4.2.8

- Gemfile
- Gemfile.lock
For work done in tickets 7478 and 7481
https://github.com/moneyadviceservice/rio/pull/96
https://github.com/moneyadviceservice/rio/pull/97
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1501)
> Bumping RIO to 1.5.0

- app/views/layouts/_base.html.erb
This merges two tickets, 7432 and 7433 to add references in the <head> to all the required icons and manifest file for the site. The actual assets are dealt with in PR694 in scripts (https://github.com/moneyadviceservice/scripts/pull/694)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1504)
> [DEV APPROVED] 7432/3: Add favicons and manifest

- Gemfile
- Gemfile.lock
Bring in new version that supports Rails 4.2.x
https://github.com/moneyadviceservice/timelines/pull/66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1507)
> Update timelines gem

- app/controllers/campaigns_controller.rb
- app/controllers/landing_pages_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/retirements_controller.rb
- app/controllers/rio_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/sitemap_controller.rb
- app/views/corporate/show.html.erb
- app/views/corporate_categories/show.html.erb
- app/views/landing_pages/show.html.erb
There are certain pages which do or dont have the correct accessible links at the top of the page, to see these go to any page and hit tab, you will see the following links appear:
| Skip to main content | Skip to main navigation |
|:----------------------:|:------------------------:|
|<img width="215" alt="screen shot 2016-08-12 at 09 04 30" src="https://cloud.githubusercontent.com/assets/13165846/17616353/14732d0a-606c-11e6-89a4-38f20de35984.png">|<img width="276" alt="screen shot 2016-08-12 at 09 04 39" src="https://cloud.githubusercontent.com/assets/13165846/17616356/18f93234-606c-11e6-9408-089ff8787562.png">|
As part of this ticket, I have done a quick review of the pages/types of pages which require the skip to main content/navigation links:
| Page | Should have skip main content …
> [DEV APPROVED] 7495 - 2016 Audit - 'Skip to main' link on certain pages

- Gemfile.lock
This is a version bump of the payday loans intervention tool, the changes made in this tool can be found here:
https://github.com/moneyadviceservice/payday_loans_intervention/pull/50
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1510)
> [DEV APPROVED] - 7532 - Bumping the payday loans intervention tool to 1.4.7

- Gemfile.lock
This patch version includes the bug fix included in the below PR:
https://github.com/moneyadviceservice/action_plans/pull/141
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1511)
> [DEV APPROVED] 7522 - Bumping action plans to 4.2.10

- app/views/shared/svg/_icon_sprite.html.erb
This icon is useful and can be reused, so we are adding it to the main SVG partial that appears on every page on the site (the arrow-right is already in there).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1515)
> [DEV APPROVED]7568 - Adding svg-icon--arrow-left to SVG partial

- app/assets/javascripts/require_config.js.erb
- bower.json.erb
- config/initializers/assets.rb
- spec/javascripts/karma.conf.js
- spec/javascripts/test-main.js
- vendor/assets/javascripts/typeahead.jquery.js
This PR adds typeahead.jquery.js as a local asset (was previously loaded as a Bower component) and makes some changes (shown below) to it to prevent the current behaviour where the tab key has the same behaviour as the enter key (fires a search from a highlighted search suggestion). 
This was proving an accessibility issue: the tab key would be expected to move the user to the next link (in this case the clear button) rather than fire a search.
Also updates some associated files necessary for this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1513)
> [DEV APPROVED]TP: 7520, Comment: Updates typeahead functionality to exclude tab key

- app/views/content_hub/show.html.erb
- config/locales/content_hub/bank_accounts.en.yml
- config/locales/content_hub/cyfrif_banc.cy.yml
- config/routes.rb
Adds the Welsh version to the Content Hub page. The English version is on Production here: https://www.moneyadviceservice.org.uk/en/hub/bank-accounts and the YML for that is here: https://github.com/moneyadviceservice/frontend/blob/master/config/locales/content_hub/bank_accounts.en.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1521)
> TP: 7598, Comment: Adds Welsh YML file for Content Hub

- app/assets/stylesheets/components/common/_social_sharing.scss
Currently in production:
The fix is to remove the top padding from the icons, please see screenshots below:
| iPhone 5s | iPhone 6 Plus | Samsung Galaxy S6 |
|-----------|---------------|---------------------|
|<img width="310" alt="iphone 5s" src="https://cloud.githubusercontent.com/assets/13165846/18276574/5ec000aa-7443-11e6-9580-5aaba6053621.png">|<img width="451" alt="iphone 6 plus" src="https://cloud.githubusercontent.com/assets/13165846/18276579/6354c7fe-7443-11e6-8a62-0296879b32e8.png">|<img width="345" alt="galaxy s6" src="https://cloud.githubusercontent.com/assets/13165846/18276606/721f3616-7443-11e6-8f6c-58de342323a4.png">|
| EDGE WIN10 | IE11 WIN7 | IE9 WIN7 |
|--------------|-----------|----------|
|<img width="219" alt="edge win10" …
> [DEV APPROVED] 7586 Social share icons - articles

- app/views/retirements/index.html.erb
- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
**Description of issue**
```
The Pensions and Retirements landing page has subcategories lists, listing the top 5 articles in each, featuring a 'view all' link. 
DAC reports that this 'view all' link does not have enough context for screen-reader users to understand what this link relates to.
This can be easily solved by renaming the 'view all' link to 'view all in x' (where x is the name of the subcategory).
```
**Solution**
Adding the 'View all...' text to the YAML files for Welsh and English for each category.
| English |
|--------|
|![image](https://cloud.githubusercontent.com/assets/13165846/18269730/440a026e-7421-11e6-82cb-95c5a0a2bc1f.png)|
| Welsh |
|-------|
|![image](https://cloud.githubusercontent.com/assets/13165846/18269671/f5337332-7420-11e6-96d5-8f5d49f79846. …
> [DEV APPROVED] - 7563 - Properly label the 'view all' link on the Pensions & Retirement Landing page

- Gemfile
- Gemfile.lock
Increments the version number for the Savings Calculator.
Required by the following PRs:
- PR26 (https://github.com/moneyadviceservice/savings_calculator/pull/26)
- PR27 (https://github.com/moneyadviceservice/savings_calculator/pull/27)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1529)
> [DEV APPROVED] TP: 7603, Comment: Updates version number for Savings Calculator

- app/assets/javascripts/require_config.js.erb
- config/initializers/assets.rb
To include the new JavaScript file added in #1527 this also needs to be added to the asset pipeline config as well as the dependency in the requireJs file.
Quite frustrating that it works locally without doing this!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1531)
> [WIP] Adding informizely to Asset pipeline and requireJS

- app/assets/javascripts/modules/informizely_tag.js
The cookies that the Informizely tag code sets need to have 'path = /' otherwise duplicates are getting set across different pages on the site when the code is ran from different locations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1534)
> 7510 - Adding path=/ to the Informizely cookie code

- app/assets/javascripts/modules/informizely_tag.js
The string concatenation in the informizely_tag.js was inserting a duplicate semicolon, which was preventing a cookie being set in some browsers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1536)
> [DEV APPROVED] 7510 - Correcting a JS error in informizely_tag

- app/views/shared/_footer_secondary.html.erb
- config/locales/cy.yml
Description from ticket:
```
When I go to the Welsh version of the MAS webiste at https://www.moneyadviceservice.org.uk/cy
I want to be able to read the AccessIn 'Report an Accessibility Problem' link in the bottome left footer in Welsh
So I can use my own language
```
The translation was already present in the Welsh YAML, however the English text was hardcoded into the footer_secondary partial, this has now been fixed.
|--------|--------|
|<img width="269" alt="english" src="https://cloud.githubusercontent.com/assets/13165846/18630436/893ab138-7e64-11e6-8a13-a96053fcbd67.png">|<img width="248" alt="screen shot 2016-09-19 at 12 28 33" src="https://cloud.githubusercontent.com/assets/13165846/18630448/9fd4576e-7e64-11e6-9f44-69ee25c9b6dc.png">|
---
This change is [<img …
> [DEV APPROVED] 7619 - Adding translation for welsh

- app/assets/javascripts/components/StickyColumn.js
Issue is being reported by a customer, in which re-circulation drivers appear on top of main content (article pages), making it impossible to read the main content unless the page is expanded/ zoomed-in. The issue appears when user is scrolling down the page.
The problem seems to be at Samsung Galaxy Tab 2  10.1 , Samsung Note 10.1 (both running android 4)  as replicated through BrowserStack. (See Screenshots) 
After messing around with CSS positioning for a day I decided to use javascript and calculate the left offset of the parent container and then applying this value as the left: attribute of the sticky recirculation section.  This fixes the problem on the older Samsung Tablets and also provides slightly more stability across all browsers.
| Samsung Galaxy Tab 2 10.1 | Samsung Galaxy …
> [DEV APPROVED] 7610 - BUG: Fix Re-circulation drivers appearing over the main content (Galaxy Tab2)

- app/assets/stylesheets/components/cms/_add-action.scss
- app/assets/stylesheets/components/page_specific/_category_link_list.scss
Since we have added underlines to improve link identification (for an accessibility requirement) there is a tweak we should make for a visual improvement.
There are now double underlines on in-page links - we should remove the black underline and keep the yellow border-bottom:
| Before |
|--------|
|<img width="536" alt="screen shot 2016-09-29 at 09 43 59" src="https://cloud.githubusercontent.com/assets/13165846/18947062/707e4eda-8629-11e6-95c9-07d29701543c.png">|
| After |
|------|
|<img width="505" alt="screen shot 2016-09-29 at 09 38 21" src="https://cloud.githubusercontent.com/assets/13165846/18946943/0239b25c-8629-11e6-9ca3-c62683daef76.png">|
Text links on the core site are now underlined to make them stand out more. The links inside the div class "add-action", however, remain …
> [DEV APPROVED] 7615: Link underlining tweaks - 7639: Add underline to blue-box text links

- app/views/retirements/pension_savings_timeline.html.erb
- config/locales/landing_pages/pension_savings_timeline.cy.yml
- config/locales/landing_pages/pension_savings_timeline.en.yml
Adds English and Welsh page titles to the Pensions Timeline
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1551)
> [DEV APPROVED] 7657 - Adding page title to pensions timeline

- Gemfile
- Gemfile.lock
update gem source in Gemfile for tidy-html5 gem to fix failing cucumber tests 
error caused by versions being used of bundle, git, cucumber
running cucumber using bundle exec forces cucumber to run using gems listed in Gemfile, 
The Tidy-HTML5 gem source was pointing directly to GitHub repo, changing to pull gem from local gems on build server resolves the error.
Ideally we should update version of Git installed and used by both build servers (1.7.1) to > 1.7.11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1555)
> [DEV APPROVED] #7675 update tidy-html5 gem source to fix failing cucumber tests

- app/views/shared/_footer_primary.html.erb
- config/locales/cy.yml
- config/locales/en.yml
The social media buttons on the foot of the main site are SVGs, which, when clicked open the relevant social media page in a new window.
If users are not made aware that this will open in a new window then they will become disoriented and unable to use the browser's back button to get back to their page.
This has been solved in this PR for some readers by adding 
<span class="visually-hidden">Facebook - opens in a new window</span>
to each of the social media links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1556)
> [DEV APPROVED] 7671 Adding new window label to social links in footer

- app/assets/stylesheets/components/common/_search.scss
- app/views/shared/_search.html.erb
There is a current display issue on the production site, where after performing a search on the search page (https://www.moneyadviceservice.org.uk/en/search) for a brief moment the results will be tucked underneath the search input and button section.
The search form now has a minumum height to ensure that the results begin after the search form element, ``@extend %clearfix;`` was unsuccessful as the typeahead component relies on absolute positioning which rendered the clearfix unable to help in this case.  There is also a conditional which adds a modifier class to the in page search form as this only applies to the form on that page, not the one in the header.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [DEV APPROVED] 7666 - Search form visual display bug fix

- app/assets/stylesheets/components/common/_download_link.scss
- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
The video transcript on this Retirement page is a PDF download, that opens in the browser window. This causes problems for many users, who are subsequently unable to navigate back to the page, and are given no warning that this will happen. 
This changes the functionality to download the file and adds a PDF icon to any link with a download attribute.
|---------|-------|
|<img width="587" alt="screen shot 2016-10-13 at 14 11 35" src="https://cloud.githubusercontent.com/assets/13165846/19350358/4f53560c-914f-11e6-9aca-e0d214419f3a.png">|<img width="585" alt="screen shot 2016-10-13 at 14 11 40" src="https://cloud.githubusercontent.com/assets/13165846/19350362/54d0653e-914f-11e6-98ef-a5b885c9024e.png">|
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [DEV APPROVED] 7672 - Adding PDF download icon

- app/views/shared/_footer_primary.html.erb
- app/views/shared/_stripe_banner.html.erb
- app/views/shared/svg/_use_icon.html.erb
This PR removes SVG's from the tab order, ``tabindex="-1"`` was mentioned in the ticket for this task but had no effect in IE11, ``focusable="false"`` worked in all cases.
**Related PR's**
Publify
https://github.com/moneyadviceservice/publify/pull/214
Dough
https://github.com/moneyadviceservice/dough/pull/276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1566)
> [DEV APPROVED] 7673 - Adding focusable false to SVGs

- app/views/devise/registrations/new.html.erb
A `<fieldset>` element should always contain a `<legend>` element to explain the purpose of he group of fields.
In this case, we no longer need the `<fieldset>` element, as there is only one field within the group, which is adequately explained in the field's label.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1579)
> [DEV APPROVED] 7479 - Removing the fieldset element around signup checkbox

- app/assets/stylesheets/components/common/_directory.scss
- app/assets/stylesheets/layout/page_specific/_category.scss
- app/assets/stylesheets/layout/page_specific/_promos.scss
The Frontend project gives SCSS warnings every time it is started due to SCSS `@extends` that do not extend any selectors. This will error rather than warn in future versions of SASS.
So this PR removes the unnecessary code, and fixes the instances that pointed to an incorrect `clearfix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1580)
> [DEV APPROVED] Removing obsolete SCSS that generates warnings

- app/controllers/feedback_controller.rb
- app/controllers/profile_controller.rb
This PR relates to our 'skip-to' links - we have 'skip to main content' and 'skip to navigation':
This PR:
- Removes 'skip to navigation' from the Profile and Feedback pages. These pages have no nav, so need no link
- Adds a 'main' ID to the main container in the Profile area. This fixes the 'skip to main content' link
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1581)
> [DEV APPROVED] 7717 - Fixing the 'skip-to' links within the profile area

- public/cy/budget-planner-hysbysu.html
- public/en/budget-planner-notification.html
**Task**
Remove link saying view online on static pages for short from budget planner deprecation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1582)
> Removed link saying "view online" from BP3 static pages

- Gemfile
- Gemfile.lock
enables setting maintenance mode serving a static holding page instead of nginx 500 error when database is unavailable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1586)
> add turnout Gem to frontend to enable maintenace mode

- app/controllers/page_feedbacks_controller.rb
- app/decorators/content_item_decorator.rb
- app/views/articles/show.html.erb
- lib/core/entity/article.rb
- spec/controllers/page_feedbacks_controller_spec.rb
We only have a handful of pages that need this right now and it's not expected to change frequently, so went with simply hard coding a list of slugs into a constant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1594)
> 7726 - adding a way to prevent the feedback panel being shown on certain pages

- app/assets/javascripts/components/OnPageFeedback.js
Originally intended to be done with a 30 day cookie, after chatting to @slaywell we decided to go with using localStorage. This is feature detected (and the feedback form will not appear at all if not found) but we are satisfied that support is ubiquitous.
localStorage is a simple key:value store, so we store the data as a serialized json object, with a key of `MAS.onPageFeedback.<article-slug>`.
One caveat: we only retrieve the number of likes and dislikes in the response after doing the actual like/dislike. Therefore, if we later on try to resume the process of asking to share or provide feedback, we don't have the figures to hand once that's complete to show them on the thumbs.
After discussing with Ed (who discussed with Mel), we decided to store the figures we get back after voting …
> 7725 - persist page feedback state in the client

- spec/javascripts/tests/OnPageFeedback_spec.js
The OnPageFeedback Karma test was failing because the component was adding data to localStorage, which was breaking future tests. This PR clears the localStorage before each run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1601)
> Clearing localStorage within Karma test

- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
Adding file type and size to the video transcript PDF for screen reader users:
Related PR: https://github.com/moneyadviceservice/rio/pull/108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1602)
> [DEV APPROVED] 7737 - A11Y: Transcript description

- Gemfile
- Gemfile.lock
Original RIO PR: https://github.com/moneyadviceservice/rio/pull/108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1603)
> 7737 - Bumping rio to 1.11.0

- app/assets/stylesheets/_print.scss
- app/assets/stylesheets/components/page_specific/_category_detail.scss
- app/assets/stylesheets/components/page_specific/_featured_links.scss
- app/decorators/category_content_decorator.rb
- app/views/categories/_child_categories.html.erb
- spec/decorators/category_content_decorator_spec.rb
The Category page has an 'expand / contract' button that toggles visibility on the first 6 items _and_ a 'View all' button that shows _all_ items. This is pretty confusing for users, and has been highlighted by DAC as a usability issue:
This PR:
- removes the 'expand/contract' button
- displays the first **three** links by default
- retains the 'View all' button which expands the whole list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1605)
> [DEV APPROVED] Removing the duplicate expand button on Category Page

- .env
- app/assets/javascripts/components/OnPageFeedback.js
- app/views/shared/_on_page_feedback.html.erb
- lib/core/repository/cms/page_feedback.rb
- spec/cassettes/en/articles/example-article/page_feedbacks.yml
- spec/cassettes/en/articles/example/page_feedbacks-invalid.yml
- spec/lib/core/repository/cms/page_feedback_spec.rb
Since I added the token auth on CMS (you can see here: https://github.com/moneyadviceservice/cms/pull/355) I need to add on the client too (this PR!). 
This still requires work on the puppet scripts to add the token environment variable. More details you can see here: https://github.com/moneyadviceservice/scripts/pull/816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1599)
> [DEV APPROVED] - Add CMS API authentication on page feedbacks endpoints

- app/assets/javascripts/components/OnPageFeedback.js
- app/assets/stylesheets/components/page_specific/_on_page_feedback.scss
- app/views/shared/_on_page_feedback.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/javascripts/tests/OnPageFeedback_spec.js
We are removing the total 'likes' and 'dislikes' from the On-page feedback component (for now, at least).
This PR removes the JavaScript, markup, CSS, locale text and JS tests that comprise this part of the feature.
Note: if a user who has previously completed the On Page Feedback form re-visits the page, the component will not display at all (see line 145 of OnPageFeedback.js).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1610)
> [DEV APPROVED] 7802 - Removing like and dislike count from OnPageFeedback

- bower.json.erb
Our Yeast bower versioning on Production is not strict enough and has automatically upgraded from 1.0.0 to 1.1.0 when I released version 1.1.0.
This change will lock updates to _patch_ versions according to semver, e.g. 1.0.0 to 1.0.x
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1614)
> Being more specific with Yeast versioning

- Gemfile
- Gemfile.lock
RIO PR: https://github.com/moneyadviceservice/rio/pull/110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1618)
> bumping rio to 1.13.0

- app/decorators/category_decorator.rb
- app/views/categories/_relay_page.html.erb
- features/factories/category.rb
- lib/core/entity/category.rb
- lib/core/interactor/category_reader.rb
- spec/decorators/category_decorator_spec.rb
- spec/lib/core/entity/category_spec.rb
- spec/lib/core/interactor/category_reader_spec.rb
**Context**
The global nav works involves data changes which means that some existing urls will become unusable.
Some partners have links to certains of those pages and we will support (for some time?) the old urls of categories that have been splited up.
**Dependency**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1615)
> [DEV APPROVED]7804 new/old categories support

- app/assets/javascripts/application.js
- app/views/categories/show.html.erb
- app/views/search_results/index.html.erb
- app/views/search_results/index_no_results.html.erb
- app/views/search_results/index_with_results.html.erb
Removes the sidebar category nav from the search, search results, and Category pages. The only place we now show this is on the Article page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1624)
> Removing the Sidenav from pages that don't need it

- app/assets/stylesheets/amp_styles.css.scss
The callout styles on the Google AMP pages needed to be brought inline with the new ones on the MAS site articles.
Google AMP supports some pseudo selectors (:not, :first-of-type, :last-of-type), but not :before or :after.  Because of this it was decided to remove the icons and go with a simpler approach for these mobile pages:
**Without a title**
**With a title**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1647)
> [DEV APPROVED]7876 - Adding callout styles

- app/assets/javascripts/modules/global_nav.js
- app/views/shared/_global_nav.html.erb
- app/views/shared/_nav.html.erb
FYI @davidtrussler - some quick tweaks I'm going to merge into the testing branch:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1646)
> [WIP] Temporary fixes for A11y testing

- app/assets/stylesheets/components/common/_icon_2x.scss
- app/assets/stylesheets/layout/page_specific/_article_page.scss
The below SCSS warnings occur whenever running Frontend. This PR fixes these, without any impact to the CSS that is generated:
```
15:10:37 web.1  | DEPRECATION WARNING on line 134 of /Users/mattsaywell/Repos/frontend/app/assets/stylesheets/components/common/_icon_2x.scss:
15:10:37 web.1  |   @extending an outer selector from within @media is deprecated.
15:10:37 web.1  |   You may only @extend selectors within the same directive.
15:10:37 web.1  |   This will be an error in Sass 3.3.
15:10:37 web.1  |   It can only work once @extend is supported natively in the browser.
15:10:37 web.1  |
15:10:37 web.1  |
15:10:37 web.1  | DEPRECATION WARNING on line 139 of /Users/mattsaywell/Repos/frontend/app/assets/stylesheets/components/common/_icon_2x.scss:
15:10:37 web.1  |   @extending an outer …
```
> [DEV APPROVED] - Fixes SCSS deprecation errors

- app/assets/stylesheets/components/common/_icon.scss
- app/assets/stylesheets/components/common/_icon_2x.scss
- app/assets/stylesheets/components/common/_icon_svg.scss
- app/assets/stylesheets/styleguide/_example.scss
- app/views/styleguide/components_common.html.erb
This PR:
- Fixes the missing `.icon--info` icon that is in the styleguide
- Adds a new styleguide section for SVG Icons, our preferred approach to spriting - see http://localhost:5000/en/styleguide/components/common for the new section
- Makes some of the display logic for SVG / PNG more generic rather than repeating the `display: none / block;` logic for each item
- Fixes the PNG fallback for the thumbs up / down icon on double-density screens
This relies upon this [Dough PR ](https://github.com/moneyadviceservice/dough/pull/281)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1636)
> [DEV APPROVED] 7847 - Fixing styleguide icons and adding SVGs

- app/views/shared/_global_nav.html.erb
- lib/core/entity/category.rb
- spec/lib/core/entity/category_spec.rb
`category.contents` returns everything in a category - subcategories, articles, guides, etc.
Added a method to the `Category` entity to return just the categories and updated the global nav to use that instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1653)
> Fix issue with global nav showing more than subcategories under each tab

- app/assets/stylesheets/components/common/_icon_svg.scss
In a previous PR to optimise the icons on the mas frontend site the piece of logic which hides the fallback icons if SVG's are supported was removed, this PR put that logic back in.
| Current Live | After |
|--------|------|
|![image](https://cloud.githubusercontent.com/assets/13165846/22057438/921821e4-dd5c-11e6-8700-966c7eaed90f.png)|![image](https://cloud.githubusercontent.com/assets/13165846/22057404/69bf6d6a-dd5c-11e6-9f51-acac4aeb5635.png)|
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1658)
> [DEV APPROVED] 7916 - Fixing share icons

- app/assets/javascripts/application.js
Implementing the Global Nav has caused the Search-box dropdown on mobile view to cease to function. This PR re-introduces the code that implements this feature and updates it so that it doesn't break the Global Nav (which was the reason it was originally removed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1659)
> [DEV APPROVED] TP: 7917, Comment: Global Nav: fixes mobile search box functioning

- app/assets/stylesheets/components/common/_mobile_nav.scss
- bower.json.erb
With the introduction of the Global Nav the behaviour of the search box needs to be modified so that it only functions as a dropdown version when the nav is not displayed.
The main changes are in Yeast PR30: https://github.com/moneyadviceservice/yeast/pull/30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1661)
> [DEV APPROVED] TP: 7924, Comment: Updates header breakpoints for global nav

- app/assets/javascripts/components/GlobalNav.js
- Pushes to the Google Analytics dataLayer on hover as requested by Periscopix
- Slight refactoring of the hover event handling / timeouts on opening and closing the subnav
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1666)
> [DEV APPROVED] 7939  - Global Nav adding analytics dataLayer push

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/views/shared/_global_nav.html.erb
At the moment there is a brief delay (whilst JS is downloading) where the Global Nav is unusable - hovering on the clump headings does nothing. 
This PR leverages the work already done by @davidtrussler on the no-JS / CSS-hover only code, and makes this behaviour apply until the JS component has downloaded and executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1667)
> [DEV APPROVED] 7944 - CSS fallback for JS behaviour whilst JS is downloading

- app/assets/stylesheets/components/common/_global_nav.scss
- app/views/shared/_global_nav.html.erb
Reverts moneyadviceservice/frontend#1668
Just spotted another minor error on this: reverting this PR to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1669)
> Revert "[DEV APPROVED] TP: 7944, Comment: Fixes some Safari-specific bugs"

- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/views/shared/_global_nav.html.erb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1671)
> TP7944: Global Nav UI tweaks / styling

- app/assets/javascripts/components/GlobalNav.js
This disables the click event on the clump headings on desktop view only, which are not links to another area of the site and also have hover events attached to them. It has been added because it is confusing for the user to have both click and hover events on these elements, which cancel each other out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1673)
> [DEV APPROVED] TP: 7944, Comment: Disables click event on clump headings

- app/assets/stylesheets/components/common/_global_nav.scss
- app/views/shared/_global_nav.html.erb
This fixes some inconsistencies across browsers with the handling of FlexBox
Also removes the 'blog' button at medium-width media queries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1672)
> 7944 flexbox inconsistencies

- app/assets/javascripts/components/GlobalNav.js
This disables focus on the global nav top level menu when clicked. This is to avoid confusing behaviour for the user whereby mouse events serve no other purpose (there is no link to follow and the sub-menu is opened by the hover event). 
Focus is retained when the user is navigating by keyboard (tab or left/right arrow) which is necessary because another keyboard action (enter or down arrow) is then required to open the sub-menu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1675)
> [DEV APPROVED] TP: 7978, Comment: Removes focus from clump headings for mouse events

- app/assets/stylesheets/components/page_specific/_home_top.scss
- app/assets/stylesheets/components/page_specific/_promo.scss
- app/assets/stylesheets/layout/page_specific/_homepage.scss
- app/assets/stylesheets/layout/page_specific/_promos.scss
- app/views/shared/_home_top.html.erb
- app/views/shared/_tool_promos.html.erb
In PR #1674 we are removing the 'Category Directory' from the homepage. This leaves us with a few layout issues with components on the homepage.
This PR:
- Adds a grey background to the 'popular tools and calculators' section that now follows the hero slot
- Changes the way that the homepage handles 'medium' width viewports - see images below - the layout is significantly different. I have also changed some font-sizes and given the hero slot a new layout at medium width viewports.
- Slightly alters the way that the full-width layout appears - the right-hand-side hero image is now constrained within its container
**Screenshots are at around 800px width, but to get a feel for the changes I would recommend local testing / resizing browser window**
New version: 
Production: 
This change …
> [DEV APPROVED]7979 - Global Nav - responsive homepage restyle

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_subnav.scss
- Fixes this bug: https://moneyadviceservice.tpondemand.com/entity/7983
- Refactors the methods used to toggle the mobile nav. We previously had `_closeMobileNav` **and** `_toggleMobileNav`, now we only need the latter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1679)
> 7893 - Fixes bug with mobile submenu show/hide

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_nav.scss
This PR replaces hover events with touch events where required. Fixes issue in TP7980.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1678)
> [DEV APPROVED] TP: 7980, Comment: Fixes touch-specific device issues

- app/views/shared/_footer_primary.html.erb
- app/views/shared/_global_nav.html.erb
- config/locales/cy.yml
- config/locales/en.yml
We forgot to add the blog link to the Global nav. This PR adds the `href` to the link, and re-organises the yaml file that contains it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1680)
> 7983 - Global nav - adding blog link

- app/assets/stylesheets/components/common/_global_nav.scss
- blog link given same property as other clumps to fix issue where this element breaks layout by being forced onto a second line
- also fixes hover/focus states of this link to be consistent with the footer blog link
Blog link forced onto second line breaks layout: 
Blog link brought into line: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1684)
> [DEV APPROVED] - TP: 7993, Comment: Fixes fallback for non-FlexBox browsers

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/page_specific/_category_detail.scss
- app/views/categories/_child_categories.html.erb
- app/views/categories/_content_items.html.erb
- app/views/categories/_corporate_categories.html.erb
- app/views/corporate/_child_categories.html.erb
- app/views/corporate_categories/_child_categories.html.erb
- app/views/styleguide/shared/_category_detail.html.erb
- Allows user to collapse the extended list of links to avoid excessive page length
- Removes data-dough-component="Collapsable" from this component since it's no longer used here
- Also adds this to corporate category pages (though I believe there are none on the site)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1685)
> [DEV APPROVED] TP: 7927, Comment: Adds "contract" option to category pages

- config/initializers/backtrace_silencers.rb
This is something that's bugged me for some time on several projects and I only came across an explanation of what's going on the other day. Rails also nowadays includes a template initializer for this sort of thing in newly generated applications.
In short, when we have custom middlewares they produce entries upstream of our application backtrace and unless we tell Rails to ignore them, it won't know that that's not a relevant part to show us in the event of an exception.
**Example: problem with an unexpected nil in my UC engine conversion**
So if we tell the backtrace silencer to ignore those four custom middlewares:
Much more helpful!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add custom backtrace silencers to stop custom middlewares obscuring application backtraces

- .env
- lib/core/connection_factory/http.rb
- spec/lib/core/connection_factory/http_spec.rb
The TL; DR we are living on the edge for one request to return 500 every hour on the site or when someone deploys the site.
QA homepage was returning 500 internal server error. The logs shown the site returns 500 but CMS returns 200. Investigating more see it is *exceeding the timeout.*
The site makes the request to the CMS and CMS (on QA) takes more than 5 seconds to respond to the categories url (details here: https://cms.qa.dev.mas.local/api/en/categories.json).
Since we have 5 seconds as timeout on the site I decided to "measure" (gross way to measure I would say) how long it is taking *in production*.
It is taking between 4.600 sec to 4.800sec on my machine.
You can run `time curl -XGET https://cms.moneyadviceservice.org.uk/api/en/categories.json` to confirm it what I said. Or use …
> [DEV APPROVED] - Add a environment variable for all http requests timeout

- app/assets/javascripts/components/StickyColumn.js
There was a fix for IE 8 that caused the sticky nav to flow off the screen to the right. I checked and the fix is not required anymore and removed. I fixed the bug by removing the left positioning call in the js file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1692)
> [DEV APPROVED]8057 Related Links nav bug

- app/assets/javascripts/components/GlobalNav.js
- mobile swipe gestures by default keep the user on the main site
- this change moves focus to the nav and ensures the user can navigate this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1696)
> [DEV APPROVED] TP: 8031, Comment: Moves focus to nav when opened

- app/assets/javascripts/application.js
- app/assets/javascripts/modules/mas_collapsable.js
- currently focus remains on the button which is confusing for a vision-impaired user
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1697)
> [DEV APPROVED] TP: 8032, Comment: Moves focus into search box when opened

- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/assets/stylesheets/components/common/_search.scss
- this makes the styles of these elements on both mobile and desktop consistent with the search button elsewhere on the site (changes background colour and retains icon colour) when activated. This keeps the colour contrast within an acceptable range for accessibility.
Current: 
Updated: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1700)
> [DEV APPROVED] TP: 8033, Comment: Updates styles of search bar button

- app/assets/javascripts/components/GlobalNav.js
- this is to ensure the user is aware that the content has changed when navigating to a subcategory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1699)
> TP: 8029, Comment: Adds aria-expanded properties to nav headings

- Gemfile.lock
Bumping mortgage calculator for the end of year tax changes, these can go into production before april as it only removes the reference: From April 2016....
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1702)
> Bumping mortgage calculator for 8055

- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/assets/stylesheets/components/common/_no-js_nav.scss
- app/views/layouts/_application_shared.html.erb
- app/views/shared/_no_js_nav.html.erb
It is not possible to navigate the current global nav via keyboard commands with JavaScript disabled or if JavaScript does not load. This PR adds an alternative navigation that displays in these circumstances and allows keyboard-only users to be able to navigate the site. 
**Alternate nav on desktop:** 
**Alternate nav on mobile:** 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1709)
> [DEV APPROVED] TP: 7996, Comment: Adds alternative navigation for non-js users

- app/assets/stylesheets/components/common/_icon_svg.scss
- app/assets/stylesheets/components/common/_social_sharing.scss
- app/assets/stylesheets/components/page_specific/_stripe_banner.scss
- app/views/shared/svg/_icon_sprite.html.erb
There area a number of instances where icons are displaying incorrectly in non-JavaScript environments, specifically:  
**Social Sharing icons in the footer**
**The arrow in the striped banner on the homepage**
**The Social Sharing icons on articles pages**
This PR fixes these issues and additionally adds consistency to the way the SVG icon for the Clear Language section of the footer is coded: 
- Adds this to the comments
- Moves the currently styles to the CSS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1716)
> 8149 icons display issue no js

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/helpers/budget_warning.rb
- app/views/layouts/_unconstrained.html.erb
- config/budget_warning_tools.yml
- spec/helpers/budget_warning_spec.rb
- spec/helpers/shared_examples/displays_banner_warning.rb
This pr removes the warning added in pr #1705.
Rather than delete the code which was added back in recently, changing the date ensures the warning is not displayed. There are several options to achieve this result, including setting the whitelist to an empty array.  This pr is to initiate _brief_ discussion on the preferred approach in terms of balancing effort, urgency and future proofing.
We decided to use a yaml file to configure which tools should show budget warnings. If the file is empty, no warning will be displayed. This approach will minimise the developer effort required to enable/disable the message each tax year.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservi …
> [DEV APPROVED] Remove new tax year warning

- app/assets/javascripts/syndication/tools.js.coffee
This PR adds the universal credit to the list of tools that will not render header nor footer from syndications requests (a request to the site with a X-syndicate header as true ).
More details about how syndication works you can see [here](https://github.com/moneyadviceservice/syndication_documentation).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1730)
> [DEV APPROVED] Syndidate the universal credit tool

- app/assets/stylesheets/components/page_specific/_floating_chat.scss
- app/views/shared/_contact_panels.html.erb
There is currently a JS error on every page apart from the homepage, this is caused by the JS looking for a variable which is undefined as the element it refers to only exists on the homepage (Where the floating chat is restricted to).
| Screenshot of error |
|------------|
|<img width="541" alt="screen shot 2017-05-18 at 15 19 47" src="https://cloud.githubusercontent.com/assets/13165846/26206808/ae53327e-3bdd-11e7-9462-1b119403f8f8.png">|
This PR wraps the sections of the JS in the contact panels which refer to this element in the condition:
```
<% if show_floating_chat? %>
```
This way the errors do not appear on any of the other pages, the variable will only be required when the floating chat is active, and will work on every subsequent page we add it to.
**Screenshots of solution**
| …
> [DEV APPROVED] 8120 - Fixing WebChat JS Error

- Gemfile
- Gemfile.lock
Bumping Unversal Credit to 2.1.0
This PR bumps the version of universal credit to version 2.0.2, the new version contains the following tickets:
[8186 - UC - Expand/Collapse Behaviour on 'to read'](https://github.com/moneyadviceservice/universal_credit/pull/128/files)
[8184 - Money Manager - Display Issues](https://github.com/moneyadviceservice/universal_credit/pull/129)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1738)
> [DEV APPROVED] Bumping UC/Money manager to 2.1.0 for tickets 8184 and 8186

- Gemfile
- Gemfile.lock
Bumping UC/MM in frontend to version 2.1.1 for ticket [8216](https://github.com/moneyadviceservice/universal_credit/pull/130)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1739)
> Bumping frontend to 2.1.1 for ticket 8216

- Gemfile
- Gemfile.lock
This bumps the new version of UC to 2.2.1
This is in reference to ticket [#8187](https://moneyadviceservice.tpondemand.com/entity/8187) and PR [138](https://github.com/moneyadviceservice/universal_credit/pull/138) and [141](https://github.com/moneyadviceservice/universal_credit/pull/141).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1745)
> 8187::Bumps version of UC to 2-2-1

- README.md
We don't need to add the private gem server to /etc/hosts file
anymore and we are not using feature toggles anymore either.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1747)
> Removing outdated steps on the Readme

- app/assets/javascripts/components/GlobalNav.js
- spec/javascripts/fixtures/GlobalNav.html
- spec/javascripts/test-main.js
- spec/javascripts/tests/GlobalNav_spec.js
This PR adds Karma tests for the Global Nav in the following areas: 
* Test for initialisation of component: check init is calling the appropriate methods. This also slightly refactors GlobalNav.js to put the two one-liners into a separate method. It's is a bit neater I think and helps test the init as a single unit which is probably better practice.
* Tests for binding events. In fact this just tests that the uninitialised class is removed when the component loads
* Test for mobile animation. This should test that the no-transition class is added/removed when the window is resized. I have so far been unable to simulate the resize event in this test so this is left as an empty test (i.e. it passes but only because it isn’t doing anything but can serve as a reminder to work on it at a …
> [DEV APPROVED] 7923 global nav add tests

- app/views/shared/_contact_panels.html.erb
https://moneyadviceservice.tpondemand.com/entity/8274
**Summary**
Currently on the production site the webchat fails to load in IE8 and throws an error.  This PR addresses this error by changing the JS selector from ``document.getElementsByClassName()`` <- Not supported by IE8, to ``document.getElementById()`` and adding an ID to the chat popup.
**Examples**
| Before | After |
|-------|------|
|![screen shot 2017-06-12 at 13 13 21 2](https://user-images.githubusercontent.com/13165846/27033933-624c49a2-4f73-11e7-8e22-aac506681357.png)|![screen shot 2017-06-12 at 13 31 36 2](https://user-images.githubusercontent.com/13165846/27033960-803eb666-4f73-11e7-9c3b-a7470b56b6b4.png)|
**Checklist**
+ [x] Code Climate passed for this PR.
+ [x] Commit …
> [DEV APPROVED] 8274 - Webchat not working in IE8

- README.md
Setting up for development documentation:
* Signpost setting up a local CMS a little more
* Adds a section for common gotchas and mitigations encountered while we Cultivars were getting set up on the 12 June 2017.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1748)
> Add more emphasis on local CMS and include some common gotchas in the README

- config/locales/employer_best_practices.en.yml
TP Ticket:
https://moneyadviceservice.tpondemand.com/entity/8343
**Summary**
The Infographic on this page:
https://www.moneyadviceservice.org.uk/en/employer-best-practices/my-business
Contains a typo - The bottom left hand point says:
"70% of employees would point employees to useful information if they had access"
This should read:
"70% of employers would point employees to useful information if they had access"
This PR makes this change, please note this is for English only
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1757)
> [DEV APPROVED] 8343 - Employer Best Practice Typo

- app/controllers/amp_articles_controller.rb
TP #8388
https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=5D6AC326B4D272C23E446C28586BAF51#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=Bug/8388
**Summary**
add new relic_ignore_enduser call to amp_articles_controller to prevent new relic js script being injected into AMP pages
**Testing**
Tested on UAT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1762)
> #8388 add newrelic_ignore_enduser to amp articles controller

- app/views/layouts/_base.html.erb
- config/application.rb
Replace Broken GooglePlus link on Frontend application 
Old link is now broken because the admin account used to create has now been deleted.
https://plus.google.com/+MoneyadviceserviceOrgUkYourMoneyAdvice/
Needs to be replaced with the numerical url link below
https://plus.google.com/116645767000258814442
TP ticket link:-
https://moneyadviceservice.tpondemand.com/entity/8476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1777)
> #8476 remove GooglePlus link embedded in frontend app

- app/views/shared/_footer_primary.html.erb
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8493)
Clear English Standard are changing the domain they use. This PR updates the link to their site in the footer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1782)
> [DEV APPROVED] 8493 clear english link update

- app/assets/javascripts/components/HomeBuyingChecklist.js
- app/assets/stylesheets/_print.scss
- app/assets/stylesheets/components/page_specific/_home_buying_checklist.scss
- app/views/home_buying_checklist/show.html.erb
- config/locales/home_buying_checklist/home_buying_checklist.cy.yml
- config/locales/home_buying_checklist/home_buying_checklist.en.yml
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8324).
This PR adds some amendments to the home buying checklist - see PR(https://github.com/moneyadviceservice/frontend/pull/1765). 
We created this as a separate PR so changes are easier to review.
These are essentially features from the [prototype](http://zvazqj.axshare.com/#g=1&p=my_do_to_list__v4_-_upfront_cost) that hadn't been implemented (mostly responsiveness) plus some text changes. We have also refactored the view to iterate over a translation file, to remove a lot of duplication.
* Green check next to inputs:
* E-mail button:
* Print button:
* *Mobile*: add (i) popups to titles:
* *Mobile*: Collapsible text in link.
* Styling changes
Before:
After:
---
This change is [<img …
> [DEV APPROVED] 8324 home buying checklist amendments

- config/locales/home_buying_checklist/home_buying_checklist.cy.yml
- config/locales/home_buying_checklist/home_buying_checklist.en.yml
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8324).
This PR adds some changes to how links are handled on home buying checklist PR(https://github.com/moneyadviceservice/frontend/pull/1765). 
We created this as a separate PR so changes are easier to review.
Links now open in a new window but with the same target so that a new tab is only opened once
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1792)
> 8324 add target to links so they open in same window

- config/locales/retirements.en.yml
[TP Story](https://moneyadviceservice.tpondemand.com/entity/8464)
Tiny fix to remove an erroneous `'` from the end of a canonical link that caused issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1793)
> [DEV APPROVED] 8464 Fix Canonical Link

- app/views/corporate/index.html.erb
- config/locales/corporate/corporate_home.cy.yml
- config/locales/corporate/corporate_home.en.yml
[TP link](https://moneyadviceservice.tpondemand.com/entity/8364)
**Summary**
This fixes a number of incorrect/missing Welsh links on https://www.moneyadviceservice.org.uk/en/corporate/.
The ticket pointed out one of these - the "Media centre" URL that was used works in English, but has no corresponding Welsh page and thus caused an error when the "Welsh" link is clicked.
In the process of fixing this, I found that the view had hardwired English URLs for several links, even though Welsh versions exist. So this PR also addresses that by using path helpers, and moving the link slugs into translation files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1790)
> [DEV APPROVED] 8364 - Fix Welsh links

- app/controllers/categories_controller.rb
- features/cassettes/CMS/get/api/en/categories/nonexistent-category_json.yml
- features/categories.feature
- features/step_definitions/category_steps.rb
- spec/controllers/categories_controller_spec.rb
[TP link](https://moneyadviceservice.tpondemand.com/entity/8391)
**Summary**
Visiting https://www.moneyadviceservice.org.uk/en/corporate_categories/blah (where 'blah' can be by any nonexistent category) returns a 500 error (`Core::Repository::Base::RequestError 'Unable to fetch Category JSON from Contento'` is raised). A 404 should be returned instead.
This is ultimately because `Core::Repository::Categories::CMS` errors when a category doesn't exist in the CMS, and this error is never caught. Changing this behaviour deeper in the system could potentially impact on other code that depends on it, so we just rescue it in the controller and show a 404.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> [DEV APPROVED] 8391 - Broken page should show 404 error

- Gemfile
- Gemfile.lock
- README.md
Currently, running `bundle install` for the first time with the latest version of `bundler` returns an error:
```
Downloading codeclimate-test-reporter-0.6.0 revealed dependencies not in the API or the lockfile (simplecov (< 1.0.0,
->= 0.7.1)).
Either installing with `--full-index` or running `bundle update codeclimate-test-reporter` should fix the problem.
```
There's a known workaround, which is to downgrade `bundler` to 1.14.6. Once the gems have been installed, `bundle install` works with no errors even with the latest `bundler` version, which is probably why this problem doesn't appear in Go builds or MAS dev environments.
The problem turned out to be an incorrectly specified dependency for `codeclimate-test-reporter` in the `Gemfile.lock` (similar problems are described …
> [DEV APPROVED] Fix `bundle install` issues with latest `bundler`

- package.json
This PR is very similar to https://github.com/moneyadviceservice/budget_planner/pull/484, and done for similar reasons.
The currently specified versions of PhantomJS and a number of Karma packages are very old (many years). These are only used to run specs, and the specs run fine with the most recent versions, so this updates them. `karma-sinon-chai` had to be locked to a less recent version, since more recent ones cause individual tests to fail.
Since these packages are only used in development, deploying this change to production should not cause any issues.
Without some of these updates, it's often not possible to run the specs at all on systems with relatively recent versions of PhantomJS (>=2) installed, which causes issues for development.
---
This change is [<img …
> [DEV APPROVED] Update JavaScript dev dependencies

- app/views/layouts/_base.html.erb
There currently an issue with tracking and optimizely where JQuery is being loaded after both scripts, and optimizely requires JQuery, this is resulting in around a 40% of target users not seeing the A/B tests.
This PR moves the inclusion of JQuery to before the optimizely include tag.
You'll notice that I have include an ``async`` attribute to the JQuery include tag, this will ensure that the script in non-blocking, and will allow the DOM content to be loaded while script is executed.  After a quick test I found the following performance impact:
| | DOMLOAD (Page is readable) | FULL LOAD (All images, scripts are complete) |
|-------|-------|-------|
| Current | 1.24s | 2s |
| ASYNC | 1.60s | 1.97s |
The DOM load is slightly impacted because the scripts are being executed at the same time …
> [DEV APPROVED] Moves the inclusion of JQuery higher in layout template

- app/assets/javascripts/syndication/tools.js.coffee
Ticket https://moneyadviceservice.tpondemand.com/entity/8566
Currently when the debt advice locator (f2f) tool is mounted using the syndication script, the tool appears very narrow, around 300px.
This needs to be adjusted so that the tool expands to the width of its parent container (iframe needs to have 100% width).  This gives partners control over how wide the tool appears once mounted as it will always be the full width of the container they put it in.
| Before | After |
|-------|------|
|![image](https://user-images.githubusercontent.com/13165846/30277169-e310c4d2-96fe-11e7-9833-a54bb60a7117.png)|![image](https://user-images.githubusercontent.com/13165846/30277185-ed097b8c-96fe-11e7-96bd-137157cd4e8f.png)|
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [DEV APPROVED] 8556 - Sets a flexible width for syndicating debt advice locator tool (f2f)

- Gemfile.lock
- db/schema.rb
TP: https://moneyadviceservice.tpondemand.com/entity/8543
So this PR bumps the budget planner version which contains the budget planner referral url feature and adds the referral url to the database. The whole work you can see here: https://github.com/moneyadviceservice/budget_planner/pull/485
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1813)
> 8543 - Update budget planner to 5.0.3.771

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/views/shared/_global_nav.html.erb
- spec/javascripts/fixtures/GlobalNav.html
- spec/javascripts/tests/GlobalNav_spec.js
TP [8549](https://moneyadviceservice.tpondemand.com/entity/8549)
a) These tools are often interacted with on Desktop so it would be valuable to surface them on mobile as well.
b) Fix vertical scrolling issue introduced to mobile nav when tools are displayed.
**Bonus**
Fix body scrolling issue discovered while testing mobile nav.
Change tools in mobile nav visibility to `display: block;`
Add `'no-scroll` class to body when mobile nav is opened.
Update subnav view  by adding `is-hidden` class and remove class with javascript when subnav is triggered.
Increase bottom padding in `.global-subnav` to allow the close button to be displayed.
This work led to the discovery of some limitations to our Karma testing environment. 
**Specifically:**
Karma is not set up to compile SCSS and include these …
> [DEV APPROVED] 8549 - Adds links for tools on mobile nav

- app/views/amp_articles/show.html.erb
[8584](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8582&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8584)
**Summary**
This PR deals with the situation whereby it has been historically not possible to track users moving from AMP pages to the responsive site. It has become possible to do this after Google published a [fix](https://support.google.com/analytics/answer/7486764?hl=en&ref_topic=7378717).
This involves two steps:  
- Addition of code to the AMP pages
- Change to the Tag Manager Configuration
Only the first of these is addressed here, the other has already been carried out externally (Periscopix).
---
This change is [<img …
> [DEV APPROVED] TP: 8584, Comment: Adds tracking code to AMP pages

- app/controllers/errors_controller.rb
- app/views/errors/show.html.erb
- features/cassettes/CMS/get/api/en/tools/i_dont_exist_json.yml
- features/error_page.feature
- features/step_definitions/error_page_steps.rb
- features/support/env.rb
- features/support/ui/pages/internal_server_error.rb
- features/support/world/pages.rb
[Card: 8577](https://moneyadviceservice.tpondemand.com/entity/8577)
https://moneyadviceservice.tpondemand.com/entity/8577
**Summary**
This card picks up on the work done last week to push through some changes to the error pages. Some recommendations were made and it was suggested that a card should be made to complete these proposed refactoring. This card does not add new functionality but rather enhances the underlying code behind a feature that works already. 
**404 Page in English**
**500 Page in Welsh**
You can test this by directly visiting the error pages for the HTML status codes for 404 and 500. 
404: http://localhost:3000/404?locale=en
500: http://localhost:3000/500?locale=cy
**Checklist**
+ [ ] Rubocop is passing for …
> [DEV APPROVED] 8577 - Refactor Error pages

- Gemfile
- Gemfile.lock
[TP8599](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=userstory/8558&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8599)
**Summary**
Bumps UC version for [PR192](https://github.com/moneyadviceservice/universal_credit/pull/192) on UC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1818)
> TP: 8599, Comment: Bump UC version to 2.15.0

- app/assets/stylesheets/components/common/_global_subnav.scss
[TP8606](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&boardPopup=bug/8606)
**Summary**
After a recent deploy the nav drop-downs are displaying without the drop shadow at the bottom making this hard to distinguish from the general background.
The solution is to revert a change that was made for the mobile nav on desktop devices.
**Examples**
Before: 
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1817)
> [DEV APPROVED] TP: 8606, Comment: Fixes dropdown display issue

- .bowerrc
When our [GO CI](https://go.dev.mas.local/go/tab/build/detail/responsive_commit_uat/256/test_and_build/1/test)
runs `bower install` the following error is raised:
`Request to https://bower.herokuapp.com/packages/angular failed with 410`
This is because the bower registry: `http://bower.herokuapp.com` is not working anymore.
And you can see here we need to update the bower registry to the new one: https://gist.github.com/sheerun/c04d856a7a368bad2896ff0c4958cb00
More of the issue you can follow here: https://github.com/bower/bower/issues/2484
See the build passed for this: https://go.dev.mas.local/go/tab/build/detail/responsive_commit_uat/257/test_and_build/1/test
So we need to update *ALL* of our tools on bower registry if we continue to use bower. This requires a further discussion with …
> [DEV APPROVED] Change bower registry

- Gemfile
- Gemfile.lock
Bumps UC tool to version 2.16.0 for [PR](https://github.com/moneyadviceservice/universal_credit/pull/195)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1823)
> Bumps UC version 2-16-0

- db/schema.rb
Cost calculator builder is returning an [error](https://app.bugsnag.com/money-advice-service/responsive-site/errors/57f8a21e9a8502cbc9b7ae45?filters%5Bevent.since%5D%5B%5D=30d&filters%5Berror.status%5D%5B%5D=open).
This is because the field was not included on the db migrate. Adding on db migrate solves the issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1825)
> [DEV APPROVED] Added cost calculator builder migration

- app/views/home_buying_checklist/show.html.erb
[TP 8604](https://moneyadviceservice.tpondemand.com/entity/8640)
**Summary**
Currently Google is indexing the home buying checklist, this shouldn't happen as its part of an A/B test to test the demand for the tool.
**Checklist**
+ [x] Code Climate passed for this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1836)
> [DEV APPROVED] 8640 - Adds noindex to homebuying checklist

- app/views/layouts/_base.html.erb
[TP: 8562](https://moneyadviceservice.tpondemand.com/entity/8562)
**Summary**
Once upon a time, in the early days of Optimizely at MAS, A test code was added for a single training session.  This code only applies to the /empty pages.  This code is not needed, and thus removed.
**Checklist**
+ [x] Code Climate passed for this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1837)
> [DEV APPROVED] 8562 - Removes old optimizely code

- app/assets/javascripts/components/Breadcrumbs.js
- app/assets/javascripts/require_config.js.erb
- app/views/shared/_breadcrumbs.html.erb
- bower.json.erb
[TP7975](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/7975)
This PR relates to [PR42](https://github.com/moneyadviceservice/yeast/pull/42) on Yeast and bumps the version number to 1.6.1 to deploy that change to frontend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1835)
> [DEV APPROVED] TP: 7975, Comment: Adds Breadcrumb component + bumps version number for Yeast

- app/assets/javascripts/components/Breadcrumbs.js
[TP7975](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/7975)
**Summary**
Removes console logs accidentally left from development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1843)
> [DEV APPROVED] TP: 7975, Comment: Removes unwanted console logs

- config/locales/home_buying_checklist/home_buying_checklist.en.yml
This PR is for ticket [8700](https://moneyadviceservice.tpondemand.com/entity/8700)
To reflect the new budget changes to Stamp Duty, in effect as of today, we need to add a sentence to the Stamp Duty section of the Home Buying Checklist: https://www.moneyadviceservice.org.uk/en/home-buying-checklist
Add sentence: 
"First-time buyers will pay no Stamp Duty on the first £300,000 for properties worth up to £500,000."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1845)
> [DEV APPROVED] 8700 - Updates stamp duty copy in home buying checklist

- Gemfile
- Gemfile.lock
Bumps WPCC for [this PR](https://github.com/moneyadviceservice/wpcc/pull/174) and [This PR](https://github.com/moneyadviceservice/wpcc/pull/172)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1850)
> Bumps WPCC to 1.11.14 for WPCC accessibility updates

- app/controllers/application_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/_base.html.erb
- spec/controllers/application_controller_spec.rb
[TP#8727](https://moneyadviceservice.tpondemand.com/entity/8727)
**Summary**
A developer from the charity Rethink reported seeing a potential JS error in Money Manager. This potentially impacting other tools. This error is common to all syndicated tools (e.g. https://partner-tools.moneyadviceservice.org.uk/en/tools/baby-money-timeline) and is because the Optimizely script isn’t available via the partner-tools domain. Periscopix are currently working to filter that domain via GTM. We will check again once that work is done ([as explained by](https://moneyadviceservice.tpondemand.com/entity/8727) @davidtrussler)
The Optimizely script tags should only be rendered on the production and UAT environment for and non-syndicated tools.
**Checklist**
+ [x] …
> [DEV APPROVED] 8727 Remove Optimizely tag from syndicated tools

- Gemfile
- Gemfile.lock
TP: 8729
Bumps version of WPCC to 1.12.0 to implement the new tooltips on this tool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1859)
> TP: 8729, Comment: Bumps versions of WPCC

- Gemfile
- Gemfile.lock
- bower.json.erb
https://moneyadviceservice.tpondemand.com/entity/8618
Bumps wpcc to 1.13.0 - add conditional messaging for near threshold warnings
bumps yeast to 1.6.4 - extra styling for warning conditional message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1864)
> Bump wpcc to 1.13.0 and yeast to 1.6.4

- Gemfile
- Gemfile.lock
Some wpcc changes don't seem to have come through so bumping a version patch. to try and force these things through.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1865)
> Bump wpcc from 1.13.0 to 1.13.1

- Gemfile.lock
Bumps dough to latest version (5.26.2.302) for ticket 8744
[TP Ticket 8744](https://moneyadviceservice.tpondemand.com/entity/8744-tooltip-component-bug)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1873)
> [DEV APPROVED] - Bumps dough to 5.26.2.302 for tooltip no-js update 8744

- app/assets/stylesheets/components/page_specific/home_beta/_tool_promo.scss
- app/views/home_beta/show.html.erb
- app/views/shared/home_beta/_tool_promos.html.erb
- app/views/shared/svg/_icon_sprite.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/home_beta_page.feature
- features/step_definitions/home_beta_page_steps.rb
- features/support/ui/pages/home_beta.rb
- features/support/world/pages.rb
Adds a tools and calculators spotlight box for the new homepage:
|--------|-------|
|![image](https://user-images.githubusercontent.com/13165846/34865935-9212b494-f772-11e7-84ee-a84669def71f.png)|![image](https://user-images.githubusercontent.com/13165846/34865918-82d9a8a2-f772-11e7-9b5a-0ed636941036.png)|
To view locally:
http://localhost:5000/en/home-beta
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1880)
> 8681 Tools spotlight

- app/assets/stylesheets/components/page_specific/home_beta/_seasonal_spotlight.scss
- app/assets/stylesheets/layout/page_specific/_homepage_beta.scss
- app/views/home_beta/show.html.erb
- app/views/shared/home_beta/_seasonal_spotlight.html.erb
- features/home_beta_page.feature
- features/step_definitions/home_beta_page_steps.rb
- features/support/ui/pages/home_beta.rb
|--------|--------|
|![image](https://user-images.githubusercontent.com/13165846/34992738-03cfdcaa-fac6-11e7-9027-a8877e904955.png)|![image](https://user-images.githubusercontent.com/13165846/34992775-24e64820-fac6-11e7-9d43-f0dcd9294959.png)|
The heights use flexbox, IE9 fallback added (Screenshot below:)
[TP Ticket 8684](https://moneyadviceservice.tpondemand.com/entity/8684-create-seasonal-spotlight-box)
**Summary**
This is a ticket to create a Seasonal spotlight box for the homepage, highlighted below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1884)
> 8684 - Seasonal Spotlight

- app/assets/stylesheets/amp_styles.css.scss
- app/decorators/amp_article_decorator.rb
- app/views/amp_articles/show.html.erb
- lib/html_processor.rb
- lib/html_processor/amp_iframe.rb
- lib/html_processor/amp_img.rb
- spec/lib/html_processors/amp_iframe_spec.rb
- spec/lib/html_processors/amp_img_spec.rb
- spec/lib/html_processors/amp_video_spec.rb
[TP ticket link](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/8783&appConfig=eyJhY2lkIjoiRjk1Qzc3Njg4REFDNTUyNTBGODhGNTE5MEM5M0JCN0UifQ==)
This PR creates a converters for `img` and `iframe` tags when we render an amp article to convert them to their corresponding `amp-img` and `amp-iframe` tags.
The `src` attribute on an `img` tag is mandatory so I'm removing and not replacing with `amp-img` if it's not present.
Create an article that's enabled for amp
Add an img and an iframe
Verify that they are correctly converted to their corresponding `amp-img` and `amp-iframe` components
Disable javascript then load a converted `img` tag and verify that it still gets displayed
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ …
> [DEV APPROVED] TP 8783: Creates amp-img tag converter

- app/assets/stylesheets/components/page_specific/home_beta/_information_guides.scss
- app/views/home_beta/show.html.erb
- app/views/shared/home_beta/_information_guides.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/home_beta_page.feature
- features/step_definitions/home_beta_page_steps.rb
- features/support/ui/pages/home_beta.rb
This ticket is to create the 'information guides on our site' element for the homepage.
These spotlights are to highlight guides/content that we know a lot of users, who land on our homepage, require.
[TP Ticket 8685](https://moneyadviceservice.tpondemand.com/entity/8685-homepage-create-information-guides-on-our)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1887)
> [DEV APPROVED] 8685 information guides

- app/assets/stylesheets/components/page_specific/home_beta/_central_search.scss
- app/controllers/home_beta_controller.rb
- app/views/home_beta/show.html.erb
- app/views/shared/home_beta/_central_search.html.erb
- app/views/shared/home_beta/_search_beta.html.erb
This PR creates the search component for the MAS  beta homepage. 
[TP](https://moneyadviceservice.tpondemand.com/entity/8680-homepage-create-central-search-box)
As a new user I want to start my journey on the Money Advice Service site using site search but I don't always see the top right search box.
**What needs to happen:**
Implement a UI element below the leader image that features site search, centred on the page.
|English | Welsh|
|-------|--------|
| <img width="1219" alt="screen shot 2018-01-26 at 11 08 27" src="https://user-images.githubusercontent.com/2187295/35437251-8277ee88-0289-11e8-8a8f-8ef1708c7393.png">| <img width="1216" alt="screen shot 2018-01-26 at 11 08 53" src="https://user-images.githubusercontent.com/2187295/35437278-916a80fe-0289-11e8-93d2-fa1e66228188.png">|
> Homepage Beta Search Component

- app/decorators/category_content_decorator.rb
- app/decorators/corporate_category_content_decorator.rb
- spec/decorators/category_content_decorator_spec.rb
[TP 8836](https://moneyadviceservice.tpondemand.com/entity/8836-all-of-the-more-in-links)
[TP 8876](https://moneyadviceservice.tpondemand.com/entity/8876-tools-links-on-category-pages-do)
**Summary**
Some of the links to tool pages are broken, and are redirecting to the current page rather than the correct tool.
Some of the tool page objects are now coming through as `Mas::Cms::Other` rather than `Core::Other`. 
When the `CategoryContentDecorator` tries to add the `path` to pages, they are getting missed as the `Mas::Cms::Other` type isn't listed.
The paths therefore aren't available when we create the links in the `_more_in` partial. 
Test that the links which were previously broken (redirecting back to the same page) on these two pages are now …
> [DEV APPROVED] 8836: Resolve issue with missing paths for tools pages

- app/views/shared/_on_page_feedback.html.erb
[TP 8814](https://moneyadviceservice.tpondemand.com/entity/8814-add-no-follow-to-the-vote)
**Summary**
The adds no follow to page feedback are on articles. This will hopefully stop clicks from non human traffic.
> [DEV APPROVED] - 8814 Add nofollow to voting buttons

- features/money_manager.feature
- features/step_definitions/money_manager_steps.rb
- features/support/ui/pages/money_manager_show_all_advice_page.rb
- features/support/world/pages.rb
[TP Link](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/4771110243071511547&appConfig=eyJhY2lkIjoiRjk1Qzc3Njg4REFDNTUyNTBGODhGNTE5MEM5M0JCN0UiLCJhcHBDb250ZXh0Ijp7InByb2plY3RDb250ZXh0Ijp7Im5vIjpmYWxzZX0sInRlYW1Db250ZXh0Ijp7Im5vIjpmYWxzZX19fQ==)
**Summary**
This PR creates a feature spec for the TP Link card above. The logic is implemented in https://github.com/moneyadviceservice/universal_credit/pull/216.
**Checklist**
+ [ ] Tests passed.
+ [ ] Rubocop is passing for this PR (or any other lint like JShint).
+ [ ] Commit history reviewed (clear commit messages).
**N.B.** The test is failing because the universal credit PR has not been merged and so we cannot bump the version of UC yet. Once that has been merged we will add that …
> [DEV APPROVED] Creates feature spec for the show_all? flag on money manager/universal credit

- app/views/sitemap/robots.text.erb
simple change to robots.txt file to fix 
The Disallow statements are currently being ignored by bots because of the missing User-Agent: * declaration.
> [DEV APPROVED] update robots.txt file to add User-agent: *

- Gemfile
- Gemfile.lock
[TP card](https://moneyadviceservice.tpondemand.com/entity/9008-nty-18-wpcc-deploy-the-feature)
This PR includes the tax changes for the new financial year.
The wpcc 2.0.0 version includes the work done on this PR: https://github.com/moneyadviceservice/wpcc/pull/205
> Bump wpcc version to 2.0.0

- bower.json.erb
# Bumps yeast for bug ticket 9129
Bumps the version of yeast used for ticket [9129](https://moneyadviceservice.tpondemand.com/entity/9129-links-in-callout-boxes-on-my)
> Bumps yeast for bug ticket 9129

- app/assets/stylesheets/components/page_specific/home_beta/_central_search.scss
TP Ticket [8961](https://moneyadviceservice.tpondemand.com/entity/8961-hp-main-image-should-rest-directly)
On the current implementation of the new homepage beta, there is a white space between the lead image and the next page element - the green search box.
This PR ensures that the image rests on top of the central search box.  By removing a top margin.
| Desktop |
|-----------|
|![image](https://user-images.githubusercontent.com/13165846/39294948-f28003ae-4934-11e8-97bc-82f41d85e14e.png)|
| Mobile |
|--------|
|![image](https://user-images.githubusercontent.com/13165846/39294979-0a47763e-4935-11e8-9c75-2e120d8799ae.png)|
> 8961 - Removes top margin from the central search box

- app/assets/stylesheets/components/page_specific/home_beta/_tool_promo.scss
TP Ticket [8963](https://moneyadviceservice.tpondemand.com/entity/8963-hp-consistent-sizestyle-for-the-get)
The 'Get Started' links and the 'read more' links on the homepage are inconsistently sized.
This PR makes the 'Get Started' links match the 'Read more' links in size.
| Screenshot (Links highlighted in red) |
|------------|
|![image](https://user-images.githubusercontent.com/13165846/39295396-3c60ca70-4936-11e8-82a8-7d6f5e1fb446.png)|
> 8963 - Makes read more and get started links equal size

- app/assets/stylesheets/components/page_specific/home_beta/_information_guides.scss
- app/assets/stylesheets/components/page_specific/home_beta/_most_read.scss
- app/assets/stylesheets/components/page_specific/home_beta/_tool_promo.scss
- app/views/shared/home_beta/_information_guides.html.erb
- app/views/shared/home_beta/_tool_promos.html.erb
[TP8962](https://moneyadviceservice.tpondemand.com/entity/8962-hp-get-started-links-require-more)
[TP8962](https://moneyadviceservice.tpondemand.com/entity/8965-hp-make-the-whole-boxes-clickable)
-Moved the links to encompass the entire content in the boxes for info guides and most read.
-Updated styling on all to have consistent hover states on info guides, most read, and additionally tools.
-Also added a little fix to fix the issue with 'hover dead zones' where there was gaps in the clickable area between the link's child elements
> 8962 8965 linked boxes

- app/assets/stylesheets/components/page_specific/home_beta/_most_read.scss
- app/views/shared/home_beta/_most_read.html.erb
[TP9170](https://moneyadviceservice.tpondemand.com/entity/9170-hp-safari-image-width-doesnt-resize)
Added back in the width:100% styling for most read images that had been lost in homepage-hero branch due to different classes, fixing the bug where in Safari, if you load the page with the window fairly small and then resize it up, the images don't scale..
_Note: won't let me upload before and after pictures, please see [ticket](https://moneyadviceservice.tpondemand.com/entity/9170-hp-safari-image-width-doesnt-resize), after screenshot uploaded in comments_
> [DEV APPROVED] added back old code that ensures images scale correctly in safari

- app/assets/stylesheets/components/page_specific/home_beta/_leader.scss
- app/helpers/home_helper.rb
- app/views/shared/home_beta/_leader_text.html.erb
- config/locales/cy.yml
- config/locales/en.yml
**Target Process tickets**
[TP8969](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8969), [TP8970](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8970), [TP8971](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8971)
**Summary**
The rendering of the text via SVG over the leader image was displaying inconsistently in some browsers and devices. This was due to an inconsistent …
> [DEV APPROVED] TP: 8969/70/71, Comment: Updates positioning of SVG text

- Gemfile.lock
CVE-2018-3760 in sprockets 2.12.4 
Specially crafted requests can be used to access files that exist on the filesystem that is outside an application's root directory, when the Sprockets server is used in production.
Bump version to 2.12.5
> [DEV APPROVED] Upgrade sprockets gem, vulnerability in 2.12.4

- Gemfile
- Gemfile.lock
This PR bumps wpcc in line with [TP9256](https://moneyadviceservice.tpondemand.com/entity/9256-bug-wpcc-callout-overlap)
> wpcc version bump

- app/models/user.rb
- features/cassettes/CMS/get/api/TR/REC-html40/loose_dtd_json.yml
- features/step_definitions/change_password_steps.rb
- features/step_definitions/email_steps.rb
- features/step_definitions/sign_in_steps.rb
- features/support/ui/pages/change_password.rb
- features/support/world/pages.rb
- spec/models/user_spec.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9322-reset-password-token-is-invalid)
When a user follows the journey to reset their password, at the point where a new password is entered and submitted, the following error is displayed and the task can not be completed - 'Reset password token is invalid'.
After implementing the encryption PR #1948, the reset password token stopped working.
The reason is the overwrite of the `find_first_by_auth_conditions`
method on the user model. This method is used  by **Devise** for authentication and **_also for
the reset password token._** The original change to the method resulted in a search **only  by email**, hence searching by token was no longer working.
Making the `conditions` more general makes both scenarios work.
> Fix reset password token

- README.md
[TP 9412](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9412)
The `README` needs to be updated to have the `bundle install` correctly executed on a brand new OSX machine. The problem encountered has been documented in the ticket and is related to the `mysql@5.5` brew formula.
> [DEV APPROVED] - 9412 Update README to allow the `bundle install` phase pass on a brand new machine (dev)

- app/assets/javascripts/require_config.js.erb
[TP9414](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/4910826923597700395&appConfig=eyJhY2lkIjoiOUZDOTM4RDBCNEZGRERFMDRGQjZERDg1NTE5MTA1NzQifQ==&boardPopup=userstory/9414/silent)
This adds a reference to PACs in the frontend require_config for JS mounting
It is part of the work to set up the PACs project with all then necessary JavaScript requirements, which is in [PR4](https://github.com/moneyadviceservice/pacs/pull/4).
> [DEV APPROVED] TP: 9414, Comment: Adds reference to pacs in require_config 

- app/assets/javascripts/syndication/tools.js.coffee
- app/assets/javascripts/syndication/widget.js.coffee
[TP Card](https://moneyadviceservice.tpondemand.com/entity/9533-partner-tools-syndication-test-environments)
The tools.js was pointing always to partner tools production site.
There was a piece of code that always was returning undefined on tools.js:
```
if toolsConfig?
then "#{toolsConfig['syndication_url']}/#{toolpath}"
else "https://partner-tools.moneyadviceservice.org.uk/#{toolpath}"
if toolsConfig?
then toolURL = toolsConfig['syndication']['ga_iframe_url']
else toolURL = "https://partner-tools.moneyadviceservice.org.uk/partner_ga_iframe.html"
```
Above toolsConfig were never defined (ever even on git history!). 
So we actually implemented the tools config to have the default behaviour and search by environment.
**Unfortunately we had to hard code the envs because the client html is …
> [DEV APPROVED] - Make sure partner tools is loaded by each environment

- app/assets/stylesheets/components/common/_header.scss
- app/assets/stylesheets/components/common/_mas_logo.scss
[TP9321](https://moneyadviceservice.tpondemand.com/entity/9321-mas-logo-in-welsh-gets-cropped)
This PR tweaks the logo size so that it doesn't crop the Welsh logo
Please note, the screenshots look a bit of a hybrid as welsh wasn't working correctly locally, so I manually put the welsh logo into the english page to do this ticket. 
Before:
After:
> [DEV APPROVED] 9321 Tweaking logo size so welsh isn't cropped

- app/assets/stylesheets/components/common/_mas_logo.scss
[TP9321](https://moneyadviceservice.tpondemand.com/entity/9321-mas-logo-in-welsh-gets-cropped)
A bug was raised when the code for the ticket was pushed to staging https://github.com/moneyadviceservice/frontend/pull/1979
This PR addresses the comment in the tp ticket where the welsh logo overlapped with the buttons on mobile (320px)
> [DEV APPROVED] 9321 Welsh logo bug - mobile overlapping

- app/assets/javascripts/syndication/widget.js.coffee
[TP9686](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=bug/9686)
Partner tools currently do not display on IE. 
This appears to be because the [URL Web API](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#Browser_compatibility) used is not compatible with IE (all versions). 
This fix updates the JS to avoid using this. 
Testing is not easy since this fix needs to be deployed first but it can be done when this is on a Test environment by running a local page along the lines suggested in the comments in the TP ticket.
> Updates JS to avoid URL Web API, which is not compatible with IE

- Gemfile
- Gemfile.lock
> [DEV APPROVED] Remove validate-url gem

- config/initializers/instrumentation.rb
To assist with debugging Defaqto API requests in production, make some
additions to the Faraday log output.
- Add status code.
- Output body if request was unsuccessful.
> [DEV APPROVED] Add more data to Faraday instrumentation

- Gemfile
- Gemfile.lock
Additional issues have emerged with this engine in the time it's spent
waiting for a deploy to staging. Rolling back the version in frontend
for now while advice_plans is being fixed.
> Rollback advice_plans

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/search_results_controller.rb
- app/decorators/search_result_collection_decorator.rb
- app/helpers/search_results_helper.rb
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_0_hitsPerPage_10_query_Norris.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_0_hitsPerPage_10_query_money.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_0_hitsPerPage_10_query_tiger.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_1_hitsPerPage_10_query_money.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_32_hitsPerPage_10_query_money.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_33_hitsPerPage_10_query_money.yml
- features/search.feature
- features/step_definitions/search_page_steps.rb
- features/support/vcr.rb
- spec/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_0_hitsPerPage_10_query_Foobar.yml
- spec/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_0_hitsPerPage_10_query_How_to_budget_for_a_monthly_benefit_payment.yml
- spec/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_0_hitsPerPage_10_query_Sut_i_gyllidebu_ar_gyfer_taliad_budd-daliadau_misol.yml
- spec/decorators/search_result_collection_decorator_spec.rb
[TP Card](https://moneyadviceservice.tpondemand.com/entity/10263-frontend-update-site_search-to-020)
**Context**
- I would suggest to review by commit (cassettes noise in one commit, more info in commit messages)
- The [site_search](https://github.com/moneyadviceservice/site_search) Gem has been updated to be used in the FinCap site. The new version added a decorator, which takes care of adding +1 to the pages number (which are 0 indexed in the underlying Algolia Gem)
- This PR removes the collection decorator page adjustment
**Testing**
- Some cassettes had to be re-recorded as the index changed since they were first recorded (2016)
i.e Total number of pages dropped from 36 to 34   
- Search tested locally against the Alglia local-test app and looks ok:
---
Last …
> [DEV APPROVED] [10263] Upgrade site search to 0.2.0

- Gemfile
- Gemfile.lock
This pr bumps down the mortgage_calculator gem from 3.5 to 3.4.
Refer to the blocker on [TP 9827](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=userstory/9827). 
The requirement for different text was added when TP 9827 reached staging.
> Revert mortgage-calculator to 3.4

- Gemfile
- Gemfile.lock
Bump Dough to v5.35.0 and PACs to v3.4.0
> Bump Dough to v5.35.0 and PACs to v3.4.0

- Gemfile
- Gemfile.lock
[TP-10333](https://moneyadviceservice.tpondemand.com/entity/10333-test-to-remove-mas-assets-gem)
According to MAS Assets Readme, in order to use the gem in your project
you need to "require mas/shared" or "@import 'mas/shared'".
There is no reference at all to "mas/shared" within Frontend project,
so having green both unit and feature tests and the app starting
without issues when removing this dependency... I assume is safe to
just delete it from the project.
> [DEV APPROVED] TP-10333: Remove mas-assets requirement

- Gemfile
- Gemfile.lock
The source we were previously using for this gem was made private. This pr updates the source of the gem to the public repo.
We use this gem to provide encryption/decryption on top of OpenSSL.
> [DEV APPROVED] Update source of aes gem

- Gemfile
- Gemfile.lock
Update wpcc engine to 2.5 for [TP 10440](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&searchPopup=userstory/10440)
> Update wpcc version

- app/views/layouts/_base.html.erb
[TP-10472](https://moneyadviceservice.tpondemand.com/entity/10472-spike-investigate-pinterest-verification-process)
This is just to add the given code that will be manually checked by Pinterest support team member: 
> If the meta tag or file method isn't working for you, there is one alternative you can try. Temporarily add this tag to the source code anywhere on your website's homepage: aef390d29af3532d99f8cabb0e10bdaa
> Once you add the tag, email me to let me know, and I'll check your site's homepage for it. If it's there, I'll be able to confirm that you're the site owner and confirm your site for you. You can remove the tag after the verification is complete.
So we don't need to worry much about name/format as the code shows up and can be checked manually.
> [DEV APPROVED] [10472] Add metatag provided by Pinterest support team for verification

- app/views/layouts/_base.html.erb
Reverts moneyadviceservice/frontend#2117
As we finally successfully claimed MAS website in Pinterest and the authentication process was an one/off code, there is no need to keep it anymore in our codebase.
Related with: https://moneyadviceservice.tpondemand.com/entity/10472-spike-investigate-pinterest-verification-process
> Revert "[10472] Add metatag provided by Pinterest support team for verification"

- app/views/shared/_contact_panels.html.erb
[TP 10549](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=bug/10549/silent)
The PR fixes a second bug where the new chat window on the popup would open blank.
> [DEV APPROVED] 10549 - Fixed blank page in chat window

- Gemfile.lock
[TP](https://moneyadviceservice.tpondemand.com/entity/9610-broken-link-in-car-costs-calculator)
> Point to car_cost_tool 1.5.1

- app/controllers/amp_articles_controller.rb
[TP](https://moneyadviceservice.tpondemand.com/entity/10506-bug-welsh-amp-intermittent-404)
The controller for AMP articles uses I18n.locale, which isn't being
dynamically updated based on the request params. Use the locale param
directly.
> [DEV APPROVED] 10506 Fix locale switching on AMP pages

- app/assets/stylesheets/components/common/_cookie_message.scss
- app/views/shared/_footer_secondary.html.erb
- config/locales/cy.yml
- config/locales/en.yml
[TP10600](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/10600)
The work in this PR 
- updates the cookie consent message 
- replaces the close button with one that states that the user accepts the use of cookies on the site. 
Existing functionality remains unchanged. 
Current cookie message: 
Updated cookie message:
> [DEV APPROVED] 10600 update cookie consent message

- app/views/layouts/_base.html.erb
- config/application.rb
[TP10589](https://moneyadviceservice.tpondemand.com/entity/10589-update-gtm-tracking-code-snippet)
This change updates a previous update ([TP10537](https://moneyadviceservice.tpondemand.com/entity/10537-update-ab-testing-lessheadgreater-code-snippets)) to the A/B Testing code snippet that moved the site from Optimizely to  Google Optimize. Following this change it was recommended that we use a different ID, which is implemented here. The recommended ID is in fact the already-existing one for Google Tag Manager. 
**Current snippet:** 
**Updated snippet:**
> [DEV APPROVED] Updates A/B Testing GTM snippet

- app/views/categories/_content_items.html.erb
[TP 10677](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10677/silent)
**Background**
On the [tools and calculators page](https://www.moneyadviceservice.org.uk/en/categories/tools-and-calculators), a view all button is displayed for each category. For some of the categories, this button doesn't do or add anything, if it is clicked nothing additional is shown. 
**Solution**
Only display the view all button, if there are additional items to be displayed.
> [DEV APPROVED] Only show view all button if there are more items to view

- app/views/shared/_panel_webchat.html.erb
- features/footer.feature
[TP10756](https://maps.tpondemand.com/entity/10756-remove-additional-text-from-welsh-web)
Removes the text informs the user that webchat is not available in Welsh when in fact it is. Updates expect text in cucumber tests.
> 10756 remove welsh text

- app/views/shared/_panel_contact_us.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/footer.feature
[TP10733](https://maps.tpondemand.com/entity/10733-modify-call-us-contact-panel-to)
This PR aims to edit the "Call us" contact panel to the footer of the MAS website globally.  
The updated panel should include the option the send an email (opens in email client via 'mailto:' link) and it should mirror the changes made in RAD Consumer on [TP10755](https://maps.tpondemand.com/entity/10755-modify-call-us-contact-panel-to)
> [DEV_APPROVED] 10733 Update Call Us Contact Panel to Include Email Enquiries

- app/assets/javascripts/syndication/tools.js.coffee
[TP10981](https://maps.tpondemand.com/entity/10981-loan-calculator-no-default-height-causes)
This PR refers to problems arising from embedding the Loan Calculator tool on a web page. The issue became apparent when Jaguar Land Rover embedded this as one of four tools [here](https://wellbeing.jaguarlandrover.com/financial-wellbeing). 
The work in this PR assumes that the problem here is by embedding multiple tools on a page the functionality to dynamically resize the tools is lost, and they are displayed at the default size (if any) specified in the embed code. Since there is no such value in the code pertaining to the Loan Calculator this is not fully displayed when embedded in this scenario (see screenshot below). 
This change simply adds a default height and width, calculated to …
> [DEV APPROVED] Adds an explicit height to the Loan Calculator tool

- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/views/layouts/_application_shared.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_maps_banner.html.erb
- bower.json.erb
- config/locales/cy.yml
- config/locales/en.yml
- spec/views/header_search_box_spec.rb
[TP10975](https://maps.tpondemand.com/entity/10975-add-maps-brand-banner-to-mas)
This work adds a MAPS banner to the MAS site. There are two related PRs for this: the one in Yeast, [PR57](https://github.com/moneyadviceservice/yeast/pull/57), adds the styles to the markup that is contained here. For testing both need to be loaded locally. 
The banner is rendered in three different sizes: 
- Home page mobile
- Home page larger viewports
- All other pages
There is also variations on when the header is sticky on mobile versions and otherwise (mostly tool pages).
> [DEV APPROVED] 10975 maps banner

- config/locales/cy.yml
[TP11002](https://maps.tpondemand.com/entity/11002-broken-links-in-welsh-footer)
This PR fixes two broken links in the footer. See the TP ticket for the correct URLs.
> Updates broken links in footer

- app/views/layouts/error.html.erb
[TP11020](https://maps.tpondemand.com/entity/11020-add-maps-brand-banner-to-mas)
When the work was done to add the MAPS banner to the MAS core site the error page was not included. 
The work in this PR adds the banner to that page.
> [DEV APPROVED] Adds MAPS banner partial to error page

- app/views/layouts/pace.html.erb
- app/views/pace/_header.html.erb
[TP11012](https://maps.tpondemand.com/entity/11012-pace-set-up-page-template)
This sets up a basic template for the PACE pages by replacing the MAS header with a simplified version and retaining the existing footer. Viewable locally at: http://localhost:3000/en/pace
> Adds PACE-specific header

- app/views/shared/_panel_webchat.html.erb
- app/views/shared/_panel_whatsapp.html.erb
- bower.json.erb
[TP10734](https://maps.tpondemand.com/entity/10734-remove-whatsapp-contact-option-from-welsh)
This work updates the small-print text that is found on two fo the panels in the footer when viewing the site in Welsh.  The requirement is to move this text so that it is above the buttons and to make it bold. There is a further requirement to update the content of that text but that is out of the scope fo this work as it is CMS controlled. 
The work is in 2 PRs: 
- This one, which makes the markup change to alter the position
- [PR60](https://github.com/moneyadviceservice/yeast/pull/60) in Yeast that makes the style change to embolden the text and remove from English language rendering of footer. 
Current
Updated
> [DEV APPROVED] Moves location of smallprint on Whatsapp and Webchat panels

- app/assets/stylesheets/layout/page_specific/_pace.scss
- app/views/pace/_faqs.html.erb
- app/views/pace/_referred.html.erb
- config/locales/pace.en.yml
[TP11044](https://maps.tpondemand.com/entity/11044-pace-add-page-behaviour-for-the)
This work adds the Dough Collapsable component to the FAQs and Referral sections of the page to add collapse/expand behaviours. These are all fully expanded in a non-JavaScript environment and all closed otherwise on initial page load. 
**FAQs, collapsed**
**FAQs, expanded**
**Referrals, collapsed**
**Referrals, expanded**
> 11044 pace page behaviour

- app/assets/images/pace/adviser_arrow.svg
- app/assets/stylesheets/layout/page_specific/_pace.scss
- app/views/layouts/pace.html.erb
- app/views/pace/_advice.html.erb
- app/views/pace/_adviser.html.erb
- app/views/pace/_faqs.html.erb
- app/views/pace/_header.html.erb
- app/views/pace/_help.html.erb
- app/views/pace/_introduction.html.erb
- app/views/pace/_nav.html.erb
- app/views/pace/_online_advice.html.erb
- app/views/pace/_organisations.html.erb
- app/views/pace/_privacy.html.erb
- app/views/pace/_wellbeing.html.erb
- app/views/pace/show.html.erb
- config/locales/pace.en.yml
[TP11045](https://maps.tpondemand.com/entity/11045-pace-create-markup-and-styles-for)
This work adds responsive styles to the PACE landing page to render the layout at larger viewport sizes. 
The design for this can be viewed [here](https://app.zeplin.io/project/5e15b2a4bb77ef7e89ba6be6/screen/5e15b2fdc022025335237932). 
If this is pulled to a local environment it is viewable at localhost:xxxx/en/pace
> 11045 pace landing page desktop

- app/views/pace/_faqs.html.erb
- app/views/pace/_nav.html.erb
- app/views/pace/_online_advice.html.erb
- app/views/pace/_organisations.html.erb
- app/views/pace/_referred.html.erb
[TP11111](https://maps.tpondemand.com/entity/11111-pace-microsite-tagging)
This work adds unique identifiers to a number of elements on the page so that user engagement with them can be tracked. The elements requiring tracking are: 
- Each of the expandable FAQs headers
- The header of the expandable "How referred you" section
- Each of the boxes in the "The advice organisations that will help you" section
- Each of the "Get online advice" Call to Actions
> [DEV APPROVED] 11111 pace tagging

- app/views/sitemap/robots.text.erb
[TP11015](https://maps.tpondemand.com/entity/11015-pace-add-privacy-policy-page-link)
This card is concerned with the Privacy Policy page, though most of the expectations within it have been met in previous cards:
- the link to the Privacy Policy page has already been added
- the template for the page itself has already been set up
So this work confines itself to the aspect of the Acceptance Criteria that relates to the requirement that this page is not logged by Search Engines. 
This is done by adding the URL to the robots.txt file, listing both `en` and `cy` versions: both will be legitimate URLs even though there is no Welsh language content at this time.
> [DEV APPROVED] Adds the PACE privacy URL to the robots.txt file 

- app/views/pace/_privacy.html.erb
- config/locales/pace.en.yml
- config/routes.rb
[TP11118](https://maps.tpondemand.com/entity/11118-pace-add-mas-url-for-pace)
The final URL for the PACE microsite has now been decided upon so this work updates that from `/pace` to `/moneyadvisernetwork`. 
Additionally there is a change to add the URL to the translation file to facilitate easier re-use.
The final URLs will now be 
- https://www.moneyadviceservice.org.uk/en/moneyadvisernetwork
- https://www.moneyadviceservice.org.uk/en/moneyadvisernetwork/privacy
> [DEV APPROVED] Updates PACE URL

- app/views/pace/privacy.html.erb
- app/views/pace/show.html.erb
- config/locales/pace.en.yml
[TP11248](https://maps.tpondemand.com/entity/11248-pace-change-the-tab-bar-title)
This is a simple change to update the the `<title>` tag from 'PACE' to 'Money Adviser Network' on both the landing and privacy pages. It also adds the title text to the translation file for reusability.
> [DEV APPROVED] 11248 pace update title tag

- app/assets/stylesheets/layout/page_specific/_pace.scss
[TP11240](https://maps.tpondemand.com/entity/11240-pace-logos-on-who-referred-you)
This work updates the display of the "Who referred you?" section. Some styling has been broken in the development process leading to problems with the display of the logos in this section:
- they display against a grey, rather than white, background
- the horizontal spacing across the whole section is wrongly rendered against the design.
The stylesheet has been updated to improve this. 
**Current:** 
**Updated:**
> [DEV APPROVED] Updates styles to display logos in referred section

- app/views/pace/show.html.erb
[TP11280](https://maps.tpondemand.com/entity/11280-pace-remove-who-referred-you-section)
This work temporarily removes the section headed 'Who referred you'. Since this will be restored to the page at the earliest opportunity this change simply comments out a section of the main view so that the partial for this section is not rendered. 
**On production:** 
**Updated in this PR:**
> [DEV APPROVED] Temporarily removes 'referred' section

- Gemfile
- Gemfile.lock
- app/assets/javascripts/require_config.js.erb
- app/controllers/application_controller.rb
- app/views/layouts/_application_shared.html.erb
- app/views/shared/_covid_banner.erb
- bower.json.erb
- config/locales/cy.yml
- config/locales/en.yml
[TP11363](https://maps.tpondemand.com/entity/11363-sticky-banner-on-mas-website-for)
This work adds a banner to direct users to our articles on Coronavirus. 
There are three PRs that make up the implementation of this component: 
- PR2201 in frontend (this PR) that provides the content and markup for the banner, as well as the Rails functionality to render the component only when this is not recorded in a Cookie as having been previously dismissed, and the reference to the associated Dough component. 
- [PR61](https://github.com/moneyadviceservice/yeast/pull/61) in yeast that provides the styles for the component, and which will be shared with other repos, such as RAD. 
- [PR338](https://github.com/moneyadviceservice/dough/pull/338) in dough that provides the JavaScript component and …
> 11363 sticky banner coronavirus info

- config/locales/cy.yml
- config/locales/en.yml
[TP11380](https://maps.tpondemand.com/entity/11380-add-ability-to-track-covid-banner)
The changes in this PR adds the class `covid_banner__link` to the link on the Covid banner. This is in order to facilitate tracking on this element.
> [DEV APPROVED] Adds class 'covid_banner__link' to covid banner link

- app/views/layouts/_base.html.erb
[TP11381](https://maps.tpondemand.com/entity/11381-dough-not-initialised-on-some-mas)
- This allows all JS to load as expected, including on 'empty templates'.
- This flag is described in the section [Consuming the front-end without having to manually import dependencies](https://github.com/moneyadviceservice/frontend#consuming-the-front-end-without-having-to-manually-import-dependencies) of the README.
- The tools that are the subject of [TP11381](https://maps.tpondemand.com/entity/11381-dough-not-initialised-on-some-mas) were included in this flag and were badly affected by it so the decision was made, as discussed in that card, to delete the flag in this instance.
> [DEV APPROVED] Removes flag 'hide_elements_irrelevant_for_third_parties' from base view

- Gemfile
- Gemfile.lock
- app/views/shared/_webchat_popup.html.erb
- config/locales/cy.yml
- config/locales/en.yml
[TP11393](https://maps.tpondemand.com/entity/11393-add-coronavirus-to-dropdown-option-on)
These changes add a Coronavirus option to the floating WebChat dropdown dropdown. 
The accompanying PR in Dough ([PR339](https://github.com/moneyadviceservice/dough/pull/339)) provides the logic to show the WhatsApp link when the Coronavirus option is selected.
> [DEV APPROVED] 11393 chat add coronavirus option

- app/views/layouts/_base.html.erb
- we need to restore this while a third party agency makes updates to their code
- it can be reinstated after that
This is to temporarily revert the work in [TP11381](https://maps.tpondemand.com/entity/11381-dough-not-initialised-on-some-mas)
> Reverts previous commit to remove conditional flag around script

- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/assets/stylesheets/components/common/_no-js_nav.scss
- app/assets/stylesheets/components/page_specific/_floating_chat.scss
- app/views/layouts/_application_shared.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_maps_banner.html.erb
- bower.json.erb
[TP11381](https://maps.tpondemand.com/entity/11381-dough-not-initialised-on-some-mas)
There are 2 PRs in this piece of work: 
- PR2212 on Frontend (this one)
- [PR62](https://github.com/moneyadviceservice/yeast/pull/62) on Yeast
It makes some small changes to our CSS to deal with issues that have become evident where third party users are loading our "empty template" to create content on the MAS estate.
There are a number of problems on the two tool pages this card caused by the usual MAS JavaScript being blocked and a number of page components break, specifically: 
- The Search Box has no means of clearing the input.
- The Navigation on desktop functions with CSS rather than JavaScript. The JavaScript provides a slightly enhanced experience as well as a number of accessibility features. …
> [DEV APPROVED] 11381 js missing

- Gemfile
- Gemfile.lock
[TP11416](https://maps.tpondemand.com/entity/11416-redundancy-pay-calculator-northern-ireland-update)
> Updates version of action_plans repo to 5.5.0 for TP11416

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/assets/stylesheets/components/common/_no-js_nav.scss
- app/views/shared/_global_nav.html.erb
- app/views/shared/_mobile_nav.html.erb
- bower.json.erb
- spec/javascripts/fixtures/GlobalNav.html
- spec/javascripts/tests/GlobalNav_spec.js
[TP11424](https://maps.tpondemand.com/entity/11424-global-navigation-no-js-improvement)
There are 2 PRs for this piece of work: 
- [PR63](https://github.com/moneyadviceservice/yeast/pull/63) in yeast
- PR2213 in frontend (this one)
This work makes some small improvements to the Global Navigation arising from the work carried out to fix issues associated with our empty template in [TP11381](https://maps.tpondemand.com/entity/11381-dough-not-initialised-on-some-mas). It updates the display of the component in desktop viewports when: 
- JavaScript does not load at all on the page
- JavaScript loads on the page but the component is not initialised
- the component is fully initialised
It also deals with the state of the component in transition between those states that gives a more …
> 11424 global nav no js improvement

- app/assets/stylesheets/_print.scss
[TP11591](https://maps.tpondemand.com/entity/11591-mas-core-site-update-general-print)
This work adds three elements to the list of components to be excluded from the print stylesheet: 
- MAPS banner
- Floating mobile Webchat
- Covid banner
Whilst this is a general task that needs to be done, this card is also part of the work to add a print stylesheet to the Money Navigator Tool (see [TP11446](https://maps.tpondemand.com/entity/11446-moneynavigator-add-print-option-to-results)).
> Excludes unnecessary components from general print stylesheet

- app/assets/javascripts/components/MoneyNavigatorResults.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
- app/views/money_navigator_tool/results.html.erb
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
- spec/javascripts/fixtures/MoneyNavigatorResults.html
- spec/javascripts/tests/MoneyNavigatorResults_spec.js
[TP11446](https://maps.tpondemand.com/entity/11446-moneynavigator-add-print-option-to-results)
This work adds the functionality to allow the user to print the contents of the results page once they have used the tool.
The design on which this is based is [here](https://4zy55q.axshare.com/#id=8c2jys&p=results_page&g=12&view=default). 
The URL for the tool on frontend is `/en/tools/money-navigator-tool`. 
There already exists a site-wide print style-sheet; this work makes a minor update to that and adds more specific styles for this tool.
> Money navigator results add print option

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- spec/javascripts/fixtures/MoneyNavigatorQuestions.html
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP11584](https://maps.tpondemand.com/entity/11584-money-navigator-logic-issue-with-employed)
This work adds the display logic to allow customised journeys to be made. 
For this release we wish to skip certain questions on "Continue" depending on which response is selected for Q1 ("What is your employment status") according to the logic below. The same route should be followed on "Back" and should be changed if the user updates their selection on Q1. 
```
If user answers      | Go to
A1 ("Employed")      | Q2 ("Are you at risk ...?") then Q4 ("How would you describe  ...?")
A2 ("Self-employed") | Q3 ("If you are self-employed ...?") then Q4 ("How would you describe  ...?")
A3 ("Unemployed")    | Q4 ("How would you describe  ...?")
A4 ("Retired")       | Q4 ("How would you describe  ...?") …
```
> 11584 money navigator journey logic

- app/views/money_navigator_tool/questionnaire.html.erb
- app/views/money_navigator_tool/results.html.erb
- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
- config/routes.rb
This PR includes changes for [TP11469](https://maps.tpondemand.com/entity/11469-money-navigator-welsh-translation-files) & [TP11629](https://maps.tpondemand.com/entity/11629-remove-note-on-q6)
A new yaml file was created to accommodate the new Welsh translations implemented here. The note on question 6 was now removed from the english translations and kept the note functionality in the view. Other minor bugs regarding dynamic text were also fixed.
The existing redirect that was preveting access to the Welsh version of the tool was also removed from `routes.rb`.
**Note:** The text on the buttons is not dynamic as of this PR, welsh translations for them are now in place and the functionality will be implemented with [PR2233](https://github.com/moneyadviceservice/frontend/pull/2233)
> 11469 - 11629 - Welsh Translation Files

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
- spec/javascripts/fixtures/MoneyNavigatorQuestions.html
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP11567](https://maps.tpondemand.com/entity/11567-money-navigator-enhanced-questions-ux-updates)
This work enhances the UI for some of the questions in the tool. It effects questions that are of the format that allows the user to select from multiple options, as shown below. This requires the user to deselect the 'No' option before the others are enabled, an experience that was proving confusing for many.
The UI is enhanced as described and illustrated below
- moves the 'No' option to the top of the section, directly below the question and above the text 'Choose all that apply'
- inserts a new option 'Yes' which is by default the selected option
- disables the 'Continue' button as the default state for the question
- adds logic to 
- display the 'Yes' and 'No' options as mutually …
> 11567 money navigator multiple questions enhanced ux

- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
[TP11626](https://maps.tpondemand.com/entity/11626-money-navigator-urgent-ctas-improvements)
When the Money Navigator tool was first released we dealt with the layout of the `Urgent Actions` section on the results page by tightly coupling the styles for the eight possible variations of the content of these sections with their content. This led to a very brittle layout whereby small changes in content could (and did) break the layout. 
This work relies on the addition of some class names to the markup in the CMS that makes the CSS able to render the correct layout in a more general way and dispenses with the selectors that are overly specific. 
The layout of these sections should remain largely unchanged as a result of this work. 
An example of such a callout is shown tin the screenshot …
> [TP11626] Updates CSS on Urgent Actions for amended markup from CMS

- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
[TP11649](https://maps.tpondemand.com/entity/11649-typo-on-landing-page-in-welsh)
This work corrects a typographical error on the landing page of the Money Navigator tool. The current and updated content is shown below. 
**Current**
**Updated**
> Corrects type in Landing page copy

- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
- app/views/money_navigator_tool/results.html.erb
- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
[TP11559](https://maps.tpondemand.com/entity/11559-money-navigator-ux-improvement-on-urgent)
This work updates the heading of the 'Urgent Actions' section of the Money Navigator results page for increased prominence. 
**Current**
**Updated**
> 11559 money navigator results ux urgent cta

- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
[TP11521](https://maps.tpondemand.com/entity/11521-money-navigator-text-changes-to-results)
This work makes several small text changes to the Results page. 
Many of these are in content that is dependant on the journey the user takes through the tool and appear in the overlay section. 
There is also a further change to the button at the bottom of the tool that allows the user to go through the questions again. This appears in all instances and is shown below. 
**Current (English)**
**Current (Welsh)**
**Updated (English)**
**Updated (Welsh)**
> 11521 money navigator results headings changes

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/common/_global_subnav.scss
[TP-11691](https://maps.tpondemand.com/entity/11691-bug-dalt-current-location-warning-message)
This update moves a `is-hidden` style in the global navigation to make it more specific to that component. This has recently been updated to make it less generic which in turn caused a problem with the error message that is shown on the Debt Advice Locator when the user's device is unable to get a location. 
The `is-hidden` style that is used both here and on the DAL tool is now a new style created in Dough. 
The change in the DAL repo that was required to be made is in [PR172](https://github.com/moneyadviceservice/debt-advice-locator/pull/172). 
The change in Dough that was required to be made is in [PR 340](https://github.com/moneyadviceservice/dough/pull/340).
> [TP-11691] Updates global nav style to fix knock-on problem on DAL

- app/middleware/partner_tools_cookies.rb
- config/application.rb
- spec/middleware/partner_tools_cookies_spec.rb
Using middleware instead of overriding `set_cookie_header` in `/action_dispatch/middleware/cookies.rb`. This way we can set it by default for syndicated tools only and the other parts we leave as is.
> [TP-11721] Add SameSite=None whenever we have X-Syndicated-Tool header

- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
[TP-11682](https://maps.tpondemand.com/entity/11682-money-navigator-technical-debt-fix-small)
This work fixes some small UI issues on the Money Navigator Questions page. These concern the `Continue` and `Back` buttons as they render on smaller viewports (see screenshots below). The problem is that their common container is responding wrongly to the viewport width. The solution is to change the width of the container at a wider breakpoint to allow the buttons to display at the same width as other elements.
> [TP-11682] Fixes some small UI inconsistencies

- app/views/money_navigator_tool/questionnaire.html.erb
- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
[TP-11681](https://maps.tpondemand.com/entity/11681-money-navigator-technical-debt-improve-the)
This is part of the Technical Debt arising from the work on the Money Navigator tool.
It refactors the view that generates the markup for the Questions page in order to remove an unnecessary loop through the response values. 
Originally this was necessary in order to render the value that would be checked by default as the first value of the list of responses to each question. We subsequently added a `sort_order` value that determined this ordering of responses. As a consequence of this the refactoring in this PR was made possible in order to cut out unnecessary code from the view.
> [TP-11681] Refactors Questions view to remove unnecessary loop

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP-11680](https://maps.tpondemand.com/entity/11680-money-navigator-technical-debt-fix-failing)
This is part of the Technical Debt arising from the work on the Money Navigator tool. It fixes a Unit Test that was broken on the deployed version of the tool.
The test checks for the display state of the banner that appears at the start of the questions (see screenshot below) and is only required to be shown for the first question. 
The problem was that the test runner was unable to locate the element in the fixture because it is located outside of the component under test. This change makes the element available to the test. 
It also makes the element location within the DOM more specific in the component itself. That change is made more for consistency than necessity.
> [TP-11680] Fixes failing Unit test in `MoneyNavigatorQuestions_spec.js`

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
- app/views/money_navigator_tool/questionnaire.html.erb
- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
- spec/javascripts/fixtures/MoneyNavigatorQuestions.html
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP11590](https://maps.tpondemand.com/entity/11590-money-navigator-enhanced-questions-ux-updates)
This work enhances the UX of a particular subset of questions by creating a generic `Grouped Questions` element. This updates the DOM fairly substantially for any instances of this subset of question by 
- grouping together all responses except the default one and removing those from the view
- adding new `control` options that show/hide the grouped responses when clicked
The initial state of the question as it currently exists and in its updated form is displayed in the screenshots below. 
**Current**
**Updated**
Logic is added to this initial state to allow the grouped responses to be shown as appropriate, as shown below. 
**On clicking `No, but I'm worried ...`**
**On clicking `Yes ...`** …
> 11590 money navigator grouped questions

- app/assets/javascripts/application.js
- app/assets/javascripts/modules/mas_collapsable.js
**Note: There are quite a lot of lines changes in this PR due to linting of both the modified files.**
[TP11487](https://maps.tpondemand.com/entity/11487-search-bar-open-by-default-on)
This PR aims to hide the search bar on a mobile view. To achieve this, a new default was implemented in the existing `Collapsible` module which was implemented to the search bar.
Other elements using this module such as the [Debt Campaign Companies](https://www.moneyadviceservice.org.uk/en/categories/debt-and-borrowing) view all button seem to be working as normal.
Karma tests are passing.
> 11487 - Search bar open by default on mobile site

- app/views/money_navigator_tool/questionnaire.html.erb
[TP11594](https://maps.tpondemand.com/entity/11594-money-navigator-error-anchor-links-dont)
This work addresses a bug in the Money Manager tool whereby any validation errors that are caught server-side are not properly reported to the user. The main effect of this is that the tool correctly displays a generic message but the links within that do not take the user to the appropriate question and that question is not highlighted as containing an error. 
**Example: the message above is displayed but the link `Q12 can't be blank` does not take the user to the question containing the error.** 
This is caused by an incomplete implementation of the Dough Form Builder methods. Specifically we are missing the required `f.form_row` and `f.errors_for` tags which display the question with an …
> [DEV APPROVED] Adds `f.errors_for` & `f.form_row` tags

- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP11686](https://maps.tpondemand.com/entity/11686-money-navigator-technical-debt-improve-code)
This work aims to tidy up the Unit Tests associated with the Money Navigator Questions page component. The TP card lists a number of potential improvements to these tests but on further inspection I felt that the only tidying required was to remove the test for the `back` button in the `_setUpGroupedQuestions` method as that was already added and tested in the `_updateDOM` method.
> [TP-11686] Money-navigator_Improve-Questions-JS-Tests

- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
[TP11798](https://maps.tpondemand.com/entity/11798-update-q10-on-money-navigator-tool)
The work in this PR makes some changes to one of the questions to bring it into line with some criteria set by  StepChange. It updates the copy of Question 10 (which currently reads "Have you fallen behind or agreed a payment break on credit commitments or priority household bills since 28th February 2020?") and deletes one fo the options from the response. 
**Existing (production)**
**Updates in this PR**
> 11798 money navigator step change update q10

- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
- app/views/money_navigator_tool/results.html.erb
[TP11561](https://maps.tpondemand.com/entity/11561-review-font-sizes-in-action-callout)
There are a few inconsistencies in the rendering of text on the Results page of the Money Navigator tool when the user opens the overlays to view content. This is caused by the content being fetched from the CMS and thereby missing styles that would be available in the context of an article page. This work adds the missing styles to the Money Navigator stylesheet so that the display is consistent with the rest of the site.
Additionally, the overlay is updated to present its content within an `<article>` tag, which allows the content to be rendered more semantically and thereby better in terms of accessibility. 
The main visual differences are summarised below. 
The overlay heading becomes an `<h1>` …
> Money navigator, font inconsistencies on the Results page overlays

- Gemfile
- Gemfile.lock
This addresses the issue of failing tests within our preview CI builds.
This was introduced when we accidentally upgraded FactoryBot to 5.2.0, from 4.10.0
The change pins FactoryBot to the previous version, so that we only update FactoryBot when we're ready to update the factory files.
The upgrade of FactoryBot happened here: https://github.com/moneyadviceservice/frontend/commit/fa628fa8be9cb4181c7ea5520a1977047c15d178#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR508
> [Bugfix] Resolve broken tests in preview

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
- app/views/money_navigator_tool/questionnaire.html.erb
- spec/javascripts/fixtures/MoneyNavigatorQuestions.html
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP-11667](https://maps.tpondemand.com/entity/11667-money-navigator-accessibility-on-back-button)
This work updates the logic that deals with the display of individual questions on the Money Navigator tool as the user navigates through the questions by keyboard via the `back` button. It ensures that focus is moved to the top of the previous question so that the flow for the keyboard user remains intuitive.
It also adds a Unit Tests for the new functionality which in turn required an update to the existing tests for the component because a clash occurred with other tests when trying to obtain a value for `document.activeElement`. This update in turn required a small change in an existing test. All now run OK. 
| When the back button on a question is activated | Focus is moved to the first …
> TP-11667 Money Navigator A11Y back button

- app/assets/stylesheets/layout/page_specific/_money_navigator_landing.scss
- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
[TP-11923](https://maps.tpondemand.com/restui/board.aspx?#page=userstory/11923&appConfig=eyJhY2lkIjoiQTYyMEM3NTQ2MEJFN0E2NDk2Qzg0RDdERjcwNzkyRDAifQ==)
This work makes some simple updates to the CSS for the Landing and Results pages of the Money Navigator tool to ensure that all links within these pages that appear within block of text are rendered with an underline style. 
There is a reference in the TP Card for this work to the Cookies message. This is covered in a card ([TP-11958](https://maps.tpondemand.com/entity/11958-link-on-cookie-message-identified-only)) in the Feature for A11Y work on the main MAS site ([TP-11852](https://maps.tpondemand.com/entity/11852-mas-accessibility-fixes-post-audit)). 
Examples of links covered in this work. 
| …
> Tp 11923 money navigator a11 y links

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP-11822](https://maps.tpondemand.com/entity/11822-money-navigator-focus-styles-on-grouped)
This work improves the experience for a keyboard user on the enhanced UI for the 2 stage question ("Are you behind with rent or mortgage payments?"). This currently does not properly display focus styles and breaks badly on the second stage (see screenshots below). 
| Initial stage | Second stage |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6080548/106499067-04aae200-64b8-11eb-9571-eb4a5f6615fb.png) | ![image](https://user-images.githubusercontent.com/6080548/106499139-1ee4c000-64b8-11eb-9c40-811868830dd2.png) |
The solution is to refactor the markup a little to aid the natural keyboard navigation and to dynamically set focus styles on keyboard events to allow navigation by …
> 11822 money navigator grouped questions focus issues

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
- app/views/money_navigator_tool/questionnaire.html.erb
- spec/javascripts/fixtures/MoneyNavigatorQuestions.html
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP-11967](https://maps.tpondemand.com/entity/11967-money-navigator-a11y-question-3-options)
In a previous change to the UI on the question "If you are self-employed, do you know what your monthly income is now?" (accessed only by users who have previously indicated that their employment status is self-employed) we removed the option "I am not self employed" from the display so avoid slightly contradictory messaging. Because that option remains checked by default this causes a scenario whereby a keyboard user is unable to navigate to the inputs that remain displayed.
The agreed solution is to set a checked state on the next sibling of any input that is both checked by default and hidden. 
| The input that is checked by default is hidden | This means the remaining inputs cannot be accessed …
> Tp 11967 money navigator keyboard nav

- app/views/pace/_footer.html.erb
- app/views/shared/_footer_primary.html.erb
[TP11966](https://maps.tpondemand.com/entity/11966-broken-link-on-clear-english-standard)
This change updates a link in the footer that is currently leading to a 404 page. The link is for the Clear English Standard accreditation and appears in two locations within the MAS site: 
- the [MAS footer](https://www.moneyadviceservice.org.uk/en)
- the [PACE footer](https://www.moneyadviceservice.org.uk/en/moneyadvisernetwork)
and is set on the organisation's logo (see below).
> [DEV APPROVED] 11966 clear english standard broken link

- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
[TP11971](https://maps.tpondemand.com/entity/11971-update-idd-link-on-pensions-tools)
This change updates the URL associated with the link to the new investment pathways (income drawdown) tool. This appears in two places on the page (see screenshots). 
| In the section headed "Your options" | In the section headed "Retirement income choices" |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6080548/107039278-94e96f80-67b5-11eb-9db6-e0f40ce7db48.png) | ![image](https://user-images.githubusercontent.com/6080548/107039304-9f0b6e00-67b5-11eb-94ab-3ccb79ca36fc.png) |
> [DEV APPROVED] 11971 update idd link

- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
[TP11992](https://maps.tpondemand.com/entity/11992-update-idd-link-text-on-pensions)
This work updates the text for the link to the new Investment Pathways Options tool from "Understand and compare income drawdown tool / Offeryn deall a chymharu tynnu incwm i lawr" to "Understand and compare your investment pathway options / Deall a chymharu eich opsiynau llwybr buddsoddi". 
This appears twice on the page, under the following headings, in both English and Welsh languages: 
- Your options / Eich opsiynau
- Retirement income choices / Dewisiadau incwm ymddeol
| | Production | This PR |
| --- | --- | --- |
| English | ![image](https://user-images.githubusercontent.com/6080548/107380098-7a7d0200-6ae5-11eb-88fb-66cb5b1a396f.png) | ![image](https://user-images.githubusercontent.com/6080548/10738 …
> TP-11992, Updates text for Investment Pathway link

- app/assets/javascripts/modules/mas_cookieController.js
- app/assets/javascripts/translations/cy.js
- app/assets/javascripts/translations/en.js
- app/assets/stylesheets/components/common/_cookie_controller.scss
- app/views/layouts/_base.html.erb
- app/views/shared/_cookie_message.erb
- app/views/shared/_footer_secondary.html.erb
- features/chat.feature
- features/cookie_disclosure.feature
[TP-12012](https://maps.tpondemand.com/entity/12012-mas-cookie-banner-changes)
This work removes the current cookie implementation on MAS and replaces it with a third party solution. The steps taken to do this are: 
- Adds the script that calls the Civic CDN to the site <head> tag
- Adds a new MAS module to implement the Civic component
- Adds a stylesheet for the component to apply MAS styles
There remains some work still to do and this will be logged as separate Technical Debt tasks: 
- Write unit tests for module
- Fully remove the current cookie implementation
- Fix the issue identified with the locale - the plan was to use the existing MAS i18n module but this is not working correctly so a temporary solution has been implemented here. 
- Make some updates for a11y: although the …
> 12012 civic cookie implementation

- config/initializers/assets.rb
This is a small update to [PR2312](https://github.com/moneyadviceservice/frontend/pull/2312) to fix a problem with the assets pipeline configuration
> [TP-12012] Updates assets pipeline for mas_cookieController

- app/assets/javascripts/modules/mas_cookieController.js
[TP-12186](https://maps.tpondemand.com/entity/12186-bug-civic-cookie-module-breaks-redundancy)
This makes a small addition to the recently implemented cookie module to add an array of necessary cookies and to include in that a cookie that is necessary for the Redundancy Pay Calculator to function correctly.
> Adds necessary cookies array to module

- Gemfile
- Gemfile.lock
[TP-12213](https://maps.tpondemand.com/entity/12213-replace-link-on-safari-message-for)
This PR accompanies [PR343](https://github.com/moneyadviceservice/dough/pull/343) on Dough to replace a link added in [TP-11920](https://maps.tpondemand.com/entity/11920-credit-card-calculator-implement-the-storage). 
The change contained here deploys that change in Dough onto the Credit Card Calculator.
> 12213 third party cookies update link

- app/assets/javascripts/modules/mas_cookieController.js
[TP-12241](https://maps.tpondemand.com/entity/12241-bug-civic-cookie-module-breaks-informizely)
This work addresses a problem we have been encountering with the Informizely survey panel. This (according to our analytics data) is not consistently appearing on the site. The problem seems to be that Civic, the cookie control module we introduced recently, requires some cookies to be set and these are being blocked by Civic. Since the survey form is considered to be an essential part of the site the solution for this is to add the Informizely cookies to the 'necessaryCookies' object in Civic.
This PR reflects this change.
> Updates list of necessary cookies to add informizely

- app/assets/javascripts/modules/mas_cookieController.js
[TP-12233](https://maps.tpondemand.com/entity/12233-dalt-search-by-town-not-working)
This adds a reference to the cookie `__zjc*` to the Civic `necessaryCookies` array. 
This is an attempt to fix a problem on the Debt Advice Locator whereby the Search feature sometimes fails. It seems that this cookie is being set to expire immediately by a script that is being injected into the DOM. Although the cause of this is not clear it seems likely that it is because this cookie is not allowed by the Civic implementation. 
This may not fix the problem but we have agreed to try this to observe the effect on this tool in the live environment.
> [TP-12233] Applies fix for DAL search by town not working

- Gemfile
- Gemfile.lock
[TP-12016](https://maps.tpondemand.com/entity/12016-redundancy-pay-calculator-ye-updates-calculations)
Update Rates
Update JSA
Update Age calculation to use .floor instead of .round
Update test suite
Fix rubocop version
> Update Action Plans for YE-2021

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/_print.scss
- app/views/layouts/_application_shared.html.erb
- app/views/layouts/error.html.erb
- app/views/layouts/pace.html.erb
- app/views/shared/_header.html.erb
- app/views/shared/_mh_banner.html.erb
- bower.json.erb
- config/locales/cy.yml
- config/locales/en.yml
[TP-12490](https://maps.tpondemand.com/entity/12490-moneyhelper-coming-soon-banner-on-mas)
This work adds a "Money Helper Coming Soon" banner to the MAS site that replaces the existing MAPS banner, to display as the screenshots below.
The styles are mostly on Yeast so that they can be shared across projects so there is an accompanying PR for the same piece of work at [PR65](https://github.com/moneyadviceservice/yeast/pull/65)
> 12490 money helper banner

- app/models/user.rb
- config/initializers/warden_hooks.rb
- spec/controllers/sessions_controller_spec.rb
- spec/models/user_spec.rb
[TP-12090](https://maps.tpondemand.com/entity/12090-email-feature-does-not-work)
CRM is no longer in use and contains no valid information
DelayedJob failed to send emails when attempting to fetch user information using Cream
Remove ActiveRecord hooks to communicate with Cream when user created/updated
Relevant tests
> TP-12090 Remove Cream 

- config/locales/cy.yml
- config/locales/en.yml
[TP-12596](https://maps.tpondemand.com/entity/12596-registration-page-open-links-in-a)
This adds the `target` attribute to the `Terms and Conditions` and `Privacy Policy` links on the registration page and sets this to `_blank` to allow these links to open in new tabs.
> Adds `target="_blank"` to links

- app/assets/javascripts/components/MoneyNavigatorResults.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
- spec/javascripts/fixtures/MoneyNavigatorResults.html
- spec/javascripts/tests/MoneyNavigatorResults_spec.js
[TP-12553](https://maps.tpondemand.com/entity/12553-money-navigator-unable-to-fully-scroll)
This work addresses the problem on iOS devices that are unable to switch between scrolling contexts when rendering content within an iFrame. This is specific to the content in expandable sections on the results page of the money Navigator tool, activated by clicking on the headers such as "Getting back on track after a severe income drop" shown below. 
The solution adopted here is to dynamically resize the body element when the content is expanded so that it does not need to be scrolled. With this in place users of devices affected do not need to change their scrolling context and area able to view the full content. 
It is not a perfect solution and some other issues are raised by it: 
- the …
> 12553 money navigator scroll on mobile

- test.sh
This is due to our environments having a lesser glibc version.
> Force builds for Nokogiri

- package.json
- spec/javascripts/karma.conf.js
We've had a weird build failure due to karma specs not being run. This change bumps karma and introduces some more verbosity to the logs to help analyse the failures.
> Fix karma build failures

- spec/javascripts/karma.conf.js
This is currently unreliable on the build server and wouldn't function
locally without clobbering a single level in the folder hierarchy.
> Modify karma's basepath

- app/models/user.rb
- features/sign_in.feature
- features/step_definitions/sign_in_steps.rb
Devise `case_insensitive_keys` doesn't work with `attr_encrypted` for some reason.
This fix just overrides devise User finder and drops the email case.
> Make email address case insensitive when signing in

- app/views/layouts/email.html.erb
This was incorrectly resolving the local app path when using the
`image_tag` helper. Forcing the `asset_url` helper means in
productionish environments the full asset path is resolved.
> Force assets URL digested images in email layout

- app/assets/javascripts/syndication/iframeScroller.js
This PR adds javascript to intercept any clicks to "Back to top" style buttons and sends a message to the parent window (if any) to tell it to scroll the iframe to the top.
AEM will intercept this message and do the scrolling in javascript.
[Link to ticket](https://dev.azure.com.mcas.ms/moneyandpensionsservice/Digital%20Experience%20Platform%20-%20AEM/_workitems/edit/2497)
**Summary**
PACs Tool: Back to filters does not scroll parent
- Go to this page: https://www.moneyhelper.org.uk/en/everyday-money/banking/use-our-compare-bank-account-fees-and-charges-tool
- Scroll all the way to the bottom of the page, then to the bottom of the iframe, and then press "Back to filters".
- You should now be scrolled to the top of the iframe.
**Checklist**
Make …
> Scroll to iframe top when clicking "Back to top" links

- app/views/layouts/email.html.erb
- config/environments/production.rb
These legacy versions of rails require the asset host to be specified
under the mailer config too.
> Ensure emails use correct asset host

- Gemfile
- Gemfile.lock
https://github.com/moneyadviceservice/dough/pull/348
> Upgrade dough-ruby to fix broken email share links

- app/controllers/passwords_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/sessions_controller.rb
- config/environments/production.rb
- features/step_definitions/change_password_steps.rb
- features/step_definitions/registration_steps.rb
Various improvements to the accounts and tools integrations:
Resolve redirects after account actions
Ensure we never attempt to redirect back to the root path when an account
action is completed. The root path will always be a partner tools URL that
then issues further redirects back to MoneyHelper. In the case of password
resets, we need to redirect back into the embedded environment as due to
constraints when passing tokens via AEM pages, we have to link directly to
the password reset journey outside of AEM and redirect back into it upon
successful reset.
Improve resolution of mailer URLs
This will ensure that production-like environments can resolve to the 
correct URL required for completing the password reset journey and others.
> Account improvements

- app/controllers/passwords_controller.rb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/layouts/syndicated.html.erb
Flash messages were never added to syndicated tools so in certain cases actions
could be confusing to the end user. For example, during the password reset
journey the customer submits their email and is then redirected to the sign in
page, without any further notification context. Adding the flash messages means
the user is well informed.
> Add flash messages to syndicated layout

- config/initializers/devise.rb
This can solve the phantom requests issues after signing out using
specific versions of safari.
> Permit signout via GET

- app/assets/javascripts/modules/IE11ImageLabelFix.js
- app/assets/javascripts/modules/common.js
- app/assets/javascripts/require_config.js.erb
- config/initializers/assets.rb
- spec/javascripts/test-main.js
Images inside labels don't trigger the input specified in for="". This works around that.
References:
- https://snook.ca/archives/javascript/using_images_as
- https://stackoverflow.com/questions/17907445/how-to-detect-ie11
Ticket: https://dev.azure.com.mcas.ms/moneyandpensionsservice/Digital%20Experience%20Platform%20-%20AEM/_boards/board/t/Team%201%20(Core%20Capability)/Stories/?workitem=3694
> Workaround for IE11 bug where <img> inside <label> doesn't work

- Gemfile.lock
The spreadsheet dependency broke how excel exports of budgets are
generated. Pinning that dependency seems to resolve the issues.
> Bump budget planner for spreadsheet fixes

- build.sh
- test.sh
- Don't purge bower cache on every build
- Don't purge bower components
I'm not sure why these changes were introduced (8 and 7 years ago respectively), but I don't believe we need them.
> Enable bower cache

- test.sh
This is because a bug in Karma is causing the tests to fail on occasion. This only occurs on slower CPUs (like in CI).
Also, remove redundant logging.
> Add a retry to the Karma test run

- app/controllers/mount_controller.rb
The canonical was missing thus causing issues in production when mounted
a cost calculator builder derived tool. I'll come back and add
integration features around this so we don't regress in future.
> Fix issue with mounted tools

- app/assets/javascripts/syndication/tools.js.coffee
- app/assets/javascripts/syndication/widget.js.coffee
The logo when syndicated was never configured to determine the
contextual locale meaning it was displayed in the EN version when the
tools are syndicated CY.
> Configure syndicated logo per locale

- .github/workflows/ci.yml
- lib/legacy_redirects.rb
This is necessary to match legacy paths for various locations.
> Redirect for legacy paths

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
ALLOWALL is considered the default so we can strip the header from the response rather than providing the value. This resolves issues in various browsers that report this misconfiguration.
> Correct `X-Frame-Options` header

- app/middleware/partner_tools_cookies.rb
- spec/middleware/partner_tools_cookies_spec.rb
In production environments due to the configuration of `force_ssl` this is added by Rails automatically. There was some incompatibility with this middleware and the tweaked settings. We can now always assume the `Secure` token is added in the necessary environments.
> Don't add the `Secure` token to cookies

- lib/legacy_redirects.rb
Wildcard redirects for all remaining legacy MAS traffic that doesn't match an existing redirection rule.
> Add a wildcard redirect for all other legacy MAS

- Gemfile
- Gemfile.lock
- app/controllers/embedded_tools_controller.rb
- spec/cassettes/webservices_capnetwork_co_uk/post/CAPDVLA_Webservice/CAPDVLA_asmx/DVLALookupVRM.yml
- spec/cassettes/webservices_capnetwork_co_uk/post/CAPNVD_Webservice/CAPNVD_asmx/GetBulkTechnicalData.yml
- spec/cassettes/webservices_capnetwork_co_uk/post/CAPUsedValues_Webservice/capusedvalues_asmx/GetUsedValuation.yml
- spec/cassettes/webservices_capnetwork_co_uk/post/CAPVehicles_Webservice/capvehicles_asmx/GetCAPMan.yml
- spec/cassettes/webservices_capnetwork_co_uk/post/captco_webservice/CAPTCO_Webservice_asmx/GetTCO.yml
- spec/features/car_cost_tool_spec.rb
- spec/requests/tool_integration/car_cost_tool_spec.rb
We were indiscriminantly checking before any action, for those tools
that were configured for cookie checks. Instead, we ought to only check
on GET requests. This was causing complications with the car cost
calculator particularly. This commit adds VCR recorded responses from
the CAP API that appear to contain secrets but do not, since the API
requires other secrets to function that are not included in the outputs.
> Only check landing pages on GET

- .github/workflows/ci.yml
- config/database.yml
- features/support/env.rb
- spec/spec_helper.rb
This was always targetting sqlite and I never really understood why. It
makes sense for these tests to run in parity with the dev/production
environment and leverage the same DB. This also fixes an issue with
sqlite that's currently affecting us in CI.
> Switch test DB to MySQL

- config/budget_warning_tools.yml
This was updated for 23/24 so is accurate and no longer needs the banner.
> Removes the redundancy pay banner

- lib/legacy_redirects.rb
- spec/requests/legacy_redirects_spec.rb
This was missed in the previous changes as
`partner-tools.moneyadviceservice.org.uk` is still used for syndication and the matching for hosts in the redirection rules went from exact to a regex that wasn't anchored.
The regression test will also catch any issues around syndicated tool redirections in future.
> Ignore the syndicated domain for redirections

- lib/legacy_redirects.rb
- spec/requests/legacy_redirects_spec.rb
When syndicated requests are made for the mortgage calculator, we redirect to the new tool URL.
> Redirect legacy mortgage calculator to new embed

- app/assets/javascripts/syndication/tools.js.coffee
This now redirects to the new tool and that has its own logo so we no longer need to display the large original logo.
> Remove syndicated logo for mortgage calculator

- app/assets/javascripts/syndication/tools.js.coffee
- lib/legacy_redirects.rb
- spec/requests/legacy_redirects_spec.rb
Redirects to their new tool counterparts and configures the logo to be ommitted in syndication.
> Prepare the SDC and LBTT calcs for decommission

- Gemfile
- Gemfile.lock
The tool is not accurate when the customer is a taxpayer in Scotland.
> Bump redundancy calc for Scotland banner

- Gemfile
- Gemfile.lock
- app/controllers/direct_budget_planner_controller.rb
- app/views/devise/sessions/new.html.erb
- config/routes.rb
- features/support/ui/pages/sign_in.rb
- spec/features/budget_planner_spec.rb
Adds direct links to budget planner summaries in English and Welsh to allow customers to land on this page, authenticate and be directed deep into the budget planner to their budget summary page. This is to facilitate the transferral of their old budgets into the new budget planner.
> Budget planner direct

- Gemfile
- Gemfile.lock
Removes the banner relating to Scotland as it's no longer needed.
> Bump action_plans for redundancy calc banner

- Gemfile
- Gemfile.lock
- db/schema.rb
Adds the correct taxation for customers completing the redundancy pay calculator and identifying as Scottish tax payers.
> Redundancy pay scotland

- app/assets/javascripts/syndication/tools.js.coffee
- lib/legacy_redirects.rb
- spec/requests/legacy_redirects_spec.rb
Omits the legacy logo in syndication and redirects to the new tool so
syndication with the legacy snippet works seamlessly.
> Ready the baby money timeline for the new tool

- app/assets/javascripts/syndication/tools.js.coffee
- app/models/cookied_tool.rb
- lib/legacy_redirects.rb
- spec/features/budget_planner_spec.rb
- spec/requests/legacy_redirects_spec.rb
- spec/requests/tool_integration/budget_planner_spec.rb
This phase just includes the redirects to enable syndication in the legacy contexts. A follow up PR will actually remove any references to the budget planner and associated code/resources.
> Budget planner retirement

- lib/legacy_redirects.rb
There are some external partners that use these paths directly still, so
they'll need to be served continuously.
> Ensure these legacy assets are served
