moneyadviceservice/frontend

- app/controllers/news_controller.rb
- app/views/news/show.html.erb
- config/initializers/core.rb
- features/cassettes/cy/core/repository/cms/cms/find/beth-maech-adroddiad-credyd-yn-ei-ddatgelu-amdanoch.yml
- features/cassettes/en/core/repository/cms/cms/find/what-your-credit-report-reveals-about-you.yml
- features/news_article_viewing.feature
- features/step_definitions/news_article_steps.rb
- features/support/env.rb
- features/support/ui/pages/news_article.rb
- lib/core/interactor/news_article_reader.rb
- spec/lib/core/interactor/news_article_reader_spec.rb
News and features page will still be fetched from hippo.
- Hide date on article page
- Remove latest news
> Fetch news article page from contento

- app/controllers/mount_controller.rb
- spec/controllers/mount_controller_spec.rb
- spec/requests/tool_integration/decision_trees_spec.rb
This was bugging me.
Will merge in the next couple hours.
> Re-conform to rubocop styleguide.

- app/assets/javascripts/modules/log.js
Think I broke this with my first commit :/
> Fix logging facade in old IE

- app/assets/javascripts/components/WantToTalk.js
- app/assets/javascripts/require_config.js.erb
- app/assets/stylesheets/components/page_specific/_want_to_talk.scss
- app/views/articles/show.html.erb
- app/views/shared/_want_to_talk.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/step_definitions/want_to_talk_steps.rb
- features/support/have_analytics_event_matcher.rb
- features/support/ui/pages/article.rb
- features/support/ui/sections/want_to_talk_panel.rb
- features/want_to_talk.feature
https://moneyadviceservice.tpondemand.com/entity/5330
Adds a toggle-able 'Want to talk?' pane onto article pages activated by Optimizely
> Implement 'Want to talk?' feature

- config/locales/cy.yml
> Update Welsh translations for Popular/Related links.

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
and now inherits
cc @Guntrisoft
> layout is no longer forced to application

- app/views/shared/_feedback.html.erb
- app/views/technical_feedback/new.html.erb
- config/routes.rb
as clashing with feedback engine
> fix named technical feedback routes

- app/assets/javascripts/application.js
- app/assets/stylesheets/layout/page_specific/_debt_management.scss
- app/controllers/debt_management_controller.rb
- app/views/debt_management/companies.html.erb
- app/views/debt_management/show.html.erb
- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
- config/routes.rb
* Adds list of companies who have shut down
* Adds item to FAQ
* Adds separate page listing companies who have shut down
List is deliberately surfaced twice for marketing reasons.
> Debt company list

- config/initializers/core.rb
- features/cassettes/en/core/repository/categories/public_website/find/tools-and-calculators.yml
Need to pause the release of the new category manager until we can migrate tools/videos etc.
> Turn off CMS category manager

- Gemfile.lock
- spec/cassettes/cy/core/repository/categories/public_website/find/having-a-baby.yml
- spec/cassettes/en/core/repository/categories/public_website/find/having-a-baby.yml
* update timelines
* add cassettes for baby timeline requests
> Bump Timelines to 1.2.1 to fix failing request specs

- bower.json.erb
An attempt to fix build failing due to missing/removed bow(ndl)er underscore dependency.
> Add a timelines dep to bower.json.erb

- app/assets/stylesheets/components/common/_authentication.scss
- app/assets/stylesheets/layout/common/_contact_panels.scss
- app/assets/stylesheets/layout/common/_global.scss
- app/assets/stylesheets/layout/common/_header.scss
- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/views/layouts/_application_shared.html.erb
- app/views/shared/_contact_panels.html.erb
There has been 4 issues reported today since the homepage went live! - these resolve those issues
> Homepage fixes

- config/locales/cy.yml
- config/locales/en.yml
Email from Trisha:
Hi T,
Here’s the blurb and link for the campaign spot:
Use our Budget planner to keep on top of your spending
https://www.moneyadviceservice.org.uk/en/tools/budget-planner
Awaiting Welsh, will send over as soon as it’s in
https://www.moneyadviceservice.org.uk/cy/tools/cynllunydd-cyllideb/start
Is it also possible to l/c ‘pensioner bonds’ in the boxes please?
Thanks,
T
> lowercased pensioner bonds

- test.sh
-f used to suppress failure even if the directory does not exist
> force removal of bower_components directory

- app/views/layouts/styleguide/page.html.erb
- app/views/layouts/styleguide/page_unconstrained.html.erb
tests were failing oops (must remember to run the tests!)
tests were failing since introduction of contact_panels_homepage variable
for the shared/contact_panels component
> contact panels bug

- Gemfile.lock
Attempt at fixing unclickable link issue on production
> Update debt advice locator

- app/assets/stylesheets/layout/common/_global.scss
- app/assets/stylesheets/layout/common/_header.scss
- app/assets/stylesheets/layout/page_specific/_article_page.scss
- ensure that width of left menu is the same as category pages on desktop
- remove strapline which shouldn't be in desktop left nav
- ensure that back to top link doesn't appear on desktop when in an article
> article menu layout fixes

- app/views/layouts/_application_shared.html.erb
- app/views/layouts/styleguide/page.html.erb
- app/views/layouts/styleguide/page_unconstrained.html.erb
- config/locales/cy.yml
- config/locales/en.yml
> Move the skip link content to the YML file

- config/initializers/valid_resource.rb
- config/routes.rb
- spec/requests/black_listed_resources_spec.rb
* There are some harded coded pages that are blocked from preview.
Please, let's remove that.
> Remove all articles from blacklist

- app/views/landing_pages/show.html.erb
> Update the annuities landing page to new video

- config/locales/en.yml
See: https://moneyadviceservice.tpondemand.com/entity/5804
> change subheading to "Your tools and settings"

- app/controllers/mount_controller.rb
- app/controllers/rio_controller.rb
- config/application.rb
- config/routes.rb
- lib/engine_mount_point.rb
- lib/engine_mount_point/base.rb
- lib/engine_mount_point/rio.rb
- lib/tool_mount_point.rb
- lib/tool_mount_point/rio.rb
- spec/controllers/mount_controller_spec.rb
- spec/requests/tool_integration/rio_spec.rb
> change rio mount point to /retirement-income-opt..

- README.md
- config/features.yml.sample
Add a features.yml.sample on the frontend.
> Fix #937 - Add a features sample file

- app/views/layouts/engine_unconstrained.html.erb
...in the header of the layout.
> allow engine to control alternate language link

- app/assets/stylesheets/components/common/_panel.scss
- app/assets/stylesheets/layout/page_specific/_block.scss
This HTML for this will be outputted by the CMS.
Will be part of this page...
> Add partnership block snippet styling

- app/controllers/application_controller.rb
cc @munckymagik @JiggyPete @picandocodigo
> add comment to syndicated layout

- lib/engine_mount_point/rio.rb
- spec/cassettes/cy/core/repository/categories/cms/find/automatic-enrolment.yml
- spec/cassettes/cy/core/repository/categories/cms/find/jobs-and-tax.yml
- spec/cassettes/cy/core/repository/categories/cms/find/redundancy.yml
- spec/cassettes/cy/core/repository/categories/cms/find/retirement-income-basics.yml
- spec/cassettes/cy/core/repository/categories/cms/find/types-of-pensions.yml
- spec/cassettes/cy/core/repository/categories/cms/find/types-of-retirement-income.yml
- spec/cassettes/cy/core/repository/categories/cms/find/work-pensions-and-retirement.yml
- spec/cassettes/en/core/repository/categories/cms/find/automatic-enrolment.yml
- spec/cassettes/en/core/repository/categories/cms/find/jobs-and-tax.yml
- spec/cassettes/en/core/repository/categories/cms/find/redundancy.yml
- spec/cassettes/en/core/repository/categories/cms/find/retirement-income-basics.yml
- spec/cassettes/en/core/repository/categories/cms/find/types-of-pensions.yml
- spec/cassettes/en/core/repository/categories/cms/find/types-of-retirement-income.yml
- spec/cassettes/en/core/repository/categories/cms/find/work-pensions-and-retirement.yml
- The vcr cassettes are used for the breadcrumb trail
> rio welsh mount point

- Gemfile
- Gemfile.lock
https://github.com/moneyadviceservice/pensions_calculator/pull/167
> Bump pensions calculator. (0.2.3.525 -> 0.2.3.526)

- app/views/styleguide/pages_annuities_landing_page.html.erb
> Fix missing translation

- config/initializers/mortgage_calculator.rb
This accompanies PR: https://github.com/moneyadviceservice/scripts/pull/207 to to reintroduce the bugsnag api key if we want it back.
NOTE: The other commit will need to be merged into scripts before this one goes in.
> add setter for bug snag key

- app/assets/stylesheets/components/common/_icon.scss
To work we also need this related PR accepted and built: 
https://github.com/moneyadviceservice/car_cost_tool/pull/22
> adding styles to allow car cost tool to remove font awesome and use dough instead

- app/decorators/chat_opening_hours_decorator.rb
- app/views/shared/_contact_panels.html.erb
- config/application.rb
- spec/decorators/chat_opening_hours_decorator_spec.rb
new method required as the requirement is that sunday which is closed
needs to be omitted
> new webchat times updated

- Gemfile.lock
Updates the versions of action_plans and advice_plans on frontend
> Update action_plans and advice_plans versions

- config/environments/development.rb
> Remove Matt Lucht's emaill address for technical feedback

- config/features.yml.sample
- config/routes.rb
- features/corporate_page.feature
- features/step_definitions/corporate_steps.rb
- features/support/ui/pages/corporate.rb
- features/support/world/pages.rb
- spec/controllers/corporate_controller_spec.rb
Places the corporate page behind a feature flag.
> Corporate feature

- features/cassettes/en/core/repository/categories/cms/find/Partners.yml
- features/cassettes/en/core/repository/categories/cms/find/about-us.yml
- features/cassettes/en/core/repository/categories/cms/find/corporate-home.yml
- features/cassettes/en/core/repository/categories/cms/find/media-centre.yml
- features/cassettes/en/core/repository/categories/cms/find/our-debt-work.yml
- features/cassettes/en/core/repository/categories/cms/find/resources-for-professionals.yml
These cassettes are needed for the corporate page related unit/feature specs.
> Check in corporate cassettes

- app/controllers/application_controller.rb
- app/controllers/sitemap_controller.rb
- app/decorators/category_decorator.rb
- app/views/sitemap/index.html.erb
- config/routes.rb
- lib/core.rb
- lib/core/interactor/category_tree_reader.rb
- lib/core/interactor/category_tree_reader_with_decorator.rb
- spec/controllers/sitemap_controller_spec.rb
public website version pulls from old cms hippo. This one pulls from the new cms contento
> add sitemap

- app/assets/javascripts/syndication/tools.js.coffee
Note: don't merge until the test harness and the scripts pull request is revised.
> Quick cash finder syndication

- app/controllers/static_pages_controller.rb
- config/initializers/core.rb
- features/cassettes/cy/core/repository/static_pages/cms/find/cysylltu-a-ni.yml
- features/cassettes/cy/core/repository/static_pages/cms/find/polisipreifatrwydd.yml
- features/cassettes/cy/core/repository/static_pages/cms/find/privacy.yml
- features/cassettes/en/core/repository/static_pages/cms/find/about-us.yml
- features/cassettes/en/core/repository/static_pages/cms/find/contact-us.yml
- features/cassettes/en/core/repository/static_pages/cms/find/polisipreifatrwydd.yml
- features/cassettes/en/core/repository/static_pages/cms/find/privacy.yml
- features/static_pages.feature
- features/step_definitions/static_page_steps.rb
- lib/core.rb
- lib/core/entity/static_page.rb
- lib/core/repository/static_pages/cms.rb
- spec/cassettes/terms.yml
- spec/lib/core/entity/static_page_spec.rb
- spec/lib/core/repository/static_page/cms_spec.rb
I tried to make this backwards compatible but it turns out that the `Feature` library isn't available when setting up core to use different drivers/repositories
> contact us and accessibility pages use contento

- app/assets/stylesheets/components/common/_link_list_tertiary.scss
- app/assets/stylesheets/layout/page_specific/_inpage_nav.scss
- app/views/corporate/_content_items.html.erb
- app/views/corporate_categories/_content_items.html.erb
- app/views/styleguide/components_website.html.erb
- app/views/styleguide/shared/_link_list_tertiary.html.erb
> Format third-level category menu

- app/views/shared/_contact_panels.html.erb
- config/application.rb
- config/locales/cy.yml
- config/locales/en.yml
> May Bank Holiday opening hours update

- config/locales/landing_pages/annuities.cy.yml
- config/locales/landing_pages/annuities.en.yml
> Update annuities landing page title tag & meta description.

- app/assets/javascripts/components/StickyColumn.js
- app/assets/javascripts/require_config.js.erb
- app/assets/stylesheets/components/page_specific/_more_in.scss
- app/assets/stylesheets/components/page_specific/_related_links.scss
- app/assets/stylesheets/layout/common/_global.scss
- app/assets/stylesheets/layout/page_specific/_article_page.scss
- app/views/articles/_article_links.html.erb
- app/views/articles/_related_articles.html.erb
- app/views/articles/show.html.erb
- app/views/corporate/show.html.erb
- spec/javascripts/fixtures/StickyColumn.html
- spec/javascripts/test-main.js
- spec/javascripts/tests/StickyColumn_spec.js
TP Ticket: https://moneyadviceservice.tpondemand.com/entity/6334
> TP-6334: Making the right column on article pages 'sticky' when scrolling on desktop

- app/controllers/retirements_controller.rb
- config/features.yml.sample
- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
- config/routes.rb
- spec/controllers/retirements_controller_spec.rb
I think this is going to take longer than I hoped to send live — this PR is so I don't block any of youse getting to production
@baphled @Tr4pSt3R since I think you're on the path to deployment
> Put Welsh retirement landing pages behind feature flag.

- app/assets/stylesheets/components/page_specific/_related_links.scss
opened each section so you can see links for non-js
> TP-6355 Recirculation drivers - Non JS version is not working

- app/assets/stylesheets/components/common/_accessin.scss
- app/views/shared/_footer_secondary.html.erb
They rewrote their form and have supplied a new embed code.
> Updating DAC AccessIn code

- config/features.yml.sample
See https://github.com/moneyadviceservice/scripts/pull/234 for more details.
> Updating features.yml.sample equals to production

- app/views/styleguide/css_overview.html.erb
Old commit but this is useful! Thanks @aduggin
> Document css naming convention for cucumber hooks

- config/features.yml.sample
See https://github.com/moneyadviceservice/scripts/pull/239 for more details
> Features toggle should be sort in alphabtical order

- spec/cassettes/en/core/repository/categories/cms/find/syndication.yml
- spec/cassettes/en/core/repository/corporate/cms/find/budget-planner-syndication.yml
- spec/cassettes/en/core/repository/corporate/cms/find/sample-tool-syndication.yml
- spec/controllers/corporate_controller_spec.rb
- spec/spec_helper.rb
* Fixes failures occuring with unit tests in Go due to missing VCR cassettes. 
@asmega
> Syndicated tools tests fix

- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
> Update links to Step Change

- app/assets/stylesheets/components/common/_search.scss
- app/assets/stylesheets/components/page_specific/_home_top.scss
- app/assets/stylesheets/layout/common/_header.scss
> Homepage banner changes

- app/assets/javascripts/require_config.js.erb
- spec/javascripts/test-main.js
Needed in both the test and main site config
This should fix current build failing
> Adding Dough's utilities to require configs

- config/environments/production.rb
Will now be 'bugs@moneyadviceservice.org.uk'
> Change the recipient of technical feedback.

- app/controllers/corporate_controller.rb
- app/views/corporate/extra/_syndication.html.erb
- app/views/corporate/extra/_tool.erb
- config/locales/corporate/corporate_home.en.yml
A handful of small changes, mostly to do with copy.
Detailed in TP ticket #5621
> Update syndication & tools pages

- app/controllers/corporate_controller.rb
...to prevent 404 on tool pages with >2 URL slug segments.
Look OK, @darokel?
> Redirect user to tool id param

- app/controllers/corporate_controller.rb
- app/models/corporate_partner.rb
- app/views/tools/_embed_code.html.erb
- spec/controllers/corporate_controller_spec.rb
- spec/models/corporate_partner_spec.rb
A few changes to make tool embed snippets behave correctly.
> Fix embed tool URLs

- app/assets/stylesheets/_enhanced.scss
- app/assets/stylesheets/base/_typography.scss
- app/assets/stylesheets/base/_variables.scss
This updates the font sizing and associated spacing on headings through the site. Have just separated it out from the category styling branch.
> Update global styles (#6288)

- app/assets/stylesheets/components/common/recommended_tool/_recommended_tool.scss
- app/assets/stylesheets/layout/page_specific/_profile.scss
- app/views/profile/edit.html.erb
- config/locales/recommended_tools.cy.yml
- config/locales/recommended_tools.en.yml
- lib/core/repository/recommended_tools/static.rb
- spec/lib/core/repository/recommended_tools/static_spec.rb
- swap the goals and saved tools around
- move the recommended tools section directly
below the saved tools
- drop down to only two recommended tools
- replace the car cost tool with retirement tool
> TP-6317 TP-6344: Profile page changes

- Gemfile.lock
Include the following changes:
https://github.com/moneyadviceservice/action_plans/pull/120
https://github.com/moneyadviceservice/action_plans/pull/121
> TP-6426: TP-6423: update action_plans

- app/assets/stylesheets/layout/page_specific/_profile.scss
- app/controllers/profile_controller.rb
- app/views/profile/edit.html.erb
- config/locales/saved_tools.cy.yml
- config/locales/saved_tools.en.yml
- Altered language files with new copy
- Conditional logic on what to display in the
saved tools section
- Conditional logic on whether to display
the budget planner 'advert' based on
whether it's been saved or not
> TP-6343: Account page - Budget planner if-then functionality

- app/assets/stylesheets/layout/common/_global.scss
- fix issue with l-main__row on mobile viewport widths
> TP-6462: Content is greater than 320px on these pages

- app/assets/stylesheets/components/common/_newsletter_signup.scss
> TP-6462: Ensuring the welsh newsletter button doesn't exceed page width

- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
> TP-6462: Altered content to ensure it doesn't break page width on mobile

- app/views/categories/_top_links.html.erb
demoted from a heading to paragraph text
fyi Welsh translation to come later
> Tweak top links heading

- app/assets/stylesheets/components/common/_search.scss
- app/assets/stylesheets/layout/page_specific/_error_page.scss
- Search text increased, after Irina felt it was too small (14px -> 16px)
- padding tweaks and font-size change of copy
> id:6391 comment: design tweeks from Irina after feedback

- app/views/debt_management/show.html.erb
- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
- There was no translations provided, so for welsh:
- Used the h1 title for the meta title on welsh,
- Same english description as the welsh version
> id:6468 comment: meta data for Debt Management Page

- app/views/shared/_news_signup_test.html.erb
- app/views/static_pages/contact_us.html.erb
- adding option to display the newsletter signup straight away
and not use the Newsletter.js script to place it
> id:6504 comment: Contact Us page - add Newsletter sign-up module

- Gemfile
- Gemfile.lock
- app/controllers/newsletter_subscriptions_controller.rb
- config/initializers/core.rb
- lib/core.rb
- lib/core/repository/newsletter_subscriptions/cream.rb
- lib/core/repository/newsletter_subscriptions/fake.rb
- spec/controllers/newsletter_subscriptions_controller_spec.rb
- spec/lib/core/repository/newsletter_subscriptions/cream_spec.rb
ported from old public website
> implement newsletter subscription

- app/assets/javascripts/components/ScrollTo.js
- app/assets/javascripts/require_config.js.erb
- app/views/categories/_child_categories.html.erb
When clicking the VIEW LESS button on category pages.
> Scroll to subcategory heading anchor

- Gemfile.lock
- app/assets/stylesheets/components/dough_theme/button/_button.scss
- app/assets/stylesheets/styleguide/_all.scss
> Newsletter button style

- app/assets/stylesheets/layout/page_specific/_registration.scss
- app/helpers/sessions_helper.rb
- app/views/devise/registrations/new.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/registration.feature
- features/step_definitions/registration_steps.rb
- features/support/ui/pages/sign_up.rb
- spec/helpers/sessions_helper_spec.rb
- copy changes
- some conditional code to deal with user coming to the page fresh or from budget planner
- uses new style for newsletter button
> id:6499 comment:updates to Registration page

- app/assets/javascripts/syndication/tools.js.coffee
* This enables the syndication of debt and mental health on partner-tools
> Add debt and mental to tools.js

- lib/core.rb
- lib/core/interactor/action_plan_reader.rb
- lib/core/interactor/article_reader.rb
- lib/core/interactor/base_content_reader.rb
- lib/core/interactor/corporate_reader.rb
- lib/core/interactor/video_reader.rb
- minor api change with exposing of id to ensure compatability
cc @tomas-stefano
> refactor interactors with inheritance

- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
Did not revert as there was another unrelated translation in the previous commit too.
> Remove new company from list temporarily

- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
Sorry about the back and forth on this, it's back in now.
> Add company to debt list

- lib/core/entity/customer.rb
- lib/core/repository/customers/cream.rb
- lib/core/repository/customers/fake.rb
- spec/lib/core/entity/customer_spec.rb
depends on https://github.com/moneyadviceservice/cream/pull/13
> TP-6556: add contact_number to CRM

- Gemfile.lock
- spec/routing/landing_pages_spec.rb
Also sneakily made a test a little more robust (i.e. stop it failing).
Probably there's some feature flag I could disable to make it pass, but it seems like the tests should pass either way.
> [DEV APPROVED] Update rio and pencalc

- Gemfile
- Gemfile.lock
- lib/validators/email.rb
- spec/validators/email_spec.rb
- dependent on https://github.com/moneyadviceservice/postcode_anywhere-email_validation/pull/3
> port email anywhere validator from old site

- Gemfile
- Gemfile.lock
- config/initializers/postcode_anywhere.rb
- features/step_definitions/newsletter_signup_steps.rb
- lib/core.rb
- lib/core/entity/newsletter_subscription.rb
- lib/core/interactor/newsletter_subscription_creator.rb
- lib/validators/email.rb
- spec/controllers/newsletter_subscriptions_controller_spec.rb
- spec/lib/core/interactor/newsletter_subscription_creator_spec.rb
- spec/validators/email_spec.rb
- as these changes were reverted due to deployment woes
> re-implement newsletter email validation

- Gemfile.lock
Incorporates this change
https://github.com/moneyadviceservice/pensions_calculator/pull/176
> Bump pensions_calculator version .533 -> .534

- app/assets/javascripts/components/StickyColumn.js
- added scroll to page to move the related links section into view where necessaary
> id: 6356, comment: Recirculation Driver - Title not visible

- app/assets/stylesheets/components/page_specific/_category_link_list.scss
- app/views/categories/_top_links.html.erb
Tried to do this with pseudo-elements but after much difficulty decided to stick to basics.
> Fix wrapping commas on header links

- app/views/layouts/_base.html.erb
Is this the right file to add this into? How do 3rd parties pull in the head?
> Add IE edge meta

- config/locales/landing_pages/annuities.cy.yml
> id: 6557, comment: broken links to Welsh pages on Annuities tool

- config/locales/cy.yml
- config/locales/en.yml
- changes to YAML files (en and cy) made to correct the copy
> id: 6651, comment: Copy bug - Home page strapline in English and Welsh

- app/assets/stylesheets/components/common/_survey.scss
Stylesheet provided by third party and added here to make available on each page required.
> id: 6657, comment: add styles for the GFK pop-up exit poll

- build.sh
- my limited bash knowledge to add timings to steps of the build process to identify bottlenecks
> add timings to the build script

- .env
- .env.test
- spec/cassettes/agreements.yml
- spec/cassettes/core/repository/cms/cms_api/find/idonotexist.yml
- spec/cassettes/cy/core/repository/articles/cms/find/pam-cynilo-mewn-pensiwn.yml
- spec/cassettes/en/core/repository/articles/cms/find/no-exist.yml
- spec/cassettes/en/core/repository/articles/cms/find/permanent-redirect.yml
- spec/cassettes/en/core/repository/articles/cms/find/temporary-redirect.yml
- spec/cassettes/en/core/repository/articles/cms/find/why-save-into-a-pension.yml
- spec/cassettes/en/core/repository/corporate/cms/find/budget-planner-syndication.yml
this uses the namespaced route to prevent collisions
> change cms api endpoint

- Gemfile.lock
Updated the version of the debt advice locator in gem file to include anchors
> Update debt advice version

- app/controllers/registrations_controller.rb
- app/views/devise/registrations/new.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- db/migrate/20150827092935_add_opt_in_field_to_users.rb
- db/schema.rb
- features/registration.feature
- features/step_definitions/registration_steps.rb
- features/support/ui/pages/sign_up.rb
Depends on the successful merge of the PR for the Cream library: https://github.com/moneyadviceservice/cream/pull/15
> [DEV APPROVED] add opt_in_for_research field to User record

- app/controllers/concerns/authenticable.rb
Bypass QA & Staging as HTTP auth is already implemented there.
> Refactor Auth module

- build.sh
- test.sh
ensure vendor cache from prior build runs are removed before test runs
> fix intermittent go failures

- app/assets/javascripts/components/NewsletterSticky.js
- spec/javascripts/tests/NewsletterSticky_spec.js
* Object was undefined, switched to variable and added stubs for window and scroll params.
> Fix broken Newsletter Test

- features/display_newsletter_form.feature
- features/step_definitions/display_newsletter_form_steps.rb
- lib/core/interactor/newsletter_subscription_creator.rb
* set feature flag mode
* stub out Newsletter customer object creation
> stub Newsletter method call in cucumber test

- app/controllers/categories_controller.rb
- lib/core/entity/category.rb
- lib/core/interactor/category_reader.rb
- lib/core/repository/categories/cms.rb
- spec/cassettes/en/core/repository/categories/cms/find/idonotexist.yml
- spec/cassettes/en/core/repository/categories/cms/find/redirected.yml
- spec/controllers/categories_controller_spec.rb
- spec/lib/core/interactor/category_reader_spec.rb
- spec/lib/core/repository/categories/cms_spec.rb
- also added missing tests to ensure coverage
> allow categories to be redirected with the cms

- app/views/christmas_money_planner/show.html.erb
> Update christmas calc embed code

- app/views/christmas_money_planner/show.html.erb
Will be overridden by the iframe resizer javascript code
> Adds default iframe height for non-javascript users

- Gemfile.lock
- features/quiz_admin_login.feature
- features/step_definitions/quiz_authentication_steps.rb
- features/support/ui/pages/quiz_admin.rb
- features/support/world/pages.rb
- lib/core/interactor/user_updater.rb
- spec/lib/core/interactor/user_updater_spec.rb
This is related to https://github.com/moneyadviceservice/quiz/pull/9
> [DEV APPROVED] - Quiz authentication

- lib/tool_mount_point/decision_trees.rb
- spec/requests/tool_integration/decision_trees_spec.rb
> remove workplace pension adivce tool

- app/views/shared/_footer_primary.html.erb
- app/views/shared/_newsletter_signup.html.erb
Some classes were missing for the cucumber hooks.
> Fixing cucumber tests

- app/assets/stylesheets/components/page_specific/_home_top.scss
Updating hero slot bg image to use conditional @if $responsive == false { … } rather than
.ie8 & { … }
> [DEV APPROVED] Updating IE8 hero image css

- config/environments/production.rb
This scripts PR 445 be merged.
https://github.com/moneyadviceservice/scripts/pull/445
Note that this PR is targetting the `azure-migration` branch ... it doesn't need to be deployed to the Rackspace environment and we'll be using this branch to collect Azure-specific changes.
> Use RESPONSIVE_ASSET_HOST_URL env var.

- app/views/christmas_money_planner/show.html.erb
- config/locales/landing_pages/annuities.cy.yml
- config/locales/landing_pages/annuities.en.yml
- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
Tried to find a way to refactor this nicely but it didn't seem worth the effort in the end. The URLs in the localised translations would be a particular pain, having to supply additional parameters to `t()` calls, if anyone can point me to an easy way of parameterising the URLs there I may update the PR.
> Replace Rackspace CDN with Azure asset hosting

- Gemfile.lock
- pensions_calculator
- advice_plans
- debt_test
- payday_loans_intervention
> Updates to tools:

- Gemfile
- Gemfile.lock
this removes the frontend helpers dependency
> update savings calc 1.1.2 => 1.2.0

- config/initializers/bugsnag.rb
Remove env check as we can do this in puppet now
> Refactor Bugsnag Initialiser

- app/controllers/errors_controller.rb
- config/features.yml.sample
This will be only merged after the migration is completed.
> Format redirect fix

- lib/core/repository/categories/cms.rb
When trying to run Front End from development, there's a few things that
you need to have set up to get a connection to Contento. This is written
up in the README, but if someone's missed something it's not that easy
to tell them what they've missed.
This is an attempt to add a bit more context for debugging this error.
> Better Contento connection info in error

- config/features.yml.sample
- config/routes.rb
Since the redirects feature is proving it is working nicely,
I removed the feature flag since we don't need to use that anymore
> Remove redirects feature flag

- db/migrate/20151109120230_drop_old_public_website_tables.rb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1292)
> [DEV APPROVED] Fixes the order of the tables to be dropped.

- lib/core/repository/categories/cms.rb
- lib/core/repository/cms/cms.rb
- spec/controllers/corporate_controller_spec.rb
- spec/lib/core/repository/categories/cms_spec.rb
- spec/lib/core/repository/cms/cms_spec.rb
- spec/requests/404_spec.rb
- spec/requests/not_implemented_spec.rb
The redirects feature flag is not used anymore.
> [DEV APPROVED]Remove the feature redirects conditions

- app/views/shared/_contact_panels.html.erb
- app/views/static_pages/contact_us.html.erb
- app/views/static_pages/cysylltu_a_ni.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Updating opening times to reflect Christmas period.  Includes contact us page (en/cy) and homepage contact panels (en/cy)
> [DEV APPROVED] Adding Christmas opening times

- app/assets/stylesheets/components/page_specific/_home_top.scss
Updating Hero slot CSS, removing references to images as they will be served inline from CMS.
> [DEV APPROVED] Updating Hero CSS

- Gemfile.lock
> id: 6640, comment: updates Gemfile.lock to use udated versions of tools

- app/assets/stylesheets/layout/common/_contact_panels.scss
In a previous PR for ticket 6797 we accidentally removed some borders on the contact panels. This PR adds them back in but also adds a flexible height to the borders so that they will increase in height when the content is longer.
> [DEV APPROVED] 6797 adding in contact panel borders

- config/features.yml.sample
See https://github.com/moneyadviceservice/scripts/pull/484 and https://github.com/moneyadviceservice/budget_planner/pull/383
> Add budget planner social share feature flag

- Gemfile.lock
Bumping debt test version to 1.4.0.28
Debt test change is for ticket #6866 (Debt test header text hidden on mobile)
> [DEV APPROVED] Bumping debt test

- .env
- test.sh
Fixes 6a95868ed723ea6a03153e2e8e96f200d95951ed (changed url in .env) also fixes removed ```-l``` in test.sh
> Fix pst errors

- app/controllers/application_controller.rb
- app/helpers/sticky_newsletter_visibility.rb
- app/views/layouts/_application_shared.html.erb
- features/cassettes/cy/core/repository/categories/cms/find/car-insurance.yml
- features/cassettes/cy/core/repository/categories/cms/find/corporate-home.yml
- features/cassettes/cy/core/repository/categories/cms/find/home-insurance.yml
- features/cassettes/cy/core/repository/categories/cms/find/insurance.yml
- features/cassettes/cy/core/repository/categories/cms/find/life-and-protection-insurance.yml
- features/cassettes/cy/core/repository/categories/cms/find/managing-money.yml
- features/cassettes/cy/core/repository/categories/cms/find/pet-insurance.yml
- features/cassettes/cy/core/repository/categories/cms/find/travel-insurance.yml
- features/cassettes/en/core/repository/corporate/cms/find/media-centre.yml
- features/display_newsletter_form.feature
- features/step_definitions/display_newsletter_form_steps.rb
- features/step_definitions/sticky_footer_visibility_steps.rb
- features/sticky_footer_visibility.feature
- features/support/ui/pages/article.rb
- features/support/ui/pages/corporate_categories.rb
- features/support/ui/pages/sitemap.rb
- features/support/ui/pages/tools.rb
- features/support/world/pages.rb
- spec/helpers/shared_examples/display_sticky_newsletter_spec.rb
- spec/helpers/sticky_newsletter_visibility_spec.rb
* removes sticky footer newsletter from home page
* removes sticky footer newsletter from categories page
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1313)
> [DEV APPROVED] Removes sticky newsletter from selected pages

- app/controllers/articles_controller.rb
- app/helpers/survive_january.rb
- app/views/articles/show.html.erb
- features/step_definitions/survive_january_steps.rb
- features/support/ui/pages/article.rb
- features/support/ui/sections/survive_january.rb
- features/survive_january.feature
- spec/helpers/survive_january_spec.rb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1340)
> [DEV APPROVED] activate survive january campaign on a certain date

- Gemfile.lock
> Bump version for PayDay Loans update

- app/views/campaigns/survive_january.html.erb
Content and Digital: "You’ve got my sign off based on a thirty second tweak of grammar and spelling – final sign off will have to come from marketing on this one."
Marketing: "Ok – then let’s go ahead."
> Survive January Copy updates

- spec/helpers/survive_january_spec.rb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1349)
> fix before go live date spec issue

- config/locales/debt_management/debt_management.en.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1354)
> [DEV APPROVED] add debt firms to warning list

- config/locales/debt_management/debt_management.cy.yml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1355)
> [DEV APPROVED] add firm to welsh list

- lib/newsletter_exclusions.rb
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1356)
> [DEV APPROVED] removes sensitive articles from artcles page

- Gemfile.lock
Changes in Budget Planner: https://github.com/moneyadviceservice/budget_planner/pull/397
> Updates version of Budget Planner

- Gemfile.lock
Updates Rio to include the Income Drawdown page.
> update rio to latest version.

- app/assets/stylesheets/components/common/_search.scss
- app/assets/stylesheets/layout/common/_header.scss
- fix Search dropdown problem
- repositions the reset button in the search box
> id: 7012, comment: Extends changes on header to tools to:

- config/locales/retirements.cy.yml
- config/locales/retirements.en.yml
Adjustments to `/en/pensions-and-retirement`
> [DEV APPROVED] Adjust income draw down link and add into "Your options"

- Gemfile.lock
Bumping version of Mortgage Calculator. <strike>This has also updated dough-ruby, minitest, rake and underscore-rails.</strike>
> Bumping mortgage calculator

- Gemfile.lock
For this https://github.com/moneyadviceservice/rio/pull/82
> [DEV APPROVED] Bump RIO to include SEO changes

- app/views/static_pages/contact_us.html.erb
- app/views/static_pages/cysylltu_a_ni.html.erb
- config/locales/cy.yml
- config/locales/en.yml
**Current and New Phone Numbers**
**Current**
**New**
**Current**
**New**
**Current**
**New**
**Current**
**New**
> Update Phone number and calls free on Footer & Contact us page

- Gemfile.lock
Changes have been approved on Preview by Mo.
> Update for latest SEO changes to RIO.

- app/assets/stylesheets/components/common/_global-alert.scss
- app/controllers/application_controller.rb
- app/helpers/budget_warning.rb
- app/views/layouts/_unconstrained.html.erb
- app/views/shared/_banner_alert.html.erb
- app/views/shared/_tool_alert.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/add_warning_to_tools.feature
- features/cassettes/cy/core/repository/categories/cms/find/redundancy.yml
- features/step_definitions/add_warning_to_tools_steps.rb
- spec/helpers/budget_warning_spec.rb
- spec/helpers/shared_examples/displays_banner_warning.rb
This PR adds a warning to the Redundancy Pay Calculator that will automatically appear on the 16th March.
> [DEV APPROVED]Adding warning tools 7047

- Gemfile
- Gemfile.lock
Our gems source is now in Azure.
> Change MAS gem source to gems.dev.mas.local

- app/assets/javascripts/require_config.js.erb
This imports the new CollapsableMobile component from Dough
> [DEV APPROVED] CollapsableMobile component extends from Collapsable.

- Gemfile.lock
Version bump for debt-advice-locator
> 6973- Bump DAL version

- Gemfile.lock
- features/display_newsletter_form.feature
- features/step_definitions/display_newsletter_form_steps.rb
- features/step_definitions/want_to_talk_steps.rb
- features/support/env.rb
- features/support/have_analytics_event_matcher.rb
- features/support/rspec.rb
Also fix broken feature highlighted by the newer version.
> Upgrade poltergiest

- Gemfile.lock
> [DEV APPROVED] Bumping RIO

- app/views/static_pages/contact_us.html.erb
- app/views/static_pages/cysylltu_a_ni.html.erb
|-----------|----------|
|<img width="313" alt="english" src="https://cloud.githubusercontent.com/assets/13165846/13917672/38ad339c-ef5a-11e5-818d-46130074a143.png">|<img width="313" alt="welsh" src="https://cloud.githubusercontent.com/assets/13165846/13917678/3ec223c8-ef5a-11e5-9dde-99ea5c549a5b.png">|
> [DEV APPROVED] #7203 - Easter opening hours

- Gemfile.lock
The updated version of timelines includes the ticket #7028 - Baby money timeline updates
PR: https://github.com/moneyadviceservice/timelines/pull/62
> [DEV APPROVED] #7028 Bumping timelines

- app/assets/stylesheets/layout/page_specific/_debt_management.scss
- config/locales/debt_management/debt_management.cy.yml
- config/locales/debt_management/debt_management.en.yml
PR updates copy and sets the link within that to open in a new tab.
> id: 7216, comment: Updates copy on Debt Management page

- app/assets/stylesheets/base/_reset.scss
Removing the outline on the tabbed-to <main> tag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1426)
> [DEV APPROVED] 7034 - Removing outline

- Gemfile.lock
See the details of the actual work here: https://github.com/moneyadviceservice/rio/pull/87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1423)
> [DEV APPROVED] bump RIO gem to include fixes

- features/display_newsletter_form.feature
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1420)
> [DEV APPROVED] fix expectation test for Sticky newsletter

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1435)
> [DEV APPROVED] bump RIO version from 0.0.3 down to 1.0.0

- .env
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1444)
> [DEV APPROVED] change MAS CMS url to point to Azure server

- app/helpers/budget_warning.rb
- features/add_warning_to_tools.feature
- features/step_definitions/add_warning_to_tools_steps.rb
- spec/helpers/budget_warning_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1440)
> [DEV APPROVED] Add warning banner to the retirement options page

- app/helpers/budget_warning.rb
- features/add_warning_to_tools.feature
- spec/helpers/budget_warning_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1448)
> [DEV APPROVED] 7097 remove updated year end tools

- Gemfile
- Gemfile.lock
Required for PR#63 in Timelines (https://github.com/moneyadviceservice/timelines/pull/63)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1453)
> TP: 7311, Comment: Bumps version for Timelines

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1459)
> Update rio to version 1.4.0

- config/locales/cy.yml
- config/locales/en.yml
- Updated English YAML
- Updated Welsh YAML (Same as english)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1470)
> [DEV APPROVED] 7415 - Updating blog footer url

- Gemfile
- Gemfile.lock
The changes can be viewed here: https://github.com/moneyadviceservice/action_plans/pull/133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1479)
> [DEV APPROVED]bump version from 4.0.8 to 4.1.1

- Gemfile.lock
Rolling out the changes in [this big PR](https://github.com/moneyadviceservice/mortgage_calculator/pull/250). Original work done by @oneKelvinSmith with follow up work from myself and @slaywell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1481)
> Bump mortgage calculator

- app/helpers/application_helper.rb
- app/views/layouts/_base.html.erb
Depends on PR659 on Scripts repo (https://github.com/moneyadviceservice/scripts/pull/659)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1480)
> [DEV APPROVED] Comment: Adds Optimizely tag to UAT

- build.sh
this will fix the issue uploading frontend assets into the env specific asset containers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1500)
> [DEV APPROVED] add ${ASSET_CONTAINER} variable to build script

- config/environments/production.rb
* 'Frontend' is the common word used on the puppet scripts.
Let's use one name on the puppet scripts and the application
You can see the scripts changes here: https://github.com/moneyadviceservice/scripts/pull/691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1505)
> [DEV APPROVED] Rename responsive prefix to frontend

- README.md
**Note**
Improved MySQL section with instructions on how to install version 5.5 with `homebrew`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1512)
> Update Readme :notebook:

- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1517)
> 7502 - Bumping Budget Planner Gem

- Gemfile.lock
This is related to https://github.com/moneyadviceservice/budget_planner/pull/458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1540)
> Bump budget planner

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1541)
> TP: 7597, Comment: Bumps version of Savings Calculator

- Gemfile
- Gemfile.lock
Relates to PR https://github.com/moneyadviceservice/rio/pull/100 on RIO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1544)
> Bumping rio to 1.7.0

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1545)
> Bumping RIO for 7634

- config/locales/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1367)
> Locales readme

- Gemfile
- Gemfile.lock
Related RIO PR:
https://github.com/moneyadviceservice/rio/pull/104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1554)
> [DEV APPROVED] - 7668 - Bumping rio to 1.8.1

- app/views/layouts/_base.html.erb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1559)
> [DEV APPROVED] - Giving Facebook access to confirm MAS' identity for Instant Articles

- Gemfile
- Gemfile.lock
PR: https://github.com/moneyadviceservice/rio/pull/106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1567)
> Bumping RIO to 1.9.1

- public/articles-sitemap.xml
- public/tools-calculators-sitemap.xml
**Task**
[Card 7722](https://moneyadviceservice.tpondemand.com/entity/7722)
The XML sitemaps have not been updated in over a year and are out of date. This has an impact on how search spiders crawl our site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1584)
> [DEV APPROVED] 7722 update sitemap

- test.sh
Otherwise there are tests that will fail if they rely on the feature to be enable ...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1588)
> Make sure is running CI tests using features.yml

- config/features.yml.sample
Obs.: This test is relying on the feature flat to be disabled,
but on production is enabled. Since there are no disabled-feature
on cucumber I am disabling on the features.yml and creating
an user story to revisit this and do a proper test when the
feature is disabled or enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1589)
> Fix cucumber scenario by turning off feature flag

- app/views/shared/_footer_primary.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Adding the fincap link to the footer
**Screenshot**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1593)
> [DEV APPROVED] 7730 - Adding fincap link to footer

- public/cy/budget-planner-hysbysu.html
- public/en/budget-planner-notification.html
**Task** [7732](https://moneyadviceservice.tpondemand.com/entity/7732)
Update weeks count in static deprecation pages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1595)
> [DEV APPROVED] Update weeks count in static deprecation pages

- Gemfile
- Gemfile.lock
Original PR https://github.com/moneyadviceservice/rio/pull/109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1609)
> 7736 - Bumping rio to 1.12.0

- app/assets/stylesheets/layout/page_specific/_car_campaign.scss
- app/views/campaigns/_section.html.erb
- app/views/campaigns/show.html.erb
Optimising the use of CSS for the car campaign, dropping from 356 lines to 153, a total reduction of 203 lines of CSS.
| [Original page](https://www.moneyadviceservice.org.uk/en/campaigns/revealed-the-true-cost-of-buying-a-car) | [Original page](https://www.moneyadviceservice.org.uk/en/campaigns/how-to-look-ahead-when-buying-a-car) |
|-------|-------|
|![image](https://cloud.githubusercontent.com/assets/13165846/21048842/52db746c-be09-11e6-8e56-bb9cf1488640.png)|![image](https://cloud.githubusercontent.com/assets/13165846/21048821/31302cd6-be09-11e6-8c47-28ef39a7017c.png)|
**Browsers**
| Chrome | Firefox | Safari | IE8 | IE9 | IE11 | MSEDGE |
|----------|------|-------|------|----|----|---------|
|<img src="https://cloud.githubusercontent.com/assets/13165846/21048912/aeaea2fa-be09-11e6-829 …
> [DEV APPROVED] 7840 Car campaign CSS refactor

- app/assets/javascripts/application.js
- app/views/categories/show.html.erb
- app/views/search_results/index.html.erb
- app/views/search_results/index_no_results.html.erb
- app/views/search_results/index_with_results.html.erb
Merging this branch into `global-nav-master`.
Not going to wait for thumbs, as this is approved in PR #1624 - this PR is just for reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1625)
> 7808 - Removing sidenav from where it shouldn't be

- Gemfile.lock
There was a change to the Gemfile.lock that
resulted in a few gems being upgraded without
meaning too.  This commit resets all gems back
to the correct versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1628)
> [DEV APPROVED]Fix gemfile.lock

- Gemfile.lock
Reverts moneyadviceservice/frontend#1628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1630)
> [DEV APPROVED] Revert "[DEV APPROVED]Fix gemfile.lock"

- app/assets/javascripts/application.js
- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/controllers/home_controller.rb
- app/views/layouts/_application_shared.html.erb
- app/views/shared/_global_nav.html.erb
- app/views/shared/_mobile_nav.html.erb
- app/views/shared/svg/_icon_sprite.html.erb
This PR represents the work done on the styling of the global nav so far.
It will need to be reviewed for refining the styles since we are working from a prototype rather than full visual design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1623)
> [WIP] 7772 global nav styling

- app/views/shared/_global_nav.html.erb
Attn @davidtrussler 🙂
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1640)
> [DEV APPROVED] Add extra class to category element if more than 5 subcategories

- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/views/shared/_global_nav.html.erb
- app/views/shared/_mobile_nav.html.erb
This PR updates the Global Nav styles to deal with some visual issues raised in TP7859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1641)
> [WIP] 7859 global nav visual updates

- public/cy/budget_planner_decomission_online.html
- public/en/budget_planner_decomission_online.html
[Card 7854](https://moneyadviceservice.tpondemand.com/entity/7854)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1645)
> [DEV APPROVED] Add email templates for BudgetPlanner decommission

- app/assets/stylesheets/components/common/_search.scss
This updates the colour of the Search button across the site to match the colour used for the Global Nav.
Current: 
Updated: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1657)
> [DEV APPROVED] TP: 7890, Comment: Changes colour of Search button to match Global Nav

- app/assets/javascripts/application.js
- app/assets/javascripts/components/GlobalNav.js
- app/assets/javascripts/require_config.js.erb
- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/views/shared/_global_nav.html.erb
- app/views/shared/_mobile_nav.html.erb
- app/views/shared/_nav.html.erb
- bower.json.erb
This PR adds the behaviour to the Global Nav, primarily: 
- activates rollovers on main clump headings on desktop devices (including slight delay)
- activates different levels on mobile devices
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1644)
> 7773 global nav interaction

- app/controllers/application_controller.rb
- app/controllers/campaigns_controller.rb
- app/controllers/concerns/suppress_menu_button.rb
- app/controllers/debt_management_controller.rb
- app/controllers/embedded_tools_controller.rb
- app/controllers/errors_controller.rb
- app/controllers/landing_pages_controller.rb
- app/controllers/mount_controller.rb
- app/controllers/profile_controller.rb
- app/controllers/registrations_controller.rb
- app/controllers/retirements_controller.rb
- app/controllers/sessions_controller.rb
- app/views/shared/_mobile_nav.html.erb
- spec/views/header_search_box_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1660)
> 7893 - remove logic to conditionally suppress the mobile menu button in header

- app/assets/stylesheets/components/common/_global_nav.scss
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1663)
> Global Nav - Small fix for the button arrows on mobile

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/assets/stylesheets/components/common/_mobile_nav.scss
- app/views/shared/_global_nav.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- Slide in navigation should be full height
- Slide in navigation should only be 80 to 90% the width of the screen
- User should be able to click/press on the remaining area to close the navigation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1664)
> [DEV APPROVED] - 7930 - Global Nav Visual updates

- app/assets/javascripts/components/GlobalNav.js
- app/assets/stylesheets/components/common/_global_nav.scss
- app/assets/stylesheets/components/common/_global_subnav.scss
- app/views/shared/_global_nav.html.erb
Adds extended keyboard interaction and Aria roles/properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1665)
> [DEV APPROVED] TP: 7894, Comment: Improves accessibility of Global Nav

- app/assets/stylesheets/components/common/_global_nav.scss
- app/views/shared/_global_nav.html.erb
- colour of links
- vertical spacing on clumps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1668)
> [DEV APPROVED] TP: 7944, Comment: Fixes some Safari-specific bugs

- app/assets/stylesheets/components/common/_global_nav.scss
The last PR was missing this!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1670)
> TP: 7944, Comment: Adds missing bracket

- app/assets/stylesheets/components/common/_global_nav.scss
The problems this solves are:
- the element triggering the event was inconsistent and so failed to open the subnav in some instances.
- the styles applied to the blog button on hover and focus are inconsistent with the styles applied in the footer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1681)
> TP: 7984, Comment: CSS changes for consistent functioning of dropdown and blog button styles

- config/locales/cy.yml
- config/locales/en.yml
- This is a minor change on PR1685: https://github.com/moneyadviceservice/frontend/pull/1685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1686)
> [DEV APPROVED] TP: 7927, Comment: Updates text on "view less" option

- app/assets/javascripts/components/GlobalNav.js
- when the nav is closed this returns focus to the menu button in the header
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1695)
> [DEV APPROVED]TP: 8035, Comment: Set Talkback/VoiceOver to reset focus on closing

- config/locales/employer_best_practices.en.yml
There were a few spelling and grammar issues on the "Whats in it for my business" page on the employer best practices portal.
On page
https://www.moneyadviceservice.org.uk/en/employer-best-practices/my-business
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1703)
> [DEV APPROVED] 8080 - Correcting spelling mistakes

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1710)
> TP: 8038, Comment: Updates version number for rio to 1.18.0

- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1712)
> [DEV APPROVED]update newrelic_rpm agent gem to latest version

- public/cy/uc_service_email.html
- public/en/uc_service_email.html
Card: [TP#8174](https://moneyadviceservice.tpondemand.com/entity/8174)
Adds the templates for the online version for the service email. This gives users the ability to view the email in their preferred language, English or Welsh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1724)
> [DEV APPROVED] Adds static email templates for UC service mail

- Gemfile
- Gemfile.lock
Related to [this work](https://github.com/moneyadviceservice/action_plans/pull/148).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1731)
> 8170 action_plans better error messages

- public/glossary.json
Adding new Glossary terms for the live A/B test of this feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1733)
> [DEV APPROVED] 8154 new glossary terms

- vendor/assets/javascripts/webchat.js
update web chat.js file to stop site monitoring timing out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1734)
> [DEV APPROVED] update webchat.js

- app/assets/javascripts/components/Glossary.js
- app/assets/javascripts/require_config.js.erb
- app/assets/stylesheets/components/page_specific/_glossary.scss
- app/views/articles/show.html.erb
- public/glossary.json
This ticket was to create a A/B test to add pop up definitions to chosen terms that may users may not know the meaning of. 
The test uses a glossary.js file that was initially created by John Player and expanded by me to add scroll to top functionality for the tooltips. Work was also done to bring the tooltip container into the current styling of the MAS site.
This ticket is connected to #8154 which updates the terms used for the A/B test.
Glossary terms are loaded from a glossary.json file for the purpose of the A/B test. Once the test is done, the glossary.js and glossary.json should be removed from our server. If the test is implemented, a CMS driven iteration on these files will be deployed to production.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> 8039 Glossary terms A/B test

- .github/PULL_REQUEST_TEMPLATE
This PR will solve to standardise our PR process.
Paired with @willhall88 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1741)
> Add an initial PR template to the site

- Gemfile
- Gemfile.lock
Bumps version of UC in front end for ticket #8185
https://moneyadviceservice.tpondemand.com/entity/8185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1742)
> Updates version of UC in frontend

- Gemfile
- Gemfile.lock
PR bumps UC to 2.1.5 for ticket 8226
https://moneyadviceservice.tpondemand.com/entity/8226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1743)
> Bumps to UC tool to version 2.1.5 for ticket 8226

- app/models/user.rb
- spec/models/user_spec.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1300)
> [DEV APPROVED]only update crm if relevant fields are modified

- Gemfile
- Gemfile.lock
Bumps Universal credit to 2.2.2 for ticket 8273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1753)
> Bumps UC to 2.2.2 for ticket 8273

- Gemfile
- Gemfile.lock
In reference to TP ticket [8272](https://moneyadviceservice.tpondemand.com/entity/8272)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1755)
> bumps uc to 2-3-0

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1756)
> Bump universal_credit to 2.3.1

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1758)
> Bump universal credit to 2.4.1

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1761)
> Bump universal_credit to 2.5.0

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1763)
> Bump universal_credit to 2.5.1

- config/locales/cy.yml
- config/locales/en.yml
- spec/helpers/sessions_helper_spec.rb
https://moneyadviceservice.tpondemand.com/entity/8399
**Summary**
Updates the copy on registration page. Removed hard coded reference to translated text (in test).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1766)
> [DEV APPROVED] 8399: Improve registration

- config/locales/cy.yml
- config/locales/en.yml
[TP Link](https://moneyadviceservice.tpondemand.com/entity/8400)
**Summary**
Updates the sign in copy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1767)
> [DEV APPROVED] 8400 - Improve sign in copy

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1769)
> [DEV APPROVED] Bump universal_credit to 2.7.1

- Gemfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1770)
> bump UC version to 2.8.0

- Gemfile
- Gemfile.lock
- db/schema.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1773)
> Bump universal_credit to 2.9.1

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1779)
> Bump universal credit to 2.10.1

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1783)
> Bump universal_credit to 2.10.3

- bower.json.erb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1786)
> Bump yeast to 1.5.4

- app/assets/javascripts/components/HomeBuyingChecklist.js
- app/assets/javascripts/require_config.js.erb
- app/assets/stylesheets/_print.scss
- app/assets/stylesheets/components/common/_popup_tip.scss
- app/assets/stylesheets/components/page_specific/_home_buying_checklist.scss
- app/controllers/home_buying_checklist_controller.rb
- app/views/home_buying_checklist/show.html.erb
- config/locales/home_buying_checklist/home_buying_checklist.cy.yml
- config/locales/home_buying_checklist/home_buying_checklist.en.yml
- config/routes.rb
- spec/controllers/home_buying_checklist_spec.rb
- spec/javascripts/fixtures/HomeBuyingChecklist.html
- spec/javascripts/test-main.js
- spec/javascripts/tests/HomeBuyingChecklist_spec.js
This is a PR for ticket [#8324](https://moneyadviceservice.tpondemand.com/entity/8324) Home Buying Checklist.
- Build a collection of inputs that tally up the numerical total without reloading the page. 
- Display unique informational messages via focus and blur events for each input.
- Display unique informational messages via collapsable component.
- Make the UX/design clean and easy to use.
- Allow for printing and storing via cookie.
- Display simplified mobile view
Tasks completed have been checked. 
| Desktop | Mobile |
|---------|--------|
|![image](https://user-images.githubusercontent.com/2187295/27965697-8df498aa-6334-11e7-890f-d07d83219e26.png) | ![image](https://user-images.githubusercontent.com/2187295/27965763-bba2dd48-6334-11e7-8ade-8576961fb031.png) |
---
This change …
> [DEV APPROVED] 8324 Home Buying Checklist

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1800)
> Bump universal_credit to 2.10.7

- Gemfile
- Gemfile.lock
This PR bumps the version of the WPCC tool for [TP Ticket 8568](https://moneyadviceservice.tpondemand.com/entity/8568)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1807)
> Bumps WPCC tool for TP-8568

- Gemfile.lock
- app/views/errors/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- error message changed from "Internal server error" >>
- Something has gone wrong on our side
This page is currently unavailable, please try reloading, wait a few minutes and try again, or  use the box below to find what you're looking for.
Expedited change request directly from CEO, JPS and Caroline Fawcett
Link to TP ticket
https://moneyadviceservice.tpondemand.com/entity/8569
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1808)
> [WIP] Update HTTP 500 custom error page to a more friendly version

- Gemfile
- Gemfile.lock
[8580 TP Ticket](https://moneyadviceservice.tpondemand.com/entity/8580)
[8572 TP Ticket](https://moneyadviceservice.tpondemand.com/entity/8572)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1812)
> 8580 and 8572 - Bumps WPCC to 1.11.3

- Gemfile
- Gemfile.lock
- bower.json.erb
This is for the following TP tickets on UC:
- [8279](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8279)
- [8500](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8500)
- [8534](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=6C17D8319C81AC3D36AFAD64CAE08A28#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8534)
- …
> [DEV APPROVED] Comment: Bumps version of UC to 2.13.3 and Yeast to 1.6.0

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1821)
> TP: 8608/8609/8611, Comment: Bumps version of UC to 1.11.8

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1826)
> TP: 8588, 8607, 8610, Comment: Updates WPCC version to 1.11.9

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1828)
> Comment: Updates WPCC version to 1.11.10 for 8588/8607/8610

- app/assets/javascripts/syndication/tools.js.coffee
- app/controllers/wpcc_controller.rb
**Target Process ticket**: [TP#8227](https://moneyadviceservice.tpondemand.com/entity/8227)
**Summary**
Adds WPCC to the list of syndicated tools.
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1819)
> [DEV APPROVED] - Adds WPCC to the Syndication tool list

- Gemfile
- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1829)
> TP: 8619, Comment: Updates WPCC version to 1.11.11

- Gemfile
- Gemfile.lock
[TP 8634](https://moneyadviceservice.tpondemand.com/entity/8634)
**Summary**
Bumps WPCC for ticket 8634, [WPCC PR here](https://github.com/moneyadviceservice/wpcc/pull/170)
Tested by Shankar who noticed the bug
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1831)
> Bumps WPCC to 1.11.12 for ticket 8634

- Gemfile
- Gemfile.lock
Updates version of UC for front end.
[TP ](https://moneyadviceservice.tpondemand.com/entity/8616)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1832)
> bumps uc version 2-16-1

- Gemfile
- Gemfile.lock
[TP8621](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=userstory/8621)
**Summary**
Bumps version of timelines to 1.5.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1834)
> TP: 8621, Comment: Bumps version of timelines to 1.5.0

- Gemfile
TP 8655 
Bump agreements engine version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1840)
> [DEV_APPROVED] Bump Agreements engine version 2.2.0

- Gemfile
- Gemfile.lock
https://moneyadviceservice.tpondemand.com/entity/8690
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1848)
> Bump version agreements gem to have reCAPTCHA

- Gemfile
- Gemfile.lock
- db/schema.rb
- features/money_manager.feature
- features/step_definitions/money_manager_steps.rb
- features/support/ui/pages/money_manager.rb
- features/support/ui/pages/money_manager_questionnaire.rb
- features/support/world/pages.rb
[TP 8545](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=feature/8545)
**Summary**
Refer to pr #1858 which was reverted due to a bug, [TP 8747](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/8747). This pr includes a fix for that bug, which is to run a migration setting a default value for the new country field.
Testing notes / guidelines if necessary.
**Checklist**
+ [x] Rubocop is passing for …
> [DEV-APPROVED] UC devolved nation feature

- Gemfile.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1878)
> TP: 7317/8781, Comment: Bumps version of Dough

- Gemfile
- Gemfile.lock
[TP Story](https://moneyadviceservice.tpondemand.com/entity/8704)
PR in UC: https://github.com/moneyadviceservice/universal_credit/pull/215
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1882)
> [DEV APPROVED] Bump UC to 3.0.3

- app/assets/stylesheets/components/page_specific/home_beta/_base.scss
- app/assets/stylesheets/components/page_specific/home_beta/_most_read.scss
- app/assets/stylesheets/components/page_specific/home_beta/_tool_promo.scss
- app/views/home_beta/show.html.erb
- app/views/shared/home_beta/_most_read.html.erb
- app/views/shared/svg/_icon_sprite.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- features/home_beta_page.feature
- features/step_definitions/home_beta_page_steps.rb
- features/support/ui/pages/home_beta.rb
[TP8695](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/8695&appConfig=eyJhY2lkIjoiNDkyNUI4QjYxRTUxM0ZFRUE1RjQwQ0NENDY4N0M1QUQifQ==)
**Summary**
Adds a "Most Read" component to the new homepage design, based on existing content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/frontend/1885)
> [DEV APPROVED] 8695 homepage beta most read component

- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/domain/breadcrumb_trail.rb
- spec/domain/breadcrumb_trail_spec.rb
This PR adds some caching to some of the MAS CMS calls to help improve performance
@pmcostello / @tomas-stefano  have done some performance testing that indicates this branch will be effective.
> [DEV APPROVED] - Add caching the mas cms client calls

- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_1_hitsPerPage_10_query_money.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_34_hitsPerPage_10_query_money.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_35_hitsPerPage_10_query_money.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_hitsPerPage_10_query_Norris.yml
- features/cassettes/algolia/post/1/indexes/pages/query/highlightPreTag_3Cb_3E_highlightPostTag_3C_2Fb_3E_page_hitsPerPage_10_query_money.yml
- features/search.feature
- features/step_definitions/search_page_steps.rb
[TP card](https://moneyadviceservice.tpondemand.com/entity/9100-frontend-site-search-pagination-feature-tests)
**Summary**
The feature tests on the frontend codebase which checked how pagination worked were too tightly tied to Google site search and couldn't be used.  We need to write replacement feature tests which cover pagination as it works under Algolia (and hopefully any future search engines we may use.)
This card will be finished when there are sufficient feature tests to provide confidence in that section of the code base moving forward.
**Checklist**
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ [x] Commit history reviewed (clear …
> [DEV APPROVED] Add feature tests for site search including pagination

- app/views/devise/registrations/new.html.erb
- config/locales/cy.yml
- config/locales/en.yml
[TP ticket 9073](https://moneyadviceservice.tpondemand.com/entity/9073-gdpr-add-privacy-policy-link-to)
Added the link to the privacy policy page at the bottom of the registration page. In both English and Welsh.
> [DEV APPROVED] 9073 gdpr privacy policy

- Gemfile
- Gemfile.lock
> TP: 9280, Comment: WPCC - updates page title for SEO

- .env-example
- README.md
Minor updates to reduce errors when setting up a local development environment.
> [DEV APPROVED] - Doc and configuration updates for dev environment setup

- spec/requests/tool_integration/pacs_spec.rb
Refer to [Pacs pr#127](https://github.com/moneyadviceservice/pacs/pull/127) which addresses [TP 9694](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=task/9746&appConfig=eyJhY2lkIjoiQkIwRTkyREU5NjQ4RUNBNkIwRTM0REFBMEY3OEJEMjAifQ==&searchPopup=userstory/9694)
The pacs tests need to be updated for changes implemented in the pacs engine for filtering.
We need to stub some class methods which the pacs engine controller
calls in order to assign variables for the root view.
This is a short term solution and we may want to revisit how
we assign these variables in pacs longer term.
**Checklist**
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ [x] Code …
> Update request spec for pacs engine

- app/assets/stylesheets/components/common/_footer_primary.scss
- app/views/shared/_footer_primary.html.erb
- config/locales/cy.yml
- config/locales/en.yml
[TP 10123](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10123/silent)
**Summary**
The website footer should include a copyright notice with the year, name and address of The Money Advice Service
**Checklist**
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ [x] Code Climate passed for this PR.
> [DEV APPROVED] - Add copyright notice to the footer

- Gemfile
- Gemfile.lock
[TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10117/silent)
[TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10158/silent)
**Summary**
Remove unused legacy code block 
Update Ruby to 2.5.3
> [DEV APPROVED] Bump Cream gem to 2.1.7

- Gemfile
- Gemfile.lock
> Upgrade Action Plans gem to v5.0.0

- Gemfile
- Gemfile.lock
[TP10188](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=bug/10188)
Bumps version of Dough.
> Bumps version of Dough

- app/views/layouts/_base.html.erb
[TP10212](https://moneyadviceservice.tpondemand.com/entity/10212-get-pinterest-verified)
Really straightforward bit of work just to add in a meta tag generated by pinterest so that they can verify MAS
> [DEV APPROVED] 10212 MAS pinterest verification tag

- Gemfile
- Gemfile.lock
Bump pacs to version 3.5.1 for pinterest verification
> Bump pacs to 3.5.1 for pinterest verification

- Gemfile
- Gemfile.lock
**Summary**
#2082 accidentally added mas-assets back into the gemfile. It had been removed in #2073. this PR is to remove it again
> [DEV APPROVED] Remove mas-assets - accidentally got added in during jquery upgrade

- Gemfile
- Gemfile.lock
> Bump timelines version

- bower.json.erb
[TP 10467](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10467/silent)
Updated the version of Yeast regarding changes to footer colour.
> [DEV APPROVED] Yeast Version Bump

- bower.json.erb
[TP 10468](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10468/silent)
**Summary**
Bumping Yeast version in front end to reflect the latest changes.
> [DEV APPROVED] Bumped Yeast Version in Bower

- Gemfile
- Gemfile.lock
Brings changes for the Redundancy Pay calculator maximum weekly
pay numbers.
> TP-10502: Upgrate Action Plans gem to v5.1.0

- app/helpers/contact_panels_helper.rb
- app/views/shared/_contact_panels.html.erb
Abstract some logic from the view to a helper.
> [DEV APPROVED] - Refactor: Improve readability of html

- app/views/shared/_contact_panels.html.erb
[TP 10549](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=bug/10549/silent)
This PR fixes an issue with domain creation for webchat url.
> [DEV APPROVED] 10549 - Webchat not accessible

- config/locales/cy.yml
- config/locales/en.yml
[TP 10590](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiMDBCQzE4QjNDMUI0NTgyN0EyMDRDMjRCMDQ0Qjc0NEEifQ==&boardPopup=bug/10590/silent)
WhatsApp contact number is corrected in the contact panel located at the bottom of every page.
> [DEV APPROVED] 10590 - Corrected WhatsApp Number in Footer

- Gemfile
- Gemfile.lock
> Bump cream gem

- app/assets/stylesheets/components/page_specific/_floating_chat.scss
- app/controllers/concerns/chat.rb
- app/views/shared/_contact_panels.html.erb
- app/views/shared/_webchat_popup.html.erb
- app/views/shared/_webchat_popup_pensions.html.erb
- config/application.rb
[TP10697](https://maps.tpondemand.com/entity/10697-restrict-visibility-of-pensions-chat-popup)
This PR aims to restrict the visibility of the pensions popup in line with the TPAS opening hours.
9am to 6.20pm Monday to Friday
> [DEV APPROVED] - Pensions Popup Opening Hours

- bower.json.erb
[TP10644](https://maps.tpondemand.com/entity/10644-rad-bring-styles-from-frontend-onto)
> Updates Yeast dependency version

- app/views/pace/_faqs.html.erb
- app/views/pace/_nav.html.erb
- app/views/pace/_online_advice.html.erb
- app/views/pace/_organisations.html.erb
- app/views/pace/_referred.html.erb
Reverts moneyadviceservice/frontend#2188
> Revert "[DEV APPROVED] 11111 pace tagging"

- app/views/pace/_privacy.html.erb
- config/locales/pace.en.yml
- config/routes.rb
Reverts moneyadviceservice/frontend#2185
> Revert "[DEV APPROVED] Updates PACE URL"

- app/views/sitemap/robots.text.erb
Reverts moneyadviceservice/frontend#2187
> Revert "[DEV APPROVED] Adds the PACE privacy URL to the robots.txt file "

- app/assets/stylesheets/layout/page_specific/_pace.scss
- app/views/layouts/pace.html.erb
- app/views/pace/privacy.html.erb
- app/views/pace/show.html.erb
- config/locales/pace.en.yml
[TP11221](https://maps.tpondemand.com/entity/11221-pace-add-content-to-privacy-policy)
This work adds the content to the PACE privacy page. 
Additionally it updates the base layout files for this and the landing page to enable the the nav to be selectively displayed on the landing page only.
> [DEV APPROVED] 11221 pace privacy policy content

- app/views/pace/_help.html.erb
- config/locales/pace.en.yml
[TP11232](https://maps.tpondemand.com/entity/11232-pace-update-copy-content-v-02)
This adds some further copy changes to the PACE project.
> [DEV APPROVED] text changes

- app/views/content_hub/blocks/_vid_hdr_lnks.html.erb
- config/locales/content_hub/coronavirus_support.en.yml
- config/locales/content_hub/cymorth_coronafeirws.cy.yml
Corona virus hub changes detailed in TP_11438
https://maps.tpondemand.com/restui/board.aspx?#page=userstory/11438&appConfig=eyJhY2lkIjoiQjhCQkYxQUQ5NjMwRjE0Mjg4N0Q0QUIwOTYzNzU4NUEifQ==
> Chore/tp 11438/corona virus hub page update

- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
Adds a hidden style for the results page of the Money Navigator.
> Adds hidden style for overlay

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/views/money_navigator_tool/questionnaire.html.erb
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP11595](https://maps.tpondemand.com/entity/11595-money-navigator-replace-hardcoded-button-text)
This PR implements dynamic translations to the question buttons using the current i18n yaml files by adding its values to the dough component config in javascript.
Note: My editor has removed some existing unnecessary spaces and semi-colons throughout the modified files so please ignore those changes.
> 11595 - Hardcoded Button Text

- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
[TP11556](https://maps.tpondemand.com/entity/11556-change-the-intro-banner-from-advice)
This work makes a copy change to the banner on the Questions page. The change is for the Welsh language only. Screenshots below. 
**Current**
**Updated**
> [DEV APPROVED] [TP11556] Updates copy in banner on Questions page

- app/models/concerns/symbols.rb
this contains the production bugfixes of the copy change errors discovered by the tests as part of [TP-11529](https://maps.tpondemand.com/RestUI/Board.aspx#page=userstory/11529&appConfig=eyJhY2lkIjoiMzg2RDNFNEYzQ0UyRTIxMkZDMEY3QTNBNkFBOEFGQjEifQ==). they have also been merged into the main feature branch for this ticket.
> [TP-11529] Fixed copy error bugs uncovered by testing

- Gemfile.lock
This PR is an outcome of [TP-11372](https://maps.tpondemand.com/entity/11372-spike-2days-address-growing-list-of) as detailed in the ticket
> [TP-11372] bundle updated rubyzip

- Gemfile.lock
This PR is an outcome of [TP-11372](https://maps.tpondemand.com/entity/11372-spike-2days-address-growing-list-of) as detailed in the ticket
> [TP-11372] bundle updated nokogiri

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
[TP11685](https://maps.tpondemand.com/entity/11685-money-navigator-technical-debt-improve-code)
The changes in this PR make some updates to the Questions Component in order to tidy it up a little and make it more consistent with other components. 
The main change involved is to replace updates to the DOM currently made by appending strings with code that programatically creates elements and inserts them into the DOM. 
Other changes add some documentation to explain the purpose of various methods and a little general tidying for consistency. 
I considered the use of a RegEx expression mentioned in the TP card and decided it would not be a viable way of achieving what needs to be done. 
None of these changes should make any visible differences to the users of the tool, they are all aimed at …
> 11685 money navigator questions js improvements

- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
This is a combination of two PRs created to deploy together.
> 11821 11817 money navigator copy changes

- app/models/concerns/money_navigator/rules/urgent_action.rb
> [TP-11823] Removed extra comma in rule criterion

- app/models/concerns/money_navigator/rules/urgent_action.rb
- features/factories/money_navigator/urgent_cta_rules.rb
This fixes the bug detailed in [TP-11875](https://maps.tpondemand.com/entity/11875-update-stepchange-cvpp-cta-logic-to)
> [TP-11875] Fixed and tested

- Gemfile
- Gemfile.lock
LINK_TO_TICKET
**Summary**
Brief description of the ticket.
**Examples (optional)**
Before / after images of any visual / ui updates.
Testing notes / guidelines if necessary.
**Checklist**
+ [ ] Tests passed.
+ [ ] Rubocop is passing for this PR (or any other lint like JShint).
+ [ ] Commit history reviewed (clear commit messages).
> [Bugfix] Revert unpinned gems

- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
[TP-11722](https://maps.tpondemand.com/entity/11722-money-navigator-focus-style-issue)
This work is primarily concerned with removing a small inconsistency in the way the focus styles display on questions containing the Yes/No options. As part of the same piece of work some generic styling has been applied to this and to two other types of questions which are not currently showing the correct focus styles, so that in total this updates the focus on three types of questions:
- those that include "Yes"/"No" buttons (4 questions)
- the initial question (“Where do you live?”) and 
- the other enhanced UI (“Are you behind with rent or mortgage payments?”)
To do this some existing focus styles have been removed and some refactoring carried out to add consistency across different formats of …
> [DEV APPROVED] 11722 money navigator focus styles

- app/assets/javascripts/components/MoneyNavigatorQuestions.js
- app/assets/stylesheets/layout/page_specific/_money_navigator_landing.scss
- app/assets/stylesheets/layout/page_specific/_money_navigator_questionnaire.scss
- app/assets/stylesheets/layout/page_specific/_money_navigator_results.scss
- app/views/money_navigator_tool/questionnaire.html.erb
- spec/javascripts/fixtures/MoneyNavigatorQuestions.html
- spec/javascripts/tests/MoneyNavigatorQuestions_spec.js
[TP-11929](https://maps.tpondemand.com/entity/11929-money-navigator-a11y)
This is a feature branch created from five previously approved commits relating to the following TP cards: 
- TP-11667
- TP-11722
- TP-11822
- TP-11923
- TP-11967
> Tp 11929 money navigator feature a11 y audit 201221

- Gemfile.lock
[TP-12557](https://maps.tpondemand.com/entity/12557-fix-xss-cross-site-scripting-issue)
Add test for OrganisationSearchDecorator, which includes a XSS attack in the query string.
Update OrganisationSearchDecorator to strip <script> tags and sanitize any query string, before rendering as html_safe
> TP 12557 XSS in DALT

- Gemfile
- Gemfile.lock
Updates version of acton_plans to 5.7.0
> [TP-12528] Redundancy Pay Calculator, Y/E benefits copy updates

- Gemfile
- Gemfile.lock
[TP-12225](https://maps.tpondemand.com/entity/12225-money-manager-talking-to-my-landlord)
Updates link on final page.
> 12225 universal credit update link

- Gemfile
- Gemfile.lock
Includes 12642, 12597, 12632 and 12609.
> TP-12609 bump WPCC for UAT/production

- app/assets/javascripts/syndication/tools.js.coffee
**Ticket 12857:**  [https://maps.tpondemand.com/restui/board.aspx?#page=userstory/12857](url)
**Description**
Updated the logo link, the logo image and the alternative text as per the ticket for the partner tools
> 12857: Update logo and logo link for partner tools

- package.json
- spec/javascripts/karma.conf.js
Reverts moneyadviceservice/frontend#2364
> Revert "Fix karma build failures"

- app/models/concerns/money_navigator/rules/urgent_action.rb
- config/locales/money_navigator_tool/money_navigator_tool.cy.yml
- config/locales/money_navigator_tool/money_navigator_tool.en.yml
- features/factories/money_navigator/borrowing_money_rules.rb
- features/factories/money_navigator/housing_costs_rules.rb
- features/factories/money_navigator/mental_health_rules.rb
- features/factories/money_navigator/money_and_work_rules.rb
- features/factories/money_navigator/non_priority_bills_rules.rb
- features/factories/money_navigator/payment_holiday_rules.rb
- features/factories/money_navigator/priority_bills_rules.rb
- features/factories/money_navigator/protecting_your_future_rules.rb
- features/factories/money_navigator/urgent_cta_rules.rb
- features/factories/money_navigator/using_pension_equity_savings_rules.rb
- features/factories/money_navigator/your_money_moving_forward_rules.rb
- spec/decorators/chat_opening_hours_decorator_spec.rb
- spec/javascripts/karma.conf.js
- spec/models/money_navigator/rules/urgent_cta_rules_spec.rb
https://maps.tpondemand.com/entity/12893-update-money-navigator-to-removechange-questions
https://maps.tpondemand.com/entity/12889-update-moneynavigator-to-remove-cvpp-banner
> Tp 12889 logic changes

- app/views/layouts/_constrained.html.erb
https://dev.azure.com.mcas.ms/moneyandpensionsservice/Digital%20Experience%20Platform%20-%20AEM/_boards/board/t/Team%201%20(Digital%20Support%20and%20Maintenance)/Stories/?workitem=2502
**Summary**
Debt Advice Locator: Iframe should scroll to top when region clicked
Steps to reproduce:
- Visit the iframed debt advice locator tool
- Scroll to the bottom of the page where there are links to specific regions:
- Click on one of the links (for example **Belfast**
- The page should scroll to the top of the iframe
**Checklist**
+ [ ] Tests passed.
+ [ ] Rubocop is passing for this PR (or any other lint like JShint).
+ [ ] Commit history …
> Always scroll to top

- app/assets/javascripts/syndication/iframeScroller.js
- app/views/layouts/_base.html.erb
- config/initializers/assets.rb
https://dev.azure.com.mcas.ms/moneyandpensionsservice/Digital%20Experience%20Platform%20-%20AEM/_boards/board/t/Team%201%20(Digital%20Support%20and%20Maintenance)/Stories/?workitem=2502
**Summary**
This moves the automatic iframe scrolling code to somewhere more general, because it wasn't showing up on some pages.
Comes from this change: https://github.com/moneyadviceservice/frontend/pull/2371
> Add scrolling code to a more general area

- app/controllers/redirectors_controller.rb
To try and debug why the redirector doesn't work in production.
> Log redirect failures in production

- app/controllers/redirectors_controller.rb
This is because for some reason I can't access the rails logs for this page right now.
This should prove whether it's nginx or rails causing the 404.
> Render an html error

- app/controllers/redirectors_controller.rb
This PR adds new redirects for three tools. The redirector sets a cookie in the browser to get around the Safari third-party cookies in iframes issues, and then redirects to the correct tool page in AEM.
[LINK_TO_TICKET](https://dev.azure.com.mcas.ms/moneyandpensionsservice/Digital%20Experience%20Platform%20-%20AEM/_boards/board/t/Team%201%20(Digital%20Support%20and%20Maintenance)/Stories/?workitem=2947)
**Checklist**
+ [ ] Tests passed.
+ [ ] Rubocop is passing for this PR (or any other lint like JShint).
+ [ ] Commit history reviewed (clear commit messages).
> Add redirector urls for more tools

- Gemfile
- Gemfile.lock
Bumps the WPCC tool engine to remove gender.
> Bump WPCC gem to remove genders

- app/assets/javascripts/modules/IE11ImageLabelFix.js
Refactor and fix code that wasn't working 100% of the time.
> Refactor IE11 image in label fix

- Gemfile.lock
This is while we incorporate the latest changes.
> Add a temporary banner for stamp duty

- app/views/layouts/_base.html.erb
As requested by the data folks.
> Include launcher script reference for analytics

- Gemfile
- Gemfile.lock
Change to the JSA and year ends.
> Bump `action_plans` for redundancy year end

- Gemfile.lock
> Bump debt advice tool to remove covid banner

- lib/legacy_redirects.rb
- spec/requests/legacy_redirects_spec.rb
> Ensure www is canonicalised for redirects

- Gemfile
- Gemfile.lock
- app/controllers/embedded_tools_controller.rb
- app/views/layouts/_base.html.erb
- features/adobe_analytics.feature
- features/step_definitions/adobe_analytics_steps.rb
- features/support/env.rb
- features/support/vcr.rb
Adds the basic fields required in the Adobe data layer for analytics and reporting.
> Adobe analytics

- lib/legacy_redirects.rb
- spec/requests/legacy_redirects_spec.rb
These have been requested for SEO purposes.
> Redirect to tool embed pages not landing pages

- app/assets/javascripts/syndication/tools.js.coffee
This nerfs the resizer in syndication otherwise.
> Remove explicit heights being set

- app/assets/javascripts/syndication/tools.js.coffee
- app/assets/javascripts/syndication/widget.js.coffee
This hasn't been functional in a long time so can be removed.
> Remove legacy GA iframe in syndication
